# 리스트 표현식
* 리스트 안에 for 반복문과 if else 조건문을 한 번에 적어서 리스트를 만드는 방법
* 여러 줄의 코드를 1줄로 줄일 수 있다.
* for문과 if else문을 사용해서 처리할 때 보다 속도가 빠르다.
* [실행할 명령 for 변수 in list, tuple]

In [22]:
for i in range(1, 11):
    print(f"{i}는 짝수입니다.") if i % 2 == 0 else print(f"{i}는 홀수입니다.")

1는 홀수입니다.
2는 짝수입니다.
3는 홀수입니다.
4는 짝수입니다.
5는 홀수입니다.
6는 짝수입니다.
7는 홀수입니다.
8는 짝수입니다.
9는 홀수입니다.
10는 짝수입니다.

* 1부터 10까지 들어있는 리스트 만들기

In [2]:
l1 = []
for i in range(1, 11):
    l1.append(i)
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
[i for i in range(1, 11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## 리스트 표현식과 일반 반복문의 속도 차이

In [4]:
import time

In [5]:
%%time
# start = time.time()
a = []
for i in range(1, 200000000):
    a.append(i + 5)
print(a[:10])

# print("코드 실행 시간: ", time.time() - start)

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
CPU times: total: 17.3 s
Wall time: 17.4 s

In [6]:
%%time
# start2 = time.time()
b = [i+5 for i in range(1, 200000000)]
print(b[:10])
# print("코드 실행 시간: ", time.time() - start2)

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
CPU times: total: 10.7 s
Wall time: 10.8 s

In [7]:
# !pip install numpy

In [8]:
import numpy as np

In [9]:
%%time
# start3 = time.time()

c = np.arange(1, 200000000)
c = c + 5
print(c[:10])
# print("코드 실행 시간: ", time.time() - start3)

[ 6  7  8  9 10 11 12 13 14 15]
CPU times: total: 891 ms
Wall time: 940 ms

* 1에서 10까지의 숫자중 짝수만 넣어서 리스트 만들기

In [10]:
l1 = []
for i in range(1, 11):
    if i % 2 ==0:
        l1.append(i)
l1

[2, 4, 6, 8, 10]

In [11]:
l2 = [i for i in range(1, 11) if i % 2 ==0]
l2

[2, 4, 6, 8, 10]

## 다중 반복문을 사용한 리스트 표현식
[i * j for i in range(2, 10) for j in range(1, 9)]

In [12]:
gugu = []
for i in range(2, 10):
    for j in range(1, 10):
        gugu.append(f"{i} X {j} = {i*j}")
gugu

['2 X 1 = 2',
 '2 X 2 = 4',
 '2 X 3 = 6',
 '2 X 4 = 8',
 '2 X 5 = 10',
 '2 X 6 = 12',
 '2 X 7 = 14',
 '2 X 8 = 16',
 '2 X 9 = 18',
 '3 X 1 = 3',
 '3 X 2 = 6',
 '3 X 3 = 9',
 '3 X 4 = 12',
 '3 X 5 = 15',
 '3 X 6 = 18',
 '3 X 7 = 21',
 '3 X 8 = 24',
 '3 X 9 = 27',
 '4 X 1 = 4',
 '4 X 2 = 8',
 '4 X 3 = 12',
 '4 X 4 = 16',
 '4 X 5 = 20',
 '4 X 6 = 24',
 '4 X 7 = 28',
 '4 X 8 = 32',
 '4 X 9 = 36',
 '5 X 1 = 5',
 '5 X 2 = 10',
 '5 X 3 = 15',
 '5 X 4 = 20',
 '5 X 5 = 25',
 '5 X 6 = 30',
 '5 X 7 = 35',
 '5 X 8 = 40',
 '5 X 9 = 45',
 '6 X 1 = 6',
 '6 X 2 = 12',
 '6 X 3 = 18',
 '6 X 4 = 24',
 '6 X 5 = 30',
 '6 X 6 = 36',
 '6 X 7 = 42',
 '6 X 8 = 48',
 '6 X 9 = 54',
 '7 X 1 = 7',
 '7 X 2 = 14',
 '7 X 3 = 21',
 '7 X 4 = 28',
 '7 X 5 = 35',
 '7 X 6 = 42',
 '7 X 7 = 49',
 '7 X 8 = 56',
 '7 X 9 = 63',
 '8 X 1 = 8',
 '8 X 2 = 16',
 '8 X 3 = 24',
 '8 X 4 = 32',
 '8 X 5 = 40',
 '8 X 6 = 48',
 '8 X 7 = 56',
 '8 X 8 = 64',
 '8 X 9 = 72',
 '9 X 1 = 9',
 '9 X 2 = 18',
 '9 X 3 = 27',
 '9 X 4 = 36',
 '9 X 5 = 45',
 '9 X 6 = 54',
 '9 X 7 = 63',
 '9 X 8 = 72',
 '9 X 9 = 81']

In [ ]:

[f"{i} X {j} = {i*j}" for i in range(2, 10) for j in range(1, 10)]

In [13]:
[f"{i} X {j} = {i*j}" for i in range(2, 10) for j in range(1, 10)]

['2 X 1 = 2',
 '2 X 2 = 4',
 '2 X 3 = 6',
 '2 X 4 = 8',
 '2 X 5 = 10',
 '2 X 6 = 12',
 '2 X 7 = 14',
 '2 X 8 = 16',
 '2 X 9 = 18',
 '3 X 1 = 3',
 '3 X 2 = 6',
 '3 X 3 = 9',
 '3 X 4 = 12',
 '3 X 5 = 15',
 '3 X 6 = 18',
 '3 X 7 = 21',
 '3 X 8 = 24',
 '3 X 9 = 27',
 '4 X 1 = 4',
 '4 X 2 = 8',
 '4 X 3 = 12',
 '4 X 4 = 16',
 '4 X 5 = 20',
 '4 X 6 = 24',
 '4 X 7 = 28',
 '4 X 8 = 32',
 '4 X 9 = 36',
 '5 X 1 = 5',
 '5 X 2 = 10',
 '5 X 3 = 15',
 '5 X 4 = 20',
 '5 X 5 = 25',
 '5 X 6 = 30',
 '5 X 7 = 35',
 '5 X 8 = 40',
 '5 X 9 = 45',
 '6 X 1 = 6',
 '6 X 2 = 12',
 '6 X 3 = 18',
 '6 X 4 = 24',
 '6 X 5 = 30',
 '6 X 6 = 36',
 '6 X 7 = 42',
 '6 X 8 = 48',
 '6 X 9 = 54',
 '7 X 1 = 7',
 '7 X 2 = 14',
 '7 X 3 = 21',
 '7 X 4 = 28',
 '7 X 5 = 35',
 '7 X 6 = 42',
 '7 X 7 = 49',
 '7 X 8 = 56',
 '7 X 9 = 63',
 '8 X 1 = 8',
 '8 X 2 = 16',
 '8 X 3 = 24',
 '8 X 4 = 32',
 '8 X 5 = 40',
 '8 X 6 = 48',
 '8 X 7 = 56',
 '8 X 8 = 64',
 '8 X 9 = 72',
 '9 X 1 = 9',
 '9 X 2 = 18',
 '9 X 3 = 27',
 '9 X 4 = 36',
 '9 X 5 = 45',
 '9 X 6 = 54',
 '9 X 7 = 63',
 '9 X 8 = 72',
 '9 X 9 = 81']

In [26]:
[f"{si:02d}:{bun:02d}:{cho:02d}" for si in range(0, 23) for bun in range(0, 60) for cho in range(0, 60)]

['00:00:00',
 '00:00:01',
 '00:00:02',
 '00:00:03',
 '00:00:04',
 '00:00:05',
 '00:00:06',
 '00:00:07',
 '00:00:08',
 '00:00:09',
 '00:00:10',
 '00:00:11',
 '00:00:12',
 '00:00:13',
 '00:00:14',
 '00:00:15',
 '00:00:16',
 '00:00:17',
 '00:00:18',
 '00:00:19',
 '00:00:20',
 '00:00:21',
 '00:00:22',
 '00:00:23',
 '00:00:24',
 '00:00:25',
 '00:00:26',
 '00:00:27',
 '00:00:28',
 '00:00:29',
 '00:00:30',
 '00:00:31',
 '00:00:32',
 '00:00:33',
 '00:00:34',
 '00:00:35',
 '00:00:36',
 '00:00:37',
 '00:00:38',
 '00:00:39',
 '00:00:40',
 '00:00:41',
 '00:00:42',
 '00:00:43',
 '00:00:44',
 '00:00:45',
 '00:00:46',
 '00:00:47',
 '00:00:48',
 '00:00:49',
 '00:00:50',
 '00:00:51',
 '00:00:52',
 '00:00:53',
 '00:00:54',
 '00:00:55',
 '00:00:56',
 '00:00:57',
 '00:00:58',
 '00:00:59',
 '00:01:00',
 '00:01:01',
 '00:01:02',
 '00:01:03',
 '00:01:04',
 '00:01:05',
 '00:01:06',
 '00:01:07',
 '00:01:08',
 '00:01:09',
 '00:01:10',
 '00:01:11',
 '00:01:12',
 '00:01:13',
 '00:01:14',
 '00:01:15',
 '00:01:16',
 '00:01:17',
 '00:01:18',
 '00:01:19',
 '00:01:20',
 '00:01:21',
 '00:01:22',
 '00:01:23',
 '00:01:24',
 '00:01:25',
 '00:01:26',
 '00:01:27',
 '00:01:28',
 '00:01:29',
 '00:01:30',
 '00:01:31',
 '00:01:32',
 '00:01:33',
 '00:01:34',
 '00:01:35',
 '00:01:36',
 '00:01:37',
 '00:01:38',
 '00:01:39',
 '00:01:40',
 '00:01:41',
 '00:01:42',
 '00:01:43',
 '00:01:44',
 '00:01:45',
 '00:01:46',
 '00:01:47',
 '00:01:48',
 '00:01:49',
 '00:01:50',
 '00:01:51',
 '00:01:52',
 '00:01:53',
 '00:01:54',
 '00:01:55',
 '00:01:56',
 '00:01:57',
 '00:01:58',
 '00:01:59',
 '00:02:00',
 '00:02:01',
 '00:02:02',
 '00:02:03',
 '00:02:04',
 '00:02:05',
 '00:02:06',
 '00:02:07',
 '00:02:08',
 '00:02:09',
 '00:02:10',
 '00:02:11',
 '00:02:12',
 '00:02:13',
 '00:02:14',
 '00:02:15',
 '00:02:16',
 '00:02:17',
 '00:02:18',
 '00:02:19',
 '00:02:20',
 '00:02:21',
 '00:02:22',
 '00:02:23',
 '00:02:24',
 '00:02:25',
 '00:02:26',
 '00:02:27',
 '00:02:28',
 '00:02:29',
 '00:02:30',
 '00:02:31',
 '00:02:32',
 '00:02:33',
 '00:02:34',
 '00:02:35',
 '00:02:36',
 '00:02:37',
 '00:02:38',
 '00:02:39',
 '00:02:40',
 '00:02:41',
 '00:02:42',
 '00:02:43',
 '00:02:44',
 '00:02:45',
 '00:02:46',
 '00:02:47',
 '00:02:48',
 '00:02:49',
 '00:02:50',
 '00:02:51',
 '00:02:52',
 '00:02:53',
 '00:02:54',
 '00:02:55',
 '00:02:56',
 '00:02:57',
 '00:02:58',
 '00:02:59',
 '00:03:00',
 '00:03:01',
 '00:03:02',
 '00:03:03',
 '00:03:04',
 '00:03:05',
 '00:03:06',
 '00:03:07',
 '00:03:08',
 '00:03:09',
 '00:03:10',
 '00:03:11',
 '00:03:12',
 '00:03:13',
 '00:03:14',
 '00:03:15',
 '00:03:16',
 '00:03:17',
 '00:03:18',
 '00:03:19',
 '00:03:20',
 '00:03:21',
 '00:03:22',
 '00:03:23',
 '00:03:24',
 '00:03:25',
 '00:03:26',
 '00:03:27',
 '00:03:28',
 '00:03:29',
 '00:03:30',
 '00:03:31',
 '00:03:32',
 '00:03:33',
 '00:03:34',
 '00:03:35',
 '00:03:36',
 '00:03:37',
 '00:03:38',
 '00:03:39',
 '00:03:40',
 '00:03:41',
 '00:03:42',
 '00:03:43',
 '00:03:44',
 '00:03:45',
 '00:03:46',
 '00:03:47',
 '00:03:48',
 '00:03:49',
 '00:03:50',
 '00:03:51',
 '00:03:52',
 '00:03:53',
 '00:03:54',
 '00:03:55',
 '00:03:56',
 '00:03:57',
 '00:03:58',
 '00:03:59',
 '00:04:00',
 '00:04:01',
 '00:04:02',
 '00:04:03',
 '00:04:04',
 '00:04:05',
 '00:04:06',
 '00:04:07',
 '00:04:08',
 '00:04:09',
 '00:04:10',
 '00:04:11',
 '00:04:12',
 '00:04:13',
 '00:04:14',
 '00:04:15',
 '00:04:16',
 '00:04:17',
 '00:04:18',
 '00:04:19',
 '00:04:20',
 '00:04:21',
 '00:04:22',
 '00:04:23',
 '00:04:24',
 '00:04:25',
 '00:04:26',
 '00:04:27',
 '00:04:28',
 '00:04:29',
 '00:04:30',
 '00:04:31',
 '00:04:32',
 '00:04:33',
 '00:04:34',
 '00:04:35',
 '00:04:36',
 '00:04:37',
 '00:04:38',
 '00:04:39',
 '00:04:40',
 '00:04:41',
 '00:04:42',
 '00:04:43',
 '00:04:44',
 '00:04:45',
 '00:04:46',
 '00:04:47',
 '00:04:48',
 '00:04:49',
 '00:04:50',
 '00:04:51',
 '00:04:52',
 '00:04:53',
 '00:04:54',
 '00:04:55',
 '00:04:56',
 '00:04:57',
 '00:04:58',
 '00:04:59',
 '00:05:00',
 '00:05:01',
 '00:05:02',
 '00:05:03',
 '00:05:04',
 '00:05:05',
 '00:05:06',
 '00:05:07',
 '00:05:08',
 '00:05:09',
 '00:05:10',
 '00:05:11',
 '00:05:12',
 '00:05:13',
 '00:05:14',
 '00:05:15',
 '00:05:16',
 '00:05:17',
 '00:05:18',
 '00:05:19',
 '00:05:20',
 '00:05:21',
 '00:05:22',
 '00:05:23',
 '00:05:24',
 '00:05:25',
 '00:05:26',
 '00:05:27',
 '00:05:28',
 '00:05:29',
 '00:05:30',
 '00:05:31',
 '00:05:32',
 '00:05:33',
 '00:05:34',
 '00:05:35',
 '00:05:36',
 '00:05:37',
 '00:05:38',
 '00:05:39',
 '00:05:40',
 '00:05:41',
 '00:05:42',
 '00:05:43',
 '00:05:44',
 '00:05:45',
 '00:05:46',
 '00:05:47',
 '00:05:48',
 '00:05:49',
 '00:05:50',
 '00:05:51',
 '00:05:52',
 '00:05:53',
 '00:05:54',
 '00:05:55',
 '00:05:56',
 '00:05:57',
 '00:05:58',
 '00:05:59',
 '00:06:00',
 '00:06:01',
 '00:06:02',
 '00:06:03',
 '00:06:04',
 '00:06:05',
 '00:06:06',
 '00:06:07',
 '00:06:08',
 '00:06:09',
 '00:06:10',
 '00:06:11',
 '00:06:12',
 '00:06:13',
 '00:06:14',
 '00:06:15',
 '00:06:16',
 '00:06:17',
 '00:06:18',
 '00:06:19',
 '00:06:20',
 '00:06:21',
 '00:06:22',
 '00:06:23',
 '00:06:24',
 '00:06:25',
 '00:06:26',
 '00:06:27',
 '00:06:28',
 '00:06:29',
 '00:06:30',
 '00:06:31',
 '00:06:32',
 '00:06:33',
 '00:06:34',
 '00:06:35',
 '00:06:36',
 '00:06:37',
 '00:06:38',
 '00:06:39',
 '00:06:40',
 '00:06:41',
 '00:06:42',
 '00:06:43',
 '00:06:44',
 '00:06:45',
 '00:06:46',
 '00:06:47',
 '00:06:48',
 '00:06:49',
 '00:06:50',
 '00:06:51',
 '00:06:52',
 '00:06:53',
 '00:06:54',
 '00:06:55',
 '00:06:56',
 '00:06:57',
 '00:06:58',
 '00:06:59',
 '00:07:00',
 '00:07:01',
 '00:07:02',
 '00:07:03',
 '00:07:04',
 '00:07:05',
 '00:07:06',
 '00:07:07',
 '00:07:08',
 '00:07:09',
 '00:07:10',
 '00:07:11',
 '00:07:12',
 '00:07:13',
 '00:07:14',
 '00:07:15',
 '00:07:16',
 '00:07:17',
 '00:07:18',
 '00:07:19',
 '00:07:20',
 '00:07:21',
 '00:07:22',
 '00:07:23',
 '00:07:24',
 '00:07:25',
 '00:07:26',
 '00:07:27',
 '00:07:28',
 '00:07:29',
 '00:07:30',
 '00:07:31',
 '00:07:32',
 '00:07:33',
 '00:07:34',
 '00:07:35',
 '00:07:36',
 '00:07:37',
 '00:07:38',
 '00:07:39',
 '00:07:40',
 '00:07:41',
 '00:07:42',
 '00:07:43',
 '00:07:44',
 '00:07:45',
 '00:07:46',
 '00:07:47',
 '00:07:48',
 '00:07:49',
 '00:07:50',
 '00:07:51',
 '00:07:52',
 '00:07:53',
 '00:07:54',
 '00:07:55',
 '00:07:56',
 '00:07:57',
 '00:07:58',
 '00:07:59',
 '00:08:00',
 '00:08:01',
 '00:08:02',
 '00:08:03',
 '00:08:04',
 '00:08:05',
 '00:08:06',
 '00:08:07',
 '00:08:08',
 '00:08:09',
 '00:08:10',
 '00:08:11',
 '00:08:12',
 '00:08:13',
 '00:08:14',
 '00:08:15',
 '00:08:16',
 '00:08:17',
 '00:08:18',
 '00:08:19',
 '00:08:20',
 '00:08:21',
 '00:08:22',
 '00:08:23',
 '00:08:24',
 '00:08:25',
 '00:08:26',
 '00:08:27',
 '00:08:28',
 '00:08:29',
 '00:08:30',
 '00:08:31',
 '00:08:32',
 '00:08:33',
 '00:08:34',
 '00:08:35',
 '00:08:36',
 '00:08:37',
 '00:08:38',
 '00:08:39',
 '00:08:40',
 '00:08:41',
 '00:08:42',
 '00:08:43',
 '00:08:44',
 '00:08:45',
 '00:08:46',
 '00:08:47',
 '00:08:48',
 '00:08:49',
 '00:08:50',
 '00:08:51',
 '00:08:52',
 '00:08:53',
 '00:08:54',
 '00:08:55',
 '00:08:56',
 '00:08:57',
 '00:08:58',
 '00:08:59',
 '00:09:00',
 '00:09:01',
 '00:09:02',
 '00:09:03',
 '00:09:04',
 '00:09:05',
 '00:09:06',
 '00:09:07',
 '00:09:08',
 '00:09:09',
 '00:09:10',
 '00:09:11',
 '00:09:12',
 '00:09:13',
 '00:09:14',
 '00:09:15',
 '00:09:16',
 '00:09:17',
 '00:09:18',
 '00:09:19',
 '00:09:20',
 '00:09:21',
 '00:09:22',
 '00:09:23',
 '00:09:24',
 '00:09:25',
 '00:09:26',
 '00:09:27',
 '00:09:28',
 '00:09:29',
 '00:09:30',
 '00:09:31',
 '00:09:32',
 '00:09:33',
 '00:09:34',
 '00:09:35',
 '00:09:36',
 '00:09:37',
 '00:09:38',
 '00:09:39',
 '00:09:40',
 '00:09:41',
 '00:09:42',
 '00:09:43',
 '00:09:44',
 '00:09:45',
 '00:09:46',
 '00:09:47',
 '00:09:48',
 '00:09:49',
 '00:09:50',
 '00:09:51',
 '00:09:52',
 '00:09:53',
 '00:09:54',
 '00:09:55',
 '00:09:56',
 '00:09:57',
 '00:09:58',
 '00:09:59',
 '00:10:00',
 '00:10:01',
 '00:10:02',
 '00:10:03',
 '00:10:04',
 '00:10:05',
 '00:10:06',
 '00:10:07',
 '00:10:08',
 '00:10:09',
 '00:10:10',
 '00:10:11',
 '00:10:12',
 '00:10:13',
 '00:10:14',
 '00:10:15',
 '00:10:16',
 '00:10:17',
 '00:10:18',
 '00:10:19',
 '00:10:20',
 '00:10:21',
 '00:10:22',
 '00:10:23',
 '00:10:24',
 '00:10:25',
 '00:10:26',
 '00:10:27',
 '00:10:28',
 '00:10:29',
 '00:10:30',
 '00:10:31',
 '00:10:32',
 '00:10:33',
 '00:10:34',
 '00:10:35',
 '00:10:36',
 '00:10:37',
 '00:10:38',
 '00:10:39',
 '00:10:40',
 '00:10:41',
 '00:10:42',
 '00:10:43',
 '00:10:44',
 '00:10:45',
 '00:10:46',
 '00:10:47',
 '00:10:48',
 '00:10:49',
 '00:10:50',
 '00:10:51',
 '00:10:52',
 '00:10:53',
 '00:10:54',
 '00:10:55',
 '00:10:56',
 '00:10:57',
 '00:10:58',
 '00:10:59',
 '00:11:00',
 '00:11:01',
 '00:11:02',
 '00:11:03',
 '00:11:04',
 '00:11:05',
 '00:11:06',
 '00:11:07',
 '00:11:08',
 '00:11:09',
 '00:11:10',
 '00:11:11',
 '00:11:12',
 '00:11:13',
 '00:11:14',
 '00:11:15',
 '00:11:16',
 '00:11:17',
 '00:11:18',
 '00:11:19',
 '00:11:20',
 '00:11:21',
 '00:11:22',
 '00:11:23',
 '00:11:24',
 '00:11:25',
 '00:11:26',
 '00:11:27',
 '00:11:28',
 '00:11:29',
 '00:11:30',
 '00:11:31',
 '00:11:32',
 '00:11:33',
 '00:11:34',
 '00:11:35',
 '00:11:36',
 '00:11:37',
 '00:11:38',
 '00:11:39',
 '00:11:40',
 '00:11:41',
 '00:11:42',
 '00:11:43',
 '00:11:44',
 '00:11:45',
 '00:11:46',
 '00:11:47',
 '00:11:48',
 '00:11:49',
 '00:11:50',
 '00:11:51',
 '00:11:52',
 '00:11:53',
 '00:11:54',
 '00:11:55',
 '00:11:56',
 '00:11:57',
 '00:11:58',
 '00:11:59',
 '00:12:00',
 '00:12:01',
 '00:12:02',
 '00:12:03',
 '00:12:04',
 '00:12:05',
 '00:12:06',
 '00:12:07',
 '00:12:08',
 '00:12:09',
 '00:12:10',
 '00:12:11',
 '00:12:12',
 '00:12:13',
 '00:12:14',
 '00:12:15',
 '00:12:16',
 '00:12:17',
 '00:12:18',
 '00:12:19',
 '00:12:20',
 '00:12:21',
 '00:12:22',
 '00:12:23',
 '00:12:24',
 '00:12:25',
 '00:12:26',
 '00:12:27',
 '00:12:28',
 '00:12:29',
 '00:12:30',
 '00:12:31',
 '00:12:32',
 '00:12:33',
 '00:12:34',
 '00:12:35',
 '00:12:36',
 '00:12:37',
 '00:12:38',
 '00:12:39',
 '00:12:40',
 '00:12:41',
 '00:12:42',
 '00:12:43',
 '00:12:44',
 '00:12:45',
 '00:12:46',
 '00:12:47',
 '00:12:48',
 '00:12:49',
 '00:12:50',
 '00:12:51',
 '00:12:52',
 '00:12:53',
 '00:12:54',
 '00:12:55',
 '00:12:56',
 '00:12:57',
 '00:12:58',
 '00:12:59',
 '00:13:00',
 '00:13:01',
 '00:13:02',
 '00:13:03',
 '00:13:04',
 '00:13:05',
 '00:13:06',
 '00:13:07',
 '00:13:08',
 '00:13:09',
 '00:13:10',
 '00:13:11',
 '00:13:12',
 '00:13:13',
 '00:13:14',
 '00:13:15',
 '00:13:16',
 '00:13:17',
 '00:13:18',
 '00:13:19',
 '00:13:20',
 '00:13:21',
 '00:13:22',
 '00:13:23',
 '00:13:24',
 '00:13:25',
 '00:13:26',
 '00:13:27',
 '00:13:28',
 '00:13:29',
 '00:13:30',
 '00:13:31',
 '00:13:32',
 '00:13:33',
 '00:13:34',
 '00:13:35',
 '00:13:36',
 '00:13:37',
 '00:13:38',
 '00:13:39',
 '00:13:40',
 '00:13:41',
 '00:13:42',
 '00:13:43',
 '00:13:44',
 '00:13:45',
 '00:13:46',
 '00:13:47',
 '00:13:48',
 '00:13:49',
 '00:13:50',
 '00:13:51',
 '00:13:52',
 '00:13:53',
 '00:13:54',
 '00:13:55',
 '00:13:56',
 '00:13:57',
 '00:13:58',
 '00:13:59',
 '00:14:00',
 '00:14:01',
 '00:14:02',
 '00:14:03',
 '00:14:04',
 '00:14:05',
 '00:14:06',
 '00:14:07',
 '00:14:08',
 '00:14:09',
 '00:14:10',
 '00:14:11',
 '00:14:12',
 '00:14:13',
 '00:14:14',
 '00:14:15',
 '00:14:16',
 '00:14:17',
 '00:14:18',
 '00:14:19',
 '00:14:20',
 '00:14:21',
 '00:14:22',
 '00:14:23',
 '00:14:24',
 '00:14:25',
 '00:14:26',
 '00:14:27',
 '00:14:28',
 '00:14:29',
 '00:14:30',
 '00:14:31',
 '00:14:32',
 '00:14:33',
 '00:14:34',
 '00:14:35',
 '00:14:36',
 '00:14:37',
 '00:14:38',
 '00:14:39',
 '00:14:40',
 '00:14:41',
 '00:14:42',
 '00:14:43',
 '00:14:44',
 '00:14:45',
 '00:14:46',
 '00:14:47',
 '00:14:48',
 '00:14:49',
 '00:14:50',
 '00:14:51',
 '00:14:52',
 '00:14:53',
 '00:14:54',
 '00:14:55',
 '00:14:56',
 '00:14:57',
 '00:14:58',
 '00:14:59',
 '00:15:00',
 '00:15:01',
 '00:15:02',
 '00:15:03',
 '00:15:04',
 '00:15:05',
 '00:15:06',
 '00:15:07',
 '00:15:08',
 '00:15:09',
 '00:15:10',
 '00:15:11',
 '00:15:12',
 '00:15:13',
 '00:15:14',
 '00:15:15',
 '00:15:16',
 '00:15:17',
 '00:15:18',
 '00:15:19',
 '00:15:20',
 '00:15:21',
 '00:15:22',
 '00:15:23',
 '00:15:24',
 '00:15:25',
 '00:15:26',
 '00:15:27',
 '00:15:28',
 '00:15:29',
 '00:15:30',
 '00:15:31',
 '00:15:32',
 '00:15:33',
 '00:15:34',
 '00:15:35',
 '00:15:36',
 '00:15:37',
 '00:15:38',
 '00:15:39',
 '00:15:40',
 '00:15:41',
 '00:15:42',
 '00:15:43',
 '00:15:44',
 '00:15:45',
 '00:15:46',
 '00:15:47',
 '00:15:48',
 '00:15:49',
 '00:15:50',
 '00:15:51',
 '00:15:52',
 '00:15:53',
 '00:15:54',
 '00:15:55',
 '00:15:56',
 '00:15:57',
 '00:15:58',
 '00:15:59',
 '00:16:00',
 '00:16:01',
 '00:16:02',
 '00:16:03',
 '00:16:04',
 '00:16:05',
 '00:16:06',
 '00:16:07',
 '00:16:08',
 '00:16:09',
 '00:16:10',
 '00:16:11',
 '00:16:12',
 '00:16:13',
 '00:16:14',
 '00:16:15',
 '00:16:16',
 '00:16:17',
 '00:16:18',
 '00:16:19',
 '00:16:20',
 '00:16:21',
 '00:16:22',
 '00:16:23',
 '00:16:24',
 '00:16:25',
 '00:16:26',
 '00:16:27',
 '00:16:28',
 '00:16:29',
 '00:16:30',
 '00:16:31',
 '00:16:32',
 '00:16:33',
 '00:16:34',
 '00:16:35',
 '00:16:36',
 '00:16:37',
 '00:16:38',
 '00:16:39',
 ...]

In [14]:
[f"{i:02d}:{j:02d}:{k:02d}" for i in range(0, 23) for j in range(0, 60) for k in range(0, 60)]

['00:00:00',
 '00:00:01',
 '00:00:02',
 '00:00:03',
 '00:00:04',
 '00:00:05',
 '00:00:06',
 '00:00:07',
 '00:00:08',
 '00:00:09',
 '00:00:10',
 '00:00:11',
 '00:00:12',
 '00:00:13',
 '00:00:14',
 '00:00:15',
 '00:00:16',
 '00:00:17',
 '00:00:18',
 '00:00:19',
 '00:00:20',
 '00:00:21',
 '00:00:22',
 '00:00:23',
 '00:00:24',
 '00:00:25',
 '00:00:26',
 '00:00:27',
 '00:00:28',
 '00:00:29',
 '00:00:30',
 '00:00:31',
 '00:00:32',
 '00:00:33',
 '00:00:34',
 '00:00:35',
 '00:00:36',
 '00:00:37',
 '00:00:38',
 '00:00:39',
 '00:00:40',
 '00:00:41',
 '00:00:42',
 '00:00:43',
 '00:00:44',
 '00:00:45',
 '00:00:46',
 '00:00:47',
 '00:00:48',
 '00:00:49',
 '00:00:50',
 '00:00:51',
 '00:00:52',
 '00:00:53',
 '00:00:54',
 '00:00:55',
 '00:00:56',
 '00:00:57',
 '00:00:58',
 '00:00:59',
 '00:01:00',
 '00:01:01',
 '00:01:02',
 '00:01:03',
 '00:01:04',
 '00:01:05',
 '00:01:06',
 '00:01:07',
 '00:01:08',
 '00:01:09',
 '00:01:10',
 '00:01:11',
 '00:01:12',
 '00:01:13',
 '00:01:14',
 '00:01:15',
 '00:01:16',
 '00:01:17',
 '00:01:18',
 '00:01:19',
 '00:01:20',
 '00:01:21',
 '00:01:22',
 '00:01:23',
 '00:01:24',
 '00:01:25',
 '00:01:26',
 '00:01:27',
 '00:01:28',
 '00:01:29',
 '00:01:30',
 '00:01:31',
 '00:01:32',
 '00:01:33',
 '00:01:34',
 '00:01:35',
 '00:01:36',
 '00:01:37',
 '00:01:38',
 '00:01:39',
 '00:01:40',
 '00:01:41',
 '00:01:42',
 '00:01:43',
 '00:01:44',
 '00:01:45',
 '00:01:46',
 '00:01:47',
 '00:01:48',
 '00:01:49',
 '00:01:50',
 '00:01:51',
 '00:01:52',
 '00:01:53',
 '00:01:54',
 '00:01:55',
 '00:01:56',
 '00:01:57',
 '00:01:58',
 '00:01:59',
 '00:02:00',
 '00:02:01',
 '00:02:02',
 '00:02:03',
 '00:02:04',
 '00:02:05',
 '00:02:06',
 '00:02:07',
 '00:02:08',
 '00:02:09',
 '00:02:10',
 '00:02:11',
 '00:02:12',
 '00:02:13',
 '00:02:14',
 '00:02:15',
 '00:02:16',
 '00:02:17',
 '00:02:18',
 '00:02:19',
 '00:02:20',
 '00:02:21',
 '00:02:22',
 '00:02:23',
 '00:02:24',
 '00:02:25',
 '00:02:26',
 '00:02:27',
 '00:02:28',
 '00:02:29',
 '00:02:30',
 '00:02:31',
 '00:02:32',
 '00:02:33',
 '00:02:34',
 '00:02:35',
 '00:02:36',
 '00:02:37',
 '00:02:38',
 '00:02:39',
 '00:02:40',
 '00:02:41',
 '00:02:42',
 '00:02:43',
 '00:02:44',
 '00:02:45',
 '00:02:46',
 '00:02:47',
 '00:02:48',
 '00:02:49',
 '00:02:50',
 '00:02:51',
 '00:02:52',
 '00:02:53',
 '00:02:54',
 '00:02:55',
 '00:02:56',
 '00:02:57',
 '00:02:58',
 '00:02:59',
 '00:03:00',
 '00:03:01',
 '00:03:02',
 '00:03:03',
 '00:03:04',
 '00:03:05',
 '00:03:06',
 '00:03:07',
 '00:03:08',
 '00:03:09',
 '00:03:10',
 '00:03:11',
 '00:03:12',
 '00:03:13',
 '00:03:14',
 '00:03:15',
 '00:03:16',
 '00:03:17',
 '00:03:18',
 '00:03:19',
 '00:03:20',
 '00:03:21',
 '00:03:22',
 '00:03:23',
 '00:03:24',
 '00:03:25',
 '00:03:26',
 '00:03:27',
 '00:03:28',
 '00:03:29',
 '00:03:30',
 '00:03:31',
 '00:03:32',
 '00:03:33',
 '00:03:34',
 '00:03:35',
 '00:03:36',
 '00:03:37',
 '00:03:38',
 '00:03:39',
 '00:03:40',
 '00:03:41',
 '00:03:42',
 '00:03:43',
 '00:03:44',
 '00:03:45',
 '00:03:46',
 '00:03:47',
 '00:03:48',
 '00:03:49',
 '00:03:50',
 '00:03:51',
 '00:03:52',
 '00:03:53',
 '00:03:54',
 '00:03:55',
 '00:03:56',
 '00:03:57',
 '00:03:58',
 '00:03:59',
 '00:04:00',
 '00:04:01',
 '00:04:02',
 '00:04:03',
 '00:04:04',
 '00:04:05',
 '00:04:06',
 '00:04:07',
 '00:04:08',
 '00:04:09',
 '00:04:10',
 '00:04:11',
 '00:04:12',
 '00:04:13',
 '00:04:14',
 '00:04:15',
 '00:04:16',
 '00:04:17',
 '00:04:18',
 '00:04:19',
 '00:04:20',
 '00:04:21',
 '00:04:22',
 '00:04:23',
 '00:04:24',
 '00:04:25',
 '00:04:26',
 '00:04:27',
 '00:04:28',
 '00:04:29',
 '00:04:30',
 '00:04:31',
 '00:04:32',
 '00:04:33',
 '00:04:34',
 '00:04:35',
 '00:04:36',
 '00:04:37',
 '00:04:38',
 '00:04:39',
 '00:04:40',
 '00:04:41',
 '00:04:42',
 '00:04:43',
 '00:04:44',
 '00:04:45',
 '00:04:46',
 '00:04:47',
 '00:04:48',
 '00:04:49',
 '00:04:50',
 '00:04:51',
 '00:04:52',
 '00:04:53',
 '00:04:54',
 '00:04:55',
 '00:04:56',
 '00:04:57',
 '00:04:58',
 '00:04:59',
 '00:05:00',
 '00:05:01',
 '00:05:02',
 '00:05:03',
 '00:05:04',
 '00:05:05',
 '00:05:06',
 '00:05:07',
 '00:05:08',
 '00:05:09',
 '00:05:10',
 '00:05:11',
 '00:05:12',
 '00:05:13',
 '00:05:14',
 '00:05:15',
 '00:05:16',
 '00:05:17',
 '00:05:18',
 '00:05:19',
 '00:05:20',
 '00:05:21',
 '00:05:22',
 '00:05:23',
 '00:05:24',
 '00:05:25',
 '00:05:26',
 '00:05:27',
 '00:05:28',
 '00:05:29',
 '00:05:30',
 '00:05:31',
 '00:05:32',
 '00:05:33',
 '00:05:34',
 '00:05:35',
 '00:05:36',
 '00:05:37',
 '00:05:38',
 '00:05:39',
 '00:05:40',
 '00:05:41',
 '00:05:42',
 '00:05:43',
 '00:05:44',
 '00:05:45',
 '00:05:46',
 '00:05:47',
 '00:05:48',
 '00:05:49',
 '00:05:50',
 '00:05:51',
 '00:05:52',
 '00:05:53',
 '00:05:54',
 '00:05:55',
 '00:05:56',
 '00:05:57',
 '00:05:58',
 '00:05:59',
 '00:06:00',
 '00:06:01',
 '00:06:02',
 '00:06:03',
 '00:06:04',
 '00:06:05',
 '00:06:06',
 '00:06:07',
 '00:06:08',
 '00:06:09',
 '00:06:10',
 '00:06:11',
 '00:06:12',
 '00:06:13',
 '00:06:14',
 '00:06:15',
 '00:06:16',
 '00:06:17',
 '00:06:18',
 '00:06:19',
 '00:06:20',
 '00:06:21',
 '00:06:22',
 '00:06:23',
 '00:06:24',
 '00:06:25',
 '00:06:26',
 '00:06:27',
 '00:06:28',
 '00:06:29',
 '00:06:30',
 '00:06:31',
 '00:06:32',
 '00:06:33',
 '00:06:34',
 '00:06:35',
 '00:06:36',
 '00:06:37',
 '00:06:38',
 '00:06:39',
 '00:06:40',
 '00:06:41',
 '00:06:42',
 '00:06:43',
 '00:06:44',
 '00:06:45',
 '00:06:46',
 '00:06:47',
 '00:06:48',
 '00:06:49',
 '00:06:50',
 '00:06:51',
 '00:06:52',
 '00:06:53',
 '00:06:54',
 '00:06:55',
 '00:06:56',
 '00:06:57',
 '00:06:58',
 '00:06:59',
 '00:07:00',
 '00:07:01',
 '00:07:02',
 '00:07:03',
 '00:07:04',
 '00:07:05',
 '00:07:06',
 '00:07:07',
 '00:07:08',
 '00:07:09',
 '00:07:10',
 '00:07:11',
 '00:07:12',
 '00:07:13',
 '00:07:14',
 '00:07:15',
 '00:07:16',
 '00:07:17',
 '00:07:18',
 '00:07:19',
 '00:07:20',
 '00:07:21',
 '00:07:22',
 '00:07:23',
 '00:07:24',
 '00:07:25',
 '00:07:26',
 '00:07:27',
 '00:07:28',
 '00:07:29',
 '00:07:30',
 '00:07:31',
 '00:07:32',
 '00:07:33',
 '00:07:34',
 '00:07:35',
 '00:07:36',
 '00:07:37',
 '00:07:38',
 '00:07:39',
 '00:07:40',
 '00:07:41',
 '00:07:42',
 '00:07:43',
 '00:07:44',
 '00:07:45',
 '00:07:46',
 '00:07:47',
 '00:07:48',
 '00:07:49',
 '00:07:50',
 '00:07:51',
 '00:07:52',
 '00:07:53',
 '00:07:54',
 '00:07:55',
 '00:07:56',
 '00:07:57',
 '00:07:58',
 '00:07:59',
 '00:08:00',
 '00:08:01',
 '00:08:02',
 '00:08:03',
 '00:08:04',
 '00:08:05',
 '00:08:06',
 '00:08:07',
 '00:08:08',
 '00:08:09',
 '00:08:10',
 '00:08:11',
 '00:08:12',
 '00:08:13',
 '00:08:14',
 '00:08:15',
 '00:08:16',
 '00:08:17',
 '00:08:18',
 '00:08:19',
 '00:08:20',
 '00:08:21',
 '00:08:22',
 '00:08:23',
 '00:08:24',
 '00:08:25',
 '00:08:26',
 '00:08:27',
 '00:08:28',
 '00:08:29',
 '00:08:30',
 '00:08:31',
 '00:08:32',
 '00:08:33',
 '00:08:34',
 '00:08:35',
 '00:08:36',
 '00:08:37',
 '00:08:38',
 '00:08:39',
 '00:08:40',
 '00:08:41',
 '00:08:42',
 '00:08:43',
 '00:08:44',
 '00:08:45',
 '00:08:46',
 '00:08:47',
 '00:08:48',
 '00:08:49',
 '00:08:50',
 '00:08:51',
 '00:08:52',
 '00:08:53',
 '00:08:54',
 '00:08:55',
 '00:08:56',
 '00:08:57',
 '00:08:58',
 '00:08:59',
 '00:09:00',
 '00:09:01',
 '00:09:02',
 '00:09:03',
 '00:09:04',
 '00:09:05',
 '00:09:06',
 '00:09:07',
 '00:09:08',
 '00:09:09',
 '00:09:10',
 '00:09:11',
 '00:09:12',
 '00:09:13',
 '00:09:14',
 '00:09:15',
 '00:09:16',
 '00:09:17',
 '00:09:18',
 '00:09:19',
 '00:09:20',
 '00:09:21',
 '00:09:22',
 '00:09:23',
 '00:09:24',
 '00:09:25',
 '00:09:26',
 '00:09:27',
 '00:09:28',
 '00:09:29',
 '00:09:30',
 '00:09:31',
 '00:09:32',
 '00:09:33',
 '00:09:34',
 '00:09:35',
 '00:09:36',
 '00:09:37',
 '00:09:38',
 '00:09:39',
 '00:09:40',
 '00:09:41',
 '00:09:42',
 '00:09:43',
 '00:09:44',
 '00:09:45',
 '00:09:46',
 '00:09:47',
 '00:09:48',
 '00:09:49',
 '00:09:50',
 '00:09:51',
 '00:09:52',
 '00:09:53',
 '00:09:54',
 '00:09:55',
 '00:09:56',
 '00:09:57',
 '00:09:58',
 '00:09:59',
 '00:10:00',
 '00:10:01',
 '00:10:02',
 '00:10:03',
 '00:10:04',
 '00:10:05',
 '00:10:06',
 '00:10:07',
 '00:10:08',
 '00:10:09',
 '00:10:10',
 '00:10:11',
 '00:10:12',
 '00:10:13',
 '00:10:14',
 '00:10:15',
 '00:10:16',
 '00:10:17',
 '00:10:18',
 '00:10:19',
 '00:10:20',
 '00:10:21',
 '00:10:22',
 '00:10:23',
 '00:10:24',
 '00:10:25',
 '00:10:26',
 '00:10:27',
 '00:10:28',
 '00:10:29',
 '00:10:30',
 '00:10:31',
 '00:10:32',
 '00:10:33',
 '00:10:34',
 '00:10:35',
 '00:10:36',
 '00:10:37',
 '00:10:38',
 '00:10:39',
 '00:10:40',
 '00:10:41',
 '00:10:42',
 '00:10:43',
 '00:10:44',
 '00:10:45',
 '00:10:46',
 '00:10:47',
 '00:10:48',
 '00:10:49',
 '00:10:50',
 '00:10:51',
 '00:10:52',
 '00:10:53',
 '00:10:54',
 '00:10:55',
 '00:10:56',
 '00:10:57',
 '00:10:58',
 '00:10:59',
 '00:11:00',
 '00:11:01',
 '00:11:02',
 '00:11:03',
 '00:11:04',
 '00:11:05',
 '00:11:06',
 '00:11:07',
 '00:11:08',
 '00:11:09',
 '00:11:10',
 '00:11:11',
 '00:11:12',
 '00:11:13',
 '00:11:14',
 '00:11:15',
 '00:11:16',
 '00:11:17',
 '00:11:18',
 '00:11:19',
 '00:11:20',
 '00:11:21',
 '00:11:22',
 '00:11:23',
 '00:11:24',
 '00:11:25',
 '00:11:26',
 '00:11:27',
 '00:11:28',
 '00:11:29',
 '00:11:30',
 '00:11:31',
 '00:11:32',
 '00:11:33',
 '00:11:34',
 '00:11:35',
 '00:11:36',
 '00:11:37',
 '00:11:38',
 '00:11:39',
 '00:11:40',
 '00:11:41',
 '00:11:42',
 '00:11:43',
 '00:11:44',
 '00:11:45',
 '00:11:46',
 '00:11:47',
 '00:11:48',
 '00:11:49',
 '00:11:50',
 '00:11:51',
 '00:11:52',
 '00:11:53',
 '00:11:54',
 '00:11:55',
 '00:11:56',
 '00:11:57',
 '00:11:58',
 '00:11:59',
 '00:12:00',
 '00:12:01',
 '00:12:02',
 '00:12:03',
 '00:12:04',
 '00:12:05',
 '00:12:06',
 '00:12:07',
 '00:12:08',
 '00:12:09',
 '00:12:10',
 '00:12:11',
 '00:12:12',
 '00:12:13',
 '00:12:14',
 '00:12:15',
 '00:12:16',
 '00:12:17',
 '00:12:18',
 '00:12:19',
 '00:12:20',
 '00:12:21',
 '00:12:22',
 '00:12:23',
 '00:12:24',
 '00:12:25',
 '00:12:26',
 '00:12:27',
 '00:12:28',
 '00:12:29',
 '00:12:30',
 '00:12:31',
 '00:12:32',
 '00:12:33',
 '00:12:34',
 '00:12:35',
 '00:12:36',
 '00:12:37',
 '00:12:38',
 '00:12:39',
 '00:12:40',
 '00:12:41',
 '00:12:42',
 '00:12:43',
 '00:12:44',
 '00:12:45',
 '00:12:46',
 '00:12:47',
 '00:12:48',
 '00:12:49',
 '00:12:50',
 '00:12:51',
 '00:12:52',
 '00:12:53',
 '00:12:54',
 '00:12:55',
 '00:12:56',
 '00:12:57',
 '00:12:58',
 '00:12:59',
 '00:13:00',
 '00:13:01',
 '00:13:02',
 '00:13:03',
 '00:13:04',
 '00:13:05',
 '00:13:06',
 '00:13:07',
 '00:13:08',
 '00:13:09',
 '00:13:10',
 '00:13:11',
 '00:13:12',
 '00:13:13',
 '00:13:14',
 '00:13:15',
 '00:13:16',
 '00:13:17',
 '00:13:18',
 '00:13:19',
 '00:13:20',
 '00:13:21',
 '00:13:22',
 '00:13:23',
 '00:13:24',
 '00:13:25',
 '00:13:26',
 '00:13:27',
 '00:13:28',
 '00:13:29',
 '00:13:30',
 '00:13:31',
 '00:13:32',
 '00:13:33',
 '00:13:34',
 '00:13:35',
 '00:13:36',
 '00:13:37',
 '00:13:38',
 '00:13:39',
 '00:13:40',
 '00:13:41',
 '00:13:42',
 '00:13:43',
 '00:13:44',
 '00:13:45',
 '00:13:46',
 '00:13:47',
 '00:13:48',
 '00:13:49',
 '00:13:50',
 '00:13:51',
 '00:13:52',
 '00:13:53',
 '00:13:54',
 '00:13:55',
 '00:13:56',
 '00:13:57',
 '00:13:58',
 '00:13:59',
 '00:14:00',
 '00:14:01',
 '00:14:02',
 '00:14:03',
 '00:14:04',
 '00:14:05',
 '00:14:06',
 '00:14:07',
 '00:14:08',
 '00:14:09',
 '00:14:10',
 '00:14:11',
 '00:14:12',
 '00:14:13',
 '00:14:14',
 '00:14:15',
 '00:14:16',
 '00:14:17',
 '00:14:18',
 '00:14:19',
 '00:14:20',
 '00:14:21',
 '00:14:22',
 '00:14:23',
 '00:14:24',
 '00:14:25',
 '00:14:26',
 '00:14:27',
 '00:14:28',
 '00:14:29',
 '00:14:30',
 '00:14:31',
 '00:14:32',
 '00:14:33',
 '00:14:34',
 '00:14:35',
 '00:14:36',
 '00:14:37',
 '00:14:38',
 '00:14:39',
 '00:14:40',
 '00:14:41',
 '00:14:42',
 '00:14:43',
 '00:14:44',
 '00:14:45',
 '00:14:46',
 '00:14:47',
 '00:14:48',
 '00:14:49',
 '00:14:50',
 '00:14:51',
 '00:14:52',
 '00:14:53',
 '00:14:54',
 '00:14:55',
 '00:14:56',
 '00:14:57',
 '00:14:58',
 '00:14:59',
 '00:15:00',
 '00:15:01',
 '00:15:02',
 '00:15:03',
 '00:15:04',
 '00:15:05',
 '00:15:06',
 '00:15:07',
 '00:15:08',
 '00:15:09',
 '00:15:10',
 '00:15:11',
 '00:15:12',
 '00:15:13',
 '00:15:14',
 '00:15:15',
 '00:15:16',
 '00:15:17',
 '00:15:18',
 '00:15:19',
 '00:15:20',
 '00:15:21',
 '00:15:22',
 '00:15:23',
 '00:15:24',
 '00:15:25',
 '00:15:26',
 '00:15:27',
 '00:15:28',
 '00:15:29',
 '00:15:30',
 '00:15:31',
 '00:15:32',
 '00:15:33',
 '00:15:34',
 '00:15:35',
 '00:15:36',
 '00:15:37',
 '00:15:38',
 '00:15:39',
 '00:15:40',
 '00:15:41',
 '00:15:42',
 '00:15:43',
 '00:15:44',
 '00:15:45',
 '00:15:46',
 '00:15:47',
 '00:15:48',
 '00:15:49',
 '00:15:50',
 '00:15:51',
 '00:15:52',
 '00:15:53',
 '00:15:54',
 '00:15:55',
 '00:15:56',
 '00:15:57',
 '00:15:58',
 '00:15:59',
 '00:16:00',
 '00:16:01',
 '00:16:02',
 '00:16:03',
 '00:16:04',
 '00:16:05',
 '00:16:06',
 '00:16:07',
 '00:16:08',
 '00:16:09',
 '00:16:10',
 '00:16:11',
 '00:16:12',
 '00:16:13',
 '00:16:14',
 '00:16:15',
 '00:16:16',
 '00:16:17',
 '00:16:18',
 '00:16:19',
 '00:16:20',
 '00:16:21',
 '00:16:22',
 '00:16:23',
 '00:16:24',
 '00:16:25',
 '00:16:26',
 '00:16:27',
 '00:16:28',
 '00:16:29',
 '00:16:30',
 '00:16:31',
 '00:16:32',
 '00:16:33',
 '00:16:34',
 '00:16:35',
 '00:16:36',
 '00:16:37',
 '00:16:38',
 '00:16:39',
 ...]

In [15]:
[f"{i:02d}:{j:02d}:{k:02d}" for i in range(0, 23) for j in range(0, 60) for k in range(0, 60)]

['00:00:00',
 '00:00:01',
 '00:00:02',
 '00:00:03',
 '00:00:04',
 '00:00:05',
 '00:00:06',
 '00:00:07',
 '00:00:08',
 '00:00:09',
 '00:00:10',
 '00:00:11',
 '00:00:12',
 '00:00:13',
 '00:00:14',
 '00:00:15',
 '00:00:16',
 '00:00:17',
 '00:00:18',
 '00:00:19',
 '00:00:20',
 '00:00:21',
 '00:00:22',
 '00:00:23',
 '00:00:24',
 '00:00:25',
 '00:00:26',
 '00:00:27',
 '00:00:28',
 '00:00:29',
 '00:00:30',
 '00:00:31',
 '00:00:32',
 '00:00:33',
 '00:00:34',
 '00:00:35',
 '00:00:36',
 '00:00:37',
 '00:00:38',
 '00:00:39',
 '00:00:40',
 '00:00:41',
 '00:00:42',
 '00:00:43',
 '00:00:44',
 '00:00:45',
 '00:00:46',
 '00:00:47',
 '00:00:48',
 '00:00:49',
 '00:00:50',
 '00:00:51',
 '00:00:52',
 '00:00:53',
 '00:00:54',
 '00:00:55',
 '00:00:56',
 '00:00:57',
 '00:00:58',
 '00:00:59',
 '00:01:00',
 '00:01:01',
 '00:01:02',
 '00:01:03',
 '00:01:04',
 '00:01:05',
 '00:01:06',
 '00:01:07',
 '00:01:08',
 '00:01:09',
 '00:01:10',
 '00:01:11',
 '00:01:12',
 '00:01:13',
 '00:01:14',
 '00:01:15',
 '00:01:16',
 '00:01:17',
 '00:01:18',
 '00:01:19',
 '00:01:20',
 '00:01:21',
 '00:01:22',
 '00:01:23',
 '00:01:24',
 '00:01:25',
 '00:01:26',
 '00:01:27',
 '00:01:28',
 '00:01:29',
 '00:01:30',
 '00:01:31',
 '00:01:32',
 '00:01:33',
 '00:01:34',
 '00:01:35',
 '00:01:36',
 '00:01:37',
 '00:01:38',
 '00:01:39',
 '00:01:40',
 '00:01:41',
 '00:01:42',
 '00:01:43',
 '00:01:44',
 '00:01:45',
 '00:01:46',
 '00:01:47',
 '00:01:48',
 '00:01:49',
 '00:01:50',
 '00:01:51',
 '00:01:52',
 '00:01:53',
 '00:01:54',
 '00:01:55',
 '00:01:56',
 '00:01:57',
 '00:01:58',
 '00:01:59',
 '00:02:00',
 '00:02:01',
 '00:02:02',
 '00:02:03',
 '00:02:04',
 '00:02:05',
 '00:02:06',
 '00:02:07',
 '00:02:08',
 '00:02:09',
 '00:02:10',
 '00:02:11',
 '00:02:12',
 '00:02:13',
 '00:02:14',
 '00:02:15',
 '00:02:16',
 '00:02:17',
 '00:02:18',
 '00:02:19',
 '00:02:20',
 '00:02:21',
 '00:02:22',
 '00:02:23',
 '00:02:24',
 '00:02:25',
 '00:02:26',
 '00:02:27',
 '00:02:28',
 '00:02:29',
 '00:02:30',
 '00:02:31',
 '00:02:32',
 '00:02:33',
 '00:02:34',
 '00:02:35',
 '00:02:36',
 '00:02:37',
 '00:02:38',
 '00:02:39',
 '00:02:40',
 '00:02:41',
 '00:02:42',
 '00:02:43',
 '00:02:44',
 '00:02:45',
 '00:02:46',
 '00:02:47',
 '00:02:48',
 '00:02:49',
 '00:02:50',
 '00:02:51',
 '00:02:52',
 '00:02:53',
 '00:02:54',
 '00:02:55',
 '00:02:56',
 '00:02:57',
 '00:02:58',
 '00:02:59',
 '00:03:00',
 '00:03:01',
 '00:03:02',
 '00:03:03',
 '00:03:04',
 '00:03:05',
 '00:03:06',
 '00:03:07',
 '00:03:08',
 '00:03:09',
 '00:03:10',
 '00:03:11',
 '00:03:12',
 '00:03:13',
 '00:03:14',
 '00:03:15',
 '00:03:16',
 '00:03:17',
 '00:03:18',
 '00:03:19',
 '00:03:20',
 '00:03:21',
 '00:03:22',
 '00:03:23',
 '00:03:24',
 '00:03:25',
 '00:03:26',
 '00:03:27',
 '00:03:28',
 '00:03:29',
 '00:03:30',
 '00:03:31',
 '00:03:32',
 '00:03:33',
 '00:03:34',
 '00:03:35',
 '00:03:36',
 '00:03:37',
 '00:03:38',
 '00:03:39',
 '00:03:40',
 '00:03:41',
 '00:03:42',
 '00:03:43',
 '00:03:44',
 '00:03:45',
 '00:03:46',
 '00:03:47',
 '00:03:48',
 '00:03:49',
 '00:03:50',
 '00:03:51',
 '00:03:52',
 '00:03:53',
 '00:03:54',
 '00:03:55',
 '00:03:56',
 '00:03:57',
 '00:03:58',
 '00:03:59',
 '00:04:00',
 '00:04:01',
 '00:04:02',
 '00:04:03',
 '00:04:04',
 '00:04:05',
 '00:04:06',
 '00:04:07',
 '00:04:08',
 '00:04:09',
 '00:04:10',
 '00:04:11',
 '00:04:12',
 '00:04:13',
 '00:04:14',
 '00:04:15',
 '00:04:16',
 '00:04:17',
 '00:04:18',
 '00:04:19',
 '00:04:20',
 '00:04:21',
 '00:04:22',
 '00:04:23',
 '00:04:24',
 '00:04:25',
 '00:04:26',
 '00:04:27',
 '00:04:28',
 '00:04:29',
 '00:04:30',
 '00:04:31',
 '00:04:32',
 '00:04:33',
 '00:04:34',
 '00:04:35',
 '00:04:36',
 '00:04:37',
 '00:04:38',
 '00:04:39',
 '00:04:40',
 '00:04:41',
 '00:04:42',
 '00:04:43',
 '00:04:44',
 '00:04:45',
 '00:04:46',
 '00:04:47',
 '00:04:48',
 '00:04:49',
 '00:04:50',
 '00:04:51',
 '00:04:52',
 '00:04:53',
 '00:04:54',
 '00:04:55',
 '00:04:56',
 '00:04:57',
 '00:04:58',
 '00:04:59',
 '00:05:00',
 '00:05:01',
 '00:05:02',
 '00:05:03',
 '00:05:04',
 '00:05:05',
 '00:05:06',
 '00:05:07',
 '00:05:08',
 '00:05:09',
 '00:05:10',
 '00:05:11',
 '00:05:12',
 '00:05:13',
 '00:05:14',
 '00:05:15',
 '00:05:16',
 '00:05:17',
 '00:05:18',
 '00:05:19',
 '00:05:20',
 '00:05:21',
 '00:05:22',
 '00:05:23',
 '00:05:24',
 '00:05:25',
 '00:05:26',
 '00:05:27',
 '00:05:28',
 '00:05:29',
 '00:05:30',
 '00:05:31',
 '00:05:32',
 '00:05:33',
 '00:05:34',
 '00:05:35',
 '00:05:36',
 '00:05:37',
 '00:05:38',
 '00:05:39',
 '00:05:40',
 '00:05:41',
 '00:05:42',
 '00:05:43',
 '00:05:44',
 '00:05:45',
 '00:05:46',
 '00:05:47',
 '00:05:48',
 '00:05:49',
 '00:05:50',
 '00:05:51',
 '00:05:52',
 '00:05:53',
 '00:05:54',
 '00:05:55',
 '00:05:56',
 '00:05:57',
 '00:05:58',
 '00:05:59',
 '00:06:00',
 '00:06:01',
 '00:06:02',
 '00:06:03',
 '00:06:04',
 '00:06:05',
 '00:06:06',
 '00:06:07',
 '00:06:08',
 '00:06:09',
 '00:06:10',
 '00:06:11',
 '00:06:12',
 '00:06:13',
 '00:06:14',
 '00:06:15',
 '00:06:16',
 '00:06:17',
 '00:06:18',
 '00:06:19',
 '00:06:20',
 '00:06:21',
 '00:06:22',
 '00:06:23',
 '00:06:24',
 '00:06:25',
 '00:06:26',
 '00:06:27',
 '00:06:28',
 '00:06:29',
 '00:06:30',
 '00:06:31',
 '00:06:32',
 '00:06:33',
 '00:06:34',
 '00:06:35',
 '00:06:36',
 '00:06:37',
 '00:06:38',
 '00:06:39',
 '00:06:40',
 '00:06:41',
 '00:06:42',
 '00:06:43',
 '00:06:44',
 '00:06:45',
 '00:06:46',
 '00:06:47',
 '00:06:48',
 '00:06:49',
 '00:06:50',
 '00:06:51',
 '00:06:52',
 '00:06:53',
 '00:06:54',
 '00:06:55',
 '00:06:56',
 '00:06:57',
 '00:06:58',
 '00:06:59',
 '00:07:00',
 '00:07:01',
 '00:07:02',
 '00:07:03',
 '00:07:04',
 '00:07:05',
 '00:07:06',
 '00:07:07',
 '00:07:08',
 '00:07:09',
 '00:07:10',
 '00:07:11',
 '00:07:12',
 '00:07:13',
 '00:07:14',
 '00:07:15',
 '00:07:16',
 '00:07:17',
 '00:07:18',
 '00:07:19',
 '00:07:20',
 '00:07:21',
 '00:07:22',
 '00:07:23',
 '00:07:24',
 '00:07:25',
 '00:07:26',
 '00:07:27',
 '00:07:28',
 '00:07:29',
 '00:07:30',
 '00:07:31',
 '00:07:32',
 '00:07:33',
 '00:07:34',
 '00:07:35',
 '00:07:36',
 '00:07:37',
 '00:07:38',
 '00:07:39',
 '00:07:40',
 '00:07:41',
 '00:07:42',
 '00:07:43',
 '00:07:44',
 '00:07:45',
 '00:07:46',
 '00:07:47',
 '00:07:48',
 '00:07:49',
 '00:07:50',
 '00:07:51',
 '00:07:52',
 '00:07:53',
 '00:07:54',
 '00:07:55',
 '00:07:56',
 '00:07:57',
 '00:07:58',
 '00:07:59',
 '00:08:00',
 '00:08:01',
 '00:08:02',
 '00:08:03',
 '00:08:04',
 '00:08:05',
 '00:08:06',
 '00:08:07',
 '00:08:08',
 '00:08:09',
 '00:08:10',
 '00:08:11',
 '00:08:12',
 '00:08:13',
 '00:08:14',
 '00:08:15',
 '00:08:16',
 '00:08:17',
 '00:08:18',
 '00:08:19',
 '00:08:20',
 '00:08:21',
 '00:08:22',
 '00:08:23',
 '00:08:24',
 '00:08:25',
 '00:08:26',
 '00:08:27',
 '00:08:28',
 '00:08:29',
 '00:08:30',
 '00:08:31',
 '00:08:32',
 '00:08:33',
 '00:08:34',
 '00:08:35',
 '00:08:36',
 '00:08:37',
 '00:08:38',
 '00:08:39',
 '00:08:40',
 '00:08:41',
 '00:08:42',
 '00:08:43',
 '00:08:44',
 '00:08:45',
 '00:08:46',
 '00:08:47',
 '00:08:48',
 '00:08:49',
 '00:08:50',
 '00:08:51',
 '00:08:52',
 '00:08:53',
 '00:08:54',
 '00:08:55',
 '00:08:56',
 '00:08:57',
 '00:08:58',
 '00:08:59',
 '00:09:00',
 '00:09:01',
 '00:09:02',
 '00:09:03',
 '00:09:04',
 '00:09:05',
 '00:09:06',
 '00:09:07',
 '00:09:08',
 '00:09:09',
 '00:09:10',
 '00:09:11',
 '00:09:12',
 '00:09:13',
 '00:09:14',
 '00:09:15',
 '00:09:16',
 '00:09:17',
 '00:09:18',
 '00:09:19',
 '00:09:20',
 '00:09:21',
 '00:09:22',
 '00:09:23',
 '00:09:24',
 '00:09:25',
 '00:09:26',
 '00:09:27',
 '00:09:28',
 '00:09:29',
 '00:09:30',
 '00:09:31',
 '00:09:32',
 '00:09:33',
 '00:09:34',
 '00:09:35',
 '00:09:36',
 '00:09:37',
 '00:09:38',
 '00:09:39',
 '00:09:40',
 '00:09:41',
 '00:09:42',
 '00:09:43',
 '00:09:44',
 '00:09:45',
 '00:09:46',
 '00:09:47',
 '00:09:48',
 '00:09:49',
 '00:09:50',
 '00:09:51',
 '00:09:52',
 '00:09:53',
 '00:09:54',
 '00:09:55',
 '00:09:56',
 '00:09:57',
 '00:09:58',
 '00:09:59',
 '00:10:00',
 '00:10:01',
 '00:10:02',
 '00:10:03',
 '00:10:04',
 '00:10:05',
 '00:10:06',
 '00:10:07',
 '00:10:08',
 '00:10:09',
 '00:10:10',
 '00:10:11',
 '00:10:12',
 '00:10:13',
 '00:10:14',
 '00:10:15',
 '00:10:16',
 '00:10:17',
 '00:10:18',
 '00:10:19',
 '00:10:20',
 '00:10:21',
 '00:10:22',
 '00:10:23',
 '00:10:24',
 '00:10:25',
 '00:10:26',
 '00:10:27',
 '00:10:28',
 '00:10:29',
 '00:10:30',
 '00:10:31',
 '00:10:32',
 '00:10:33',
 '00:10:34',
 '00:10:35',
 '00:10:36',
 '00:10:37',
 '00:10:38',
 '00:10:39',
 '00:10:40',
 '00:10:41',
 '00:10:42',
 '00:10:43',
 '00:10:44',
 '00:10:45',
 '00:10:46',
 '00:10:47',
 '00:10:48',
 '00:10:49',
 '00:10:50',
 '00:10:51',
 '00:10:52',
 '00:10:53',
 '00:10:54',
 '00:10:55',
 '00:10:56',
 '00:10:57',
 '00:10:58',
 '00:10:59',
 '00:11:00',
 '00:11:01',
 '00:11:02',
 '00:11:03',
 '00:11:04',
 '00:11:05',
 '00:11:06',
 '00:11:07',
 '00:11:08',
 '00:11:09',
 '00:11:10',
 '00:11:11',
 '00:11:12',
 '00:11:13',
 '00:11:14',
 '00:11:15',
 '00:11:16',
 '00:11:17',
 '00:11:18',
 '00:11:19',
 '00:11:20',
 '00:11:21',
 '00:11:22',
 '00:11:23',
 '00:11:24',
 '00:11:25',
 '00:11:26',
 '00:11:27',
 '00:11:28',
 '00:11:29',
 '00:11:30',
 '00:11:31',
 '00:11:32',
 '00:11:33',
 '00:11:34',
 '00:11:35',
 '00:11:36',
 '00:11:37',
 '00:11:38',
 '00:11:39',
 '00:11:40',
 '00:11:41',
 '00:11:42',
 '00:11:43',
 '00:11:44',
 '00:11:45',
 '00:11:46',
 '00:11:47',
 '00:11:48',
 '00:11:49',
 '00:11:50',
 '00:11:51',
 '00:11:52',
 '00:11:53',
 '00:11:54',
 '00:11:55',
 '00:11:56',
 '00:11:57',
 '00:11:58',
 '00:11:59',
 '00:12:00',
 '00:12:01',
 '00:12:02',
 '00:12:03',
 '00:12:04',
 '00:12:05',
 '00:12:06',
 '00:12:07',
 '00:12:08',
 '00:12:09',
 '00:12:10',
 '00:12:11',
 '00:12:12',
 '00:12:13',
 '00:12:14',
 '00:12:15',
 '00:12:16',
 '00:12:17',
 '00:12:18',
 '00:12:19',
 '00:12:20',
 '00:12:21',
 '00:12:22',
 '00:12:23',
 '00:12:24',
 '00:12:25',
 '00:12:26',
 '00:12:27',
 '00:12:28',
 '00:12:29',
 '00:12:30',
 '00:12:31',
 '00:12:32',
 '00:12:33',
 '00:12:34',
 '00:12:35',
 '00:12:36',
 '00:12:37',
 '00:12:38',
 '00:12:39',
 '00:12:40',
 '00:12:41',
 '00:12:42',
 '00:12:43',
 '00:12:44',
 '00:12:45',
 '00:12:46',
 '00:12:47',
 '00:12:48',
 '00:12:49',
 '00:12:50',
 '00:12:51',
 '00:12:52',
 '00:12:53',
 '00:12:54',
 '00:12:55',
 '00:12:56',
 '00:12:57',
 '00:12:58',
 '00:12:59',
 '00:13:00',
 '00:13:01',
 '00:13:02',
 '00:13:03',
 '00:13:04',
 '00:13:05',
 '00:13:06',
 '00:13:07',
 '00:13:08',
 '00:13:09',
 '00:13:10',
 '00:13:11',
 '00:13:12',
 '00:13:13',
 '00:13:14',
 '00:13:15',
 '00:13:16',
 '00:13:17',
 '00:13:18',
 '00:13:19',
 '00:13:20',
 '00:13:21',
 '00:13:22',
 '00:13:23',
 '00:13:24',
 '00:13:25',
 '00:13:26',
 '00:13:27',
 '00:13:28',
 '00:13:29',
 '00:13:30',
 '00:13:31',
 '00:13:32',
 '00:13:33',
 '00:13:34',
 '00:13:35',
 '00:13:36',
 '00:13:37',
 '00:13:38',
 '00:13:39',
 '00:13:40',
 '00:13:41',
 '00:13:42',
 '00:13:43',
 '00:13:44',
 '00:13:45',
 '00:13:46',
 '00:13:47',
 '00:13:48',
 '00:13:49',
 '00:13:50',
 '00:13:51',
 '00:13:52',
 '00:13:53',
 '00:13:54',
 '00:13:55',
 '00:13:56',
 '00:13:57',
 '00:13:58',
 '00:13:59',
 '00:14:00',
 '00:14:01',
 '00:14:02',
 '00:14:03',
 '00:14:04',
 '00:14:05',
 '00:14:06',
 '00:14:07',
 '00:14:08',
 '00:14:09',
 '00:14:10',
 '00:14:11',
 '00:14:12',
 '00:14:13',
 '00:14:14',
 '00:14:15',
 '00:14:16',
 '00:14:17',
 '00:14:18',
 '00:14:19',
 '00:14:20',
 '00:14:21',
 '00:14:22',
 '00:14:23',
 '00:14:24',
 '00:14:25',
 '00:14:26',
 '00:14:27',
 '00:14:28',
 '00:14:29',
 '00:14:30',
 '00:14:31',
 '00:14:32',
 '00:14:33',
 '00:14:34',
 '00:14:35',
 '00:14:36',
 '00:14:37',
 '00:14:38',
 '00:14:39',
 '00:14:40',
 '00:14:41',
 '00:14:42',
 '00:14:43',
 '00:14:44',
 '00:14:45',
 '00:14:46',
 '00:14:47',
 '00:14:48',
 '00:14:49',
 '00:14:50',
 '00:14:51',
 '00:14:52',
 '00:14:53',
 '00:14:54',
 '00:14:55',
 '00:14:56',
 '00:14:57',
 '00:14:58',
 '00:14:59',
 '00:15:00',
 '00:15:01',
 '00:15:02',
 '00:15:03',
 '00:15:04',
 '00:15:05',
 '00:15:06',
 '00:15:07',
 '00:15:08',
 '00:15:09',
 '00:15:10',
 '00:15:11',
 '00:15:12',
 '00:15:13',
 '00:15:14',
 '00:15:15',
 '00:15:16',
 '00:15:17',
 '00:15:18',
 '00:15:19',
 '00:15:20',
 '00:15:21',
 '00:15:22',
 '00:15:23',
 '00:15:24',
 '00:15:25',
 '00:15:26',
 '00:15:27',
 '00:15:28',
 '00:15:29',
 '00:15:30',
 '00:15:31',
 '00:15:32',
 '00:15:33',
 '00:15:34',
 '00:15:35',
 '00:15:36',
 '00:15:37',
 '00:15:38',
 '00:15:39',
 '00:15:40',
 '00:15:41',
 '00:15:42',
 '00:15:43',
 '00:15:44',
 '00:15:45',
 '00:15:46',
 '00:15:47',
 '00:15:48',
 '00:15:49',
 '00:15:50',
 '00:15:51',
 '00:15:52',
 '00:15:53',
 '00:15:54',
 '00:15:55',
 '00:15:56',
 '00:15:57',
 '00:15:58',
 '00:15:59',
 '00:16:00',
 '00:16:01',
 '00:16:02',
 '00:16:03',
 '00:16:04',
 '00:16:05',
 '00:16:06',
 '00:16:07',
 '00:16:08',
 '00:16:09',
 '00:16:10',
 '00:16:11',
 '00:16:12',
 '00:16:13',
 '00:16:14',
 '00:16:15',
 '00:16:16',
 '00:16:17',
 '00:16:18',
 '00:16:19',
 '00:16:20',
 '00:16:21',
 '00:16:22',
 '00:16:23',
 '00:16:24',
 '00:16:25',
 '00:16:26',
 '00:16:27',
 '00:16:28',
 '00:16:29',
 '00:16:30',
 '00:16:31',
 '00:16:32',
 '00:16:33',
 '00:16:34',
 '00:16:35',
 '00:16:36',
 '00:16:37',
 '00:16:38',
 '00:16:39',
 ...]

# 파일 읽기 쓰기 open(), with open()
## 1) 파일에 문자열을 쓰거나 읽을때는 open 함수 사용
* 파일저장
변수명 = open("파일이름", 모드(w:쓰기, r:읽기, a:추가)<br>
변수명.write("저장할 내용")<br>
변수명.close()<br> 
**close()를 안하면 계속 열려있음**

In [49]:
file = open("test.txt", "w") 
file.write("\n파일 만들기 연습4")
file.close()

* 파일열기
변수1 = open("파일이름", 파일모드(r))<br>
변수2 = 변수1.read()<br>
변수1.close()<br>

In [50]:
file1 = open("test.txt", "r")
my_file = file1.read()
file1.close()
print(my_file)

파일 만들기 연습파일 만들기 연습2
파일 만들기 연습3
파일 만들기 연습3
파일 만들기 연습4
파일 만들기 연습4
파일 만들기 연습4

In [33]:
my_file

'파일 만들기 연습파일 만들기 연습2\n파일 만들기 연습3'

## with open
* with open은 close()를 하지 않아도 자동으로 close()처리를 해줌

In [51]:
with open("test2.txt", 'a') as file3:
    file3.write("\nwith open을 사용하면 파일을 자동으로 닫아주어 편리하다.")

In [54]:
with open("test2.txt", 'r') as file4:
#     data = file4.readlines()
    data = file4.read()
print(data)

with open을 사용하면 파일을 자동으로 닫아주어 편리하다.
with open을 사용하면 파일을 자동으로 닫아주어 편리하다.

# encoding에 따른 읽기 오류
* 운영체제나(windows, linux, macOS), 한글/영어 윈도우에 따라서 인코딩 되는 포멧이 달라짐
* 인코딩에 따른 오류가 발생 가능
* web표준은 utf-8이므로 인코딩은 utf-8로 하는 것이 좋다.
* windows의 경우 인코딩이 cp949이므로 주의

In [20]:
with open("test_utf-8.txt", 'w', encoding='utf-8') as file5:
    file5.write("이것은 with open으로 만들 utf-8 인코딩 파일입니다.")

In [21]:
with open("test_utf-8.txt", 'r') as file6:
    file6_data = file6.read()
print(file6_data)

UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 0: illegal multibyte sequence

In [ ]:
with open("test_utf-8.txt", 'r', encoding="utf-8") as file6:
    file6_data = file6.read()
print(file6_data)

# json 파일 읽어와서 내용 정리하기

In [3]:
with open("./data/서울특별시_관광지입장정보_2011_2016.json", 'r', encoding="utf-8") as file7:
    trip_info = file7.read()
trip_info

'[\n    {\n        "ForNum": 44722,\n        "NatNum": 75991,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 11017,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "운현궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 132399,\n        "NatNum": 237330,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 3133,\n        "NatNum": 21267,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 18226,\n        "NatNum": 24223,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 233828,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 93554,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "서울역사박물관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 13935,\n        "NatNum": 52140,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 61115,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "서울시립미술관 본관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 10,\n        "NatNum": 1885,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 32412,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 19308,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 5214,\n        "NatNum": 6956,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 13,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 333,\n        "NatNum": 1823,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 14,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 4704,\n        "NatNum": 16634,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 15,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 52484,\n        "NatNum": 642290,\n        "addrCd": 1171,\n        "gungu": "송파구",\n        "resNm": "롯데월드",\n        "rnum": 16,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 27814,\n        "NatNum": 28061,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 546,\n        "NatNum": 5978,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "운현궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 105370,\n        "NatNum": 133012,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 1451,\n        "NatNum": 15722,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 8817,\n        "NatNum": 8068,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 13033,\n        "NatNum": 227077,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 1138,\n        "NatNum": 78179,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "서울역사박물관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 11151,\n        "NatNum": 44855,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 213467,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "서울시립미술관 본관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 15,\n        "NatNum": 1252,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 6625,\n        "NatNum": 14090,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 18881,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 24492,\n        "NatNum": 9167,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 13,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 62,\n        "NatNum": 860,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 14,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 66868,\n        "NatNum": 670056,\n        "addrCd": 1171,\n        "gungu": "송파구",\n        "resNm": "롯데월드",\n        "rnum": 15,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 25550,\n        "NatNum": 38553,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 101942,\n        "NatNum": 145544,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 1986,\n        "NatNum": 20035,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 6048,\n        "NatNum": 13896,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 9083,\n        "NatNum": 286992,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 13282,\n        "NatNum": 99301,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 6,\n        "NatNum": 706,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 6732,\n        "NatNum": 14607,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 23245,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 43129,\n        "NatNum": 11886,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 16,\n        "NatNum": 1248,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 1445,\n        "NatNum": 11890,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 29928,\n        "NatNum": 41561,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 129946,\n        "NatNum": 190501,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 1693,\n        "NatNum": 19473,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 3891,\n        "NatNum": 5951,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 7195,\n        "NatNum": 258781,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 14723,\n        "NatNum": 44272,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 12,\n        "NatNum": 486,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 6263,\n        "NatNum": 27205,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 24527,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 42443,\n        "NatNum": 7478,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 5,\n        "NatNum": 1036,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 823,\n        "NatNum": 8869,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 33342,\n        "NatNum": 59738,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 170379,\n        "NatNum": 148961,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 1783,\n        "NatNum": 27172,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 3406,\n        "NatNum": 14936,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 13127,\n        "NatNum": 281457,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 15197,\n        "NatNum": 68749,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 16,\n        "NatNum": 2221,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 5588,\n        "NatNum": 44232,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 22587,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 29520,\n        "NatNum": 8822,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 3,\n        "NatNum": 1647,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 492,\n        "NatNum": 14454,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    }\n]'

In [4]:
print(trip_info)

[
    {
        "ForNum": 44722,
        "NatNum": 75991,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창덕궁",
        "rnum": 1,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 0,
        "NatNum": 11017,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "운현궁",
        "rnum": 2,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 132399,
        "NatNum": 237330,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "경복궁",
        "rnum": 3,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 3133,
        "NatNum": 21267,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창경궁",
        "rnum": 4,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 18226,
        "NatNum": 24223,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "종묘",
        "rnum": 5,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 0,
        "NatNum": 233828,
        "addrCd": 1117,
        "gungu": "용산구",
        "resNm": "국립중앙박물관",
        "rnum": 6,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 0,
        "NatNum": 93554,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "서울역사박물관",
        "rnum": 7,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 13935,
        "NatNum": 52140,
        "addrCd": 1114,
        "gungu": "중구",
        "resNm": "덕수궁",
        "rnum": 8,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 0,
        "NatNum": 61115,
        "addrCd": 1114,
        "gungu": "중구",
        "resNm": "서울시립미술관 본관",
        "rnum": 9,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 10,
        "NatNum": 1885,
        "addrCd": 1135,
        "gungu": "노원구",
        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",
        "rnum": 10,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 0,
        "NatNum": 32412,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문형무소역사관",
        "rnum": 11,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 0,
        "NatNum": 19308,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문자연사박물관",
        "rnum": 12,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 5214,
        "NatNum": 6956,
        "addrCd": 1144,
        "gungu": "마포구",
        "resNm": "트릭아이미술관",
        "rnum": 13,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 333,
        "NatNum": 1823,
        "addrCd": 1165,
        "gungu": "서초구",
        "resNm": "헌릉ㆍ인릉",
        "rnum": 14,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 4704,
        "NatNum": 16634,
        "addrCd": 1168,
        "gungu": "강남구",
        "resNm": "선릉·정릉",
        "rnum": 15,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 52484,
        "NatNum": 642290,
        "addrCd": 1171,
        "gungu": "송파구",
        "resNm": "롯데월드",
        "rnum": 16,
        "sido": "서울특별시",
        "yyyymm": "201112"
    },
    {
        "ForNum": 27814,
        "NatNum": 28061,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창덕궁",
        "rnum": 1,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 546,
        "NatNum": 5978,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "운현궁",
        "rnum": 2,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 105370,
        "NatNum": 133012,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "경복궁",
        "rnum": 3,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 1451,
        "NatNum": 15722,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창경궁",
        "rnum": 4,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 8817,
        "NatNum": 8068,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "종묘",
        "rnum": 5,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 13033,
        "NatNum": 227077,
        "addrCd": 1117,
        "gungu": "용산구",
        "resNm": "국립중앙박물관",
        "rnum": 6,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 1138,
        "NatNum": 78179,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "서울역사박물관",
        "rnum": 7,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 11151,
        "NatNum": 44855,
        "addrCd": 1114,
        "gungu": "중구",
        "resNm": "덕수궁",
        "rnum": 8,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 0,
        "NatNum": 213467,
        "addrCd": 1114,
        "gungu": "중구",
        "resNm": "서울시립미술관 본관",
        "rnum": 9,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 15,
        "NatNum": 1252,
        "addrCd": 1135,
        "gungu": "노원구",
        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",
        "rnum": 10,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 6625,
        "NatNum": 14090,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문형무소역사관",
        "rnum": 11,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 0,
        "NatNum": 18881,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문자연사박물관",
        "rnum": 12,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 24492,
        "NatNum": 9167,
        "addrCd": 1144,
        "gungu": "마포구",
        "resNm": "트릭아이미술관",
        "rnum": 13,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 62,
        "NatNum": 860,
        "addrCd": 1165,
        "gungu": "서초구",
        "resNm": "헌릉ㆍ인릉",
        "rnum": 14,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 66868,
        "NatNum": 670056,
        "addrCd": 1171,
        "gungu": "송파구",
        "resNm": "롯데월드",
        "rnum": 15,
        "sido": "서울특별시",
        "yyyymm": "201212"
    },
    {
        "ForNum": 25550,
        "NatNum": 38553,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창덕궁",
        "rnum": 1,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 101942,
        "NatNum": 145544,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "경복궁",
        "rnum": 2,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 1986,
        "NatNum": 20035,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창경궁",
        "rnum": 3,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 6048,
        "NatNum": 13896,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "종묘",
        "rnum": 4,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 9083,
        "NatNum": 286992,
        "addrCd": 1117,
        "gungu": "용산구",
        "resNm": "국립중앙박물관",
        "rnum": 5,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 13282,
        "NatNum": 99301,
        "addrCd": 1114,
        "gungu": "중구",
        "resNm": "덕수궁",
        "rnum": 6,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 6,
        "NatNum": 706,
        "addrCd": 1135,
        "gungu": "노원구",
        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",
        "rnum": 7,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 6732,
        "NatNum": 14607,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문형무소역사관",
        "rnum": 8,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 0,
        "NatNum": 23245,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문자연사박물관",
        "rnum": 9,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 43129,
        "NatNum": 11886,
        "addrCd": 1144,
        "gungu": "마포구",
        "resNm": "트릭아이미술관",
        "rnum": 10,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 16,
        "NatNum": 1248,
        "addrCd": 1165,
        "gungu": "서초구",
        "resNm": "헌릉ㆍ인릉",
        "rnum": 11,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 1445,
        "NatNum": 11890,
        "addrCd": 1168,
        "gungu": "강남구",
        "resNm": "선릉·정릉",
        "rnum": 12,
        "sido": "서울특별시",
        "yyyymm": "201312"
    },
    {
        "ForNum": 29928,
        "NatNum": 41561,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창덕궁",
        "rnum": 1,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 129946,
        "NatNum": 190501,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "경복궁",
        "rnum": 2,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 1693,
        "NatNum": 19473,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창경궁",
        "rnum": 3,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 3891,
        "NatNum": 5951,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "종묘",
        "rnum": 4,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 7195,
        "NatNum": 258781,
        "addrCd": 1117,
        "gungu": "용산구",
        "resNm": "국립중앙박물관",
        "rnum": 5,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 14723,
        "NatNum": 44272,
        "addrCd": 1114,
        "gungu": "중구",
        "resNm": "덕수궁",
        "rnum": 6,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 12,
        "NatNum": 486,
        "addrCd": 1135,
        "gungu": "노원구",
        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",
        "rnum": 7,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 6263,
        "NatNum": 27205,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문형무소역사관",
        "rnum": 8,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 0,
        "NatNum": 24527,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문자연사박물관",
        "rnum": 9,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 42443,
        "NatNum": 7478,
        "addrCd": 1144,
        "gungu": "마포구",
        "resNm": "트릭아이미술관",
        "rnum": 10,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 5,
        "NatNum": 1036,
        "addrCd": 1165,
        "gungu": "서초구",
        "resNm": "헌릉ㆍ인릉",
        "rnum": 11,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 823,
        "NatNum": 8869,
        "addrCd": 1168,
        "gungu": "강남구",
        "resNm": "선릉·정릉",
        "rnum": 12,
        "sido": "서울특별시",
        "yyyymm": "201412"
    },
    {
        "ForNum": 33342,
        "NatNum": 59738,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창덕궁",
        "rnum": 1,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 170379,
        "NatNum": 148961,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "경복궁",
        "rnum": 2,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 1783,
        "NatNum": 27172,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "창경궁",
        "rnum": 3,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 3406,
        "NatNum": 14936,
        "addrCd": 1111,
        "gungu": "종로구",
        "resNm": "종묘",
        "rnum": 4,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 13127,
        "NatNum": 281457,
        "addrCd": 1117,
        "gungu": "용산구",
        "resNm": "국립중앙박물관",
        "rnum": 5,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 15197,
        "NatNum": 68749,
        "addrCd": 1114,
        "gungu": "중구",
        "resNm": "덕수궁",
        "rnum": 6,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 16,
        "NatNum": 2221,
        "addrCd": 1135,
        "gungu": "노원구",
        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",
        "rnum": 7,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 5588,
        "NatNum": 44232,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문형무소역사관",
        "rnum": 8,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 0,
        "NatNum": 22587,
        "addrCd": 1141,
        "gungu": "서대문구",
        "resNm": "서대문자연사박물관",
        "rnum": 9,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 29520,
        "NatNum": 8822,
        "addrCd": 1144,
        "gungu": "마포구",
        "resNm": "트릭아이미술관",
        "rnum": 10,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 3,
        "NatNum": 1647,
        "addrCd": 1165,
        "gungu": "서초구",
        "resNm": "헌릉ㆍ인릉",
        "rnum": 11,
        "sido": "서울특별시",
        "yyyymm": "201512"
    },
    {
        "ForNum": 492,
        "NatNum": 14454,
        "addrCd": 1168,
        "gungu": "강남구",
        "resNm": "선릉·정릉",
        "rnum": 12,
        "sido": "서울특별시",
        "yyyymm": "201512"
    }
]

In [5]:
print(type(trip_info))

<class 'str'>

In [6]:
trip_info[0:100]

'[\n    {\n        "ForNum": 44722,\n        "NatNum": 75991,\n        "addrCd": 1111,\n        "gungu": "'

# 문자열을 JSON/DICT 형식으로 변환
# json 모듈
# json.loads(함수)

In [7]:
import json

In [8]:
data = json.loads(trip_info)

In [9]:
data[0].items()

dict_items([('ForNum', 44722), ('NatNum', 75991), ('addrCd', 1111), ('gungu', '종로구'), ('resNm', '창덕궁'), ('rnum', 1), ('sido', '서울특별시'), ('yyyymm', '201112')])

In [10]:
type(data[0])

dict

In [11]:
list(data[0].keys())

['ForNum', 'NatNum', 'addrCd', 'gungu', 'resNm', 'rnum', 'sido', 'yyyymm']

* 1) data 변수에 json.loads()로 문자열로 읽어온 파일을 json 형식으로 변환하기
* 2) 구조 파악하기 리스트, 딕셔너리 구조 
* 3) data는 리스트 안에 67개의 딕셔너리 세트가 저장되어 있음.
* 4) 각 딕셔너리에는 ['ForNum', 'NatNum', 'addrCd', 'gungu', 'resNm', 'rnum', 'sido', 'yyyymm'] 키로 관광지 입장객 정보가 저장되어 있음.
* 5) 67개의 딕셔너리에서 하나의 key당 67개의 value를 리스트 형태로 저장
* 6) pandas를 이용해서 dataframe으로 변환

* value를 리스트로 만든 후 dict함수로 딕셔너리로 만들어 데이터프레임 만들기
* 1) 딕셔너리에 key를 직접 입력해서 value를 추출
* 2) key 이름의 list에 value를 append 해서 value 리스트 만듬
* 3) key : value_list 형태로 딕셔너리를 다시 만듬
* 4) 최종 완성된 딕셔너리를 dataframe으로 변환

In [12]:
print(type(data))
# data 리스트 안에 67개의 딕셔너리 세트가 있음.
print(len(data))

<class 'list'>
67

In [13]:
data[0].keys()

dict_keys(['ForNum', 'NatNum', 'addrCd', 'gungu', 'resNm', 'rnum', 'sido', 'yyyymm'])

In [14]:
data[0]

{'ForNum': 44722,
 'NatNum': 75991,
 'addrCd': 1111,
 'gungu': '종로구',
 'resNm': '창덕궁',
 'rnum': 1,
 'sido': '서울특별시',
 'yyyymm': '201112'}

In [17]:
data[0]['ForNum']

44722

In [106]:
fn = []
nn = []
ac = []
gg = []
rm = []
r_num = []
sd = []
ym =[]

In [91]:
ForNum = data[2]['ForNum']
NatNum = data[2]['NatNum']
addrCd = data[2]['addrCd']
gungu = data[2]['gungu']
resNm = data[2]['resNm']
rnum = data[2]['rnum']
sido = data[2]['sido']
yyyymm = data[2]['yyyymm']

# print(ForNum, NatNum, addrCd, gungu, resNm, rnum, sido, yyyymm )

fn.append(ForNum)
nn.append(NatNum)
ac.append(addrCd)
gg.append(gungu)
rm.append(resNm)
r_num.append(rnum)
sd.append(sido)
ym.append(yyyymm)

print(fn)
print(nn)
print(ac)
print(gg)
print(rm)
print(r_num)
print(sd)
print(ym)

[44722, 0, 132399]
[75991, 11017, 237330]
[1111, 1111, 1111]
['종로구', '종로구', '종로구']
['창덕궁', '운현궁', '경복궁']
[1, 2, 3]
['서울특별시', '서울특별시', '서울특별시']
['201112', '201112', '201112']

# 한땀한땀 하려니 힘들다. 반복문을 쓰자!

In [18]:
fn = []
nn = []
ac = []
gg = []
rm = []
r_num = []
sd = []
ym =[]

In [19]:
print(type(data))

<class 'list'>

In [20]:
len(data)

67

In [21]:
# for i in range(len(data)):
#     print(i)

In [22]:
for i in range(len(data)):
    ForNum = data[i]['ForNum']
    NatNum = data[i]['NatNum']
    addrCd = data[i]['addrCd']
    gungu = data[i]['gungu']
    resNm = data[i]['resNm']
    rnum = data[i]['rnum']
    sido = data[i]['sido']
    yyyymm = data[i]['yyyymm']

    # print(ForNum, NatNum, addrCd, gungu, resNm, rnum, sido, yyyymm )

    fn.append(ForNum)
    nn.append(NatNum)
    ac.append(addrCd)
    gg.append(gungu)
    rm.append(resNm)
    r_num.append(rnum)
    sd.append(sido)
    ym.append(yyyymm)

#     print(fn)
#     print(nn)
#     print(ac)
#     print(gg)
#     print(rm)
#     print(r_num)
#     print(sd)
#     print(ym)
#     print()

In [23]:
data[0].keys()

dict_keys(['ForNum', 'NatNum', 'addrCd', 'gungu', 'resNm', 'rnum', 'sido', 'yyyymm'])

In [25]:
len(rm)

67

In [26]:
result = dict(ForNum=fn, NatNum=nn, addrCd=ac, gungu=gg, resNm=rm, rnum=r_num, sido=sd, yyyymm=ym)
result

{'ForNum': [44722,
  0,
  132399,
  3133,
  18226,
  0,
  0,
  13935,
  0,
  10,
  0,
  0,
  5214,
  333,
  4704,
  52484,
  27814,
  546,
  105370,
  1451,
  8817,
  13033,
  1138,
  11151,
  0,
  15,
  6625,
  0,
  24492,
  62,
  66868,
  25550,
  101942,
  1986,
  6048,
  9083,
  13282,
  6,
  6732,
  0,
  43129,
  16,
  1445,
  29928,
  129946,
  1693,
  3891,
  7195,
  14723,
  12,
  6263,
  0,
  42443,
  5,
  823,
  33342,
  170379,
  1783,
  3406,
  13127,
  15197,
  16,
  5588,
  0,
  29520,
  3,
  492],
 'NatNum': [75991,
  11017,
  237330,
  21267,
  24223,
  233828,
  93554,
  52140,
  61115,
  1885,
  32412,
  19308,
  6956,
  1823,
  16634,
  642290,
  28061,
  5978,
  133012,
  15722,
  8068,
  227077,
  78179,
  44855,
  213467,
  1252,
  14090,
  18881,
  9167,
  860,
  670056,
  38553,
  145544,
  20035,
  13896,
  286992,
  99301,
  706,
  14607,
  23245,
  11886,
  1248,
  11890,
  41561,
  190501,
  19473,
  5951,
  258781,
  44272,
  486,
  27205,
  24527,
  7478,
  1036,
  8869,
  59738,
  148961,
  27172,
  14936,
  281457,
  68749,
  2221,
  44232,
  22587,
  8822,
  1647,
  14454],
 'addrCd': [1111,
  1111,
  1111,
  1111,
  1111,
  1117,
  1111,
  1114,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1171,
  1111,
  1111,
  1111,
  1111,
  1111,
  1117,
  1111,
  1114,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1171,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168],
 'gungu': ['종로구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '종로구',
  '중구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '송파구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '종로구',
  '중구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '송파구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구'],
 'resNm': ['창덕궁',
  '운현궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '서울역사박물관',
  '덕수궁',
  '서울시립미술관 본관',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '롯데월드',
  '창덕궁',
  '운현궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '서울역사박물관',
  '덕수궁',
  '서울시립미술관 본관',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '롯데월드',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉'],
 'rnum': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12],
 'sido': ['서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시'],
 'yyyymm': ['201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512']}

In [27]:
import pandas as pd

In [28]:
result_df = pd.DataFrame(result)
result_df

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]

# 반복문을 사용하되 range없이 사용하기

In [29]:
fn = []
nn = []
ac = []
gg = []
rm = []
r_num = []
sd = []
ym =[]

In [30]:
for dicts in data:
    ForNum = dicts['ForNum']
    NatNum = dicts['NatNum']
    addrCd = dicts['addrCd']
    gungu = dicts['gungu']
    resNm = dicts['resNm']
    rnum = dicts['rnum']
    sido = dicts['sido']
    yyyymm = dicts['yyyymm']
    
    fn.append(ForNum)
    nn.append(NatNum)
    ac.append(addrCd)
    gg.append(gungu)
    rm.append(resNm)
    r_num.append(rnum)
    sd.append(sido)
    ym.append(yyyymm)

#     print(fn)
#     print(nn)
#     print(ac)
#     print(gg)
#     print(rm)
#     print(r_num)
#     print(sd)
#     print(ym)
#     print()

# 딕셔너리의 key도 자동으로 넣을 수 있을까?

In [130]:
data[0]['ForNum']

44722

In [132]:
data[0].keys()

dict_keys(['ForNum', 'NatNum', 'addrCd', 'gungu', 'resNm', 'rnum', 'sido', 'yyyymm'])

In [31]:
for key in data[0]:
    print(key)

ForNum
NatNum
addrCd
gungu
resNm
rnum
sido
yyyymm

In [34]:
fn = []
nn = []
ac = []
gg = []
rm = []
r_num = []
sd = []
ym =[]

In [41]:
result = {}
for key in data[0]:
    temp = []
    for dicts in data:
        temp.append(dicts[key])
    result[key] = temp
print(result)

{'ForNum': [44722, 0, 132399, 3133, 18226, 0, 0, 13935, 0, 10, 0, 0, 5214, 333, 4704, 52484, 27814, 546, 105370, 1451, 8817, 13033, 1138, 11151, 0, 15, 6625, 0, 24492, 62, 66868, 25550, 101942, 1986, 6048, 9083, 13282, 6, 6732, 0, 43129, 16, 1445, 29928, 129946, 1693, 3891, 7195, 14723, 12, 6263, 0, 42443, 5, 823, 33342, 170379, 1783, 3406, 13127, 15197, 16, 5588, 0, 29520, 3, 492], 'NatNum': [75991, 11017, 237330, 21267, 24223, 233828, 93554, 52140, 61115, 1885, 32412, 19308, 6956, 1823, 16634, 642290, 28061, 5978, 133012, 15722, 8068, 227077, 78179, 44855, 213467, 1252, 14090, 18881, 9167, 860, 670056, 38553, 145544, 20035, 13896, 286992, 99301, 706, 14607, 23245, 11886, 1248, 11890, 41561, 190501, 19473, 5951, 258781, 44272, 486, 27205, 24527, 7478, 1036, 8869, 59738, 148961, 27172, 14936, 281457, 68749, 2221, 44232, 22587, 8822, 1647, 14454], 'addrCd': [1111, 1111, 1111, 1111, 1111, 1117, 1111, 1114, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1171, 1111, 1111, 1111, 1111, 1111, 1117, 1111, 1114, 1114, 1135, 1141, 1141, 1144, 1165, 1171, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168], 'gungu': ['종로구', '종로구', '종로구', '종로구', '종로구', '용산구', '종로구', '중구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '송파구', '종로구', '종로구', '종로구', '종로구', '종로구', '용산구', '종로구', '중구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '송파구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구'], 'resNm': ['창덕궁', '운현궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '서울역사박물관', '덕수궁', '서울시립미술관 본관', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '롯데월드', '창덕궁', '운현궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '서울역사박물관', '덕수궁', '서울시립미술관 본관', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '롯데월드', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉'], 'rnum': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 'sido': ['서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시'], 'yyyymm': ['201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512']}

# 좀 더 쉽게 딕너리 함수를 이용해서 할 수 있을까?

In [42]:
result2 = {}
for dicts in data[:2]:
    for key, value in dicts.items():
        result2.setdefault(key, []).append(value)
        print(result2)

{'ForNum': [44722]}
{'ForNum': [44722], 'NatNum': [75991]}
{'ForNum': [44722], 'NatNum': [75991], 'addrCd': [1111]}
{'ForNum': [44722], 'NatNum': [75991], 'addrCd': [1111], 'gungu': ['종로구']}
{'ForNum': [44722], 'NatNum': [75991], 'addrCd': [1111], 'gungu': ['종로구'], 'resNm': ['창덕궁']}
{'ForNum': [44722], 'NatNum': [75991], 'addrCd': [1111], 'gungu': ['종로구'], 'resNm': ['창덕궁'], 'rnum': [1]}
{'ForNum': [44722], 'NatNum': [75991], 'addrCd': [1111], 'gungu': ['종로구'], 'resNm': ['창덕궁'], 'rnum': [1], 'sido': ['서울특별시']}
{'ForNum': [44722], 'NatNum': [75991], 'addrCd': [1111], 'gungu': ['종로구'], 'resNm': ['창덕궁'], 'rnum': [1], 'sido': ['서울특별시'], 'yyyymm': ['201112']}
{'ForNum': [44722, 0], 'NatNum': [75991], 'addrCd': [1111], 'gungu': ['종로구'], 'resNm': ['창덕궁'], 'rnum': [1], 'sido': ['서울특별시'], 'yyyymm': ['201112']}
{'ForNum': [44722, 0], 'NatNum': [75991, 11017], 'addrCd': [1111], 'gungu': ['종로구'], 'resNm': ['창덕궁'], 'rnum': [1], 'sido': ['서울특별시'], 'yyyymm': ['201112']}
{'ForNum': [44722, 0], 'NatNum': [75991, 11017], 'addrCd': [1111, 1111], 'gungu': ['종로구'], 'resNm': ['창덕궁'], 'rnum': [1], 'sido': ['서울특별시'], 'yyyymm': ['201112']}
{'ForNum': [44722, 0], 'NatNum': [75991, 11017], 'addrCd': [1111, 1111], 'gungu': ['종로구', '종로구'], 'resNm': ['창덕궁'], 'rnum': [1], 'sido': ['서울특별시'], 'yyyymm': ['201112']}
{'ForNum': [44722, 0], 'NatNum': [75991, 11017], 'addrCd': [1111, 1111], 'gungu': ['종로구', '종로구'], 'resNm': ['창덕궁', '운현궁'], 'rnum': [1], 'sido': ['서울특별시'], 'yyyymm': ['201112']}
{'ForNum': [44722, 0], 'NatNum': [75991, 11017], 'addrCd': [1111, 1111], 'gungu': ['종로구', '종로구'], 'resNm': ['창덕궁', '운현궁'], 'rnum': [1, 2], 'sido': ['서울특별시'], 'yyyymm': ['201112']}
{'ForNum': [44722, 0], 'NatNum': [75991, 11017], 'addrCd': [1111, 1111], 'gungu': ['종로구', '종로구'], 'resNm': ['창덕궁', '운현궁'], 'rnum': [1, 2], 'sido': ['서울특별시', '서울특별시'], 'yyyymm': ['201112']}
{'ForNum': [44722, 0], 'NatNum': [75991, 11017], 'addrCd': [1111, 1111], 'gungu': ['종로구', '종로구'], 'resNm': ['창덕궁', '운현궁'], 'rnum': [1, 2], 'sido': ['서울특별시', '서울특별시'], 'yyyymm': ['201112', '201112']}

In [ ]:
year_mon = []
sido = []
place = []
foriners = []
total = []

for item in data:
    foriners.append(item['ForNum'])
    total.append(item['NatNum'])
    place.append(item['resNm'])
    sido.append(item['sido'])
    year_mon.append(item['yyyymm'])
    
tour_info = dict(년월=year_mon, 시도=sido, 장소=place, 외국인=foriners, 전체방문객수=total)
tour_info

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(tour_info)
df

* 딕셔너리를 바로 만들어서 데이터프레임으로 변환
* key, value를 직접 할당해서 딕셔너리 만들기

In [82]:
d = {}
d['장소'] = "경복궁"
d

{'장소': '경복궁'}

In [83]:
result = {}
for key in data[0]:
    value_list = []
    for item in data:
        value_list.append(item[key])
    print(key, value_list)
    result[key] = value_list

result

ForNum [44722, 0, 132399, 3133, 18226, 0, 0, 13935, 0, 10, 0, 0, 5214, 333, 4704, 52484, 27814, 546, 105370, 1451, 8817, 13033, 1138, 11151, 0, 15, 6625, 0, 24492, 62, 66868, 25550, 101942, 1986, 6048, 9083, 13282, 6, 6732, 0, 43129, 16, 1445, 29928, 129946, 1693, 3891, 7195, 14723, 12, 6263, 0, 42443, 5, 823, 33342, 170379, 1783, 3406, 13127, 15197, 16, 5588, 0, 29520, 3, 492]
NatNum [75991, 11017, 237330, 21267, 24223, 233828, 93554, 52140, 61115, 1885, 32412, 19308, 6956, 1823, 16634, 642290, 28061, 5978, 133012, 15722, 8068, 227077, 78179, 44855, 213467, 1252, 14090, 18881, 9167, 860, 670056, 38553, 145544, 20035, 13896, 286992, 99301, 706, 14607, 23245, 11886, 1248, 11890, 41561, 190501, 19473, 5951, 258781, 44272, 486, 27205, 24527, 7478, 1036, 8869, 59738, 148961, 27172, 14936, 281457, 68749, 2221, 44232, 22587, 8822, 1647, 14454]
addrCd [1111, 1111, 1111, 1111, 1111, 1117, 1111, 1114, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1171, 1111, 1111, 1111, 1111, 1111, 1117, 1111, 1114, 1114, 1135, 1141, 1141, 1144, 1165, 1171, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168]
gungu ['종로구', '종로구', '종로구', '종로구', '종로구', '용산구', '종로구', '중구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '송파구', '종로구', '종로구', '종로구', '종로구', '종로구', '용산구', '종로구', '중구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '송파구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구']
resNm ['창덕궁', '운현궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '서울역사박물관', '덕수궁', '서울시립미술관 본관', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '롯데월드', '창덕궁', '운현궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '서울역사박물관', '덕수궁', '서울시립미술관 본관', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '롯데월드', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉']
rnum [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
sido ['서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시']
yyyymm ['201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512']

{'ForNum': [44722,
  0,
  132399,
  3133,
  18226,
  0,
  0,
  13935,
  0,
  10,
  0,
  0,
  5214,
  333,
  4704,
  52484,
  27814,
  546,
  105370,
  1451,
  8817,
  13033,
  1138,
  11151,
  0,
  15,
  6625,
  0,
  24492,
  62,
  66868,
  25550,
  101942,
  1986,
  6048,
  9083,
  13282,
  6,
  6732,
  0,
  43129,
  16,
  1445,
  29928,
  129946,
  1693,
  3891,
  7195,
  14723,
  12,
  6263,
  0,
  42443,
  5,
  823,
  33342,
  170379,
  1783,
  3406,
  13127,
  15197,
  16,
  5588,
  0,
  29520,
  3,
  492],
 'NatNum': [75991,
  11017,
  237330,
  21267,
  24223,
  233828,
  93554,
  52140,
  61115,
  1885,
  32412,
  19308,
  6956,
  1823,
  16634,
  642290,
  28061,
  5978,
  133012,
  15722,
  8068,
  227077,
  78179,
  44855,
  213467,
  1252,
  14090,
  18881,
  9167,
  860,
  670056,
  38553,
  145544,
  20035,
  13896,
  286992,
  99301,
  706,
  14607,
  23245,
  11886,
  1248,
  11890,
  41561,
  190501,
  19473,
  5951,
  258781,
  44272,
  486,
  27205,
  24527,
  7478,
  1036,
  8869,
  59738,
  148961,
  27172,
  14936,
  281457,
  68749,
  2221,
  44232,
  22587,
  8822,
  1647,
  14454],
 'addrCd': [1111,
  1111,
  1111,
  1111,
  1111,
  1117,
  1111,
  1114,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1171,
  1111,
  1111,
  1111,
  1111,
  1111,
  1117,
  1111,
  1114,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1171,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168],
 'gungu': ['종로구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '종로구',
  '중구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '송파구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '종로구',
  '중구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '송파구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구'],
 'resNm': ['창덕궁',
  '운현궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '서울역사박물관',
  '덕수궁',
  '서울시립미술관 본관',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '롯데월드',
  '창덕궁',
  '운현궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '서울역사박물관',
  '덕수궁',
  '서울시립미술관 본관',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '롯데월드',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉'],
 'rnum': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12],
 'sido': ['서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시'],
 'yyyymm': ['201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512']}

In [86]:
result_df = pd.DataFrame(result)
result_df

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]

In [89]:
d2 = {}
d2.setdefault("key", 3)
d2

{'key': 3}

* setdefault 함수를 이용해 만들기

In [90]:
dic_result = {}
for dicts in data:
    for key, value in dicts.items():
        dic_result.setdefault(key, []).append(value)
dic_result

{'ForNum': [44722,
  0,
  132399,
  3133,
  18226,
  0,
  0,
  13935,
  0,
  10,
  0,
  0,
  5214,
  333,
  4704,
  52484,
  27814,
  546,
  105370,
  1451,
  8817,
  13033,
  1138,
  11151,
  0,
  15,
  6625,
  0,
  24492,
  62,
  66868,
  25550,
  101942,
  1986,
  6048,
  9083,
  13282,
  6,
  6732,
  0,
  43129,
  16,
  1445,
  29928,
  129946,
  1693,
  3891,
  7195,
  14723,
  12,
  6263,
  0,
  42443,
  5,
  823,
  33342,
  170379,
  1783,
  3406,
  13127,
  15197,
  16,
  5588,
  0,
  29520,
  3,
  492],
 'NatNum': [75991,
  11017,
  237330,
  21267,
  24223,
  233828,
  93554,
  52140,
  61115,
  1885,
  32412,
  19308,
  6956,
  1823,
  16634,
  642290,
  28061,
  5978,
  133012,
  15722,
  8068,
  227077,
  78179,
  44855,
  213467,
  1252,
  14090,
  18881,
  9167,
  860,
  670056,
  38553,
  145544,
  20035,
  13896,
  286992,
  99301,
  706,
  14607,
  23245,
  11886,
  1248,
  11890,
  41561,
  190501,
  19473,
  5951,
  258781,
  44272,
  486,
  27205,
  24527,
  7478,
  1036,
  8869,
  59738,
  148961,
  27172,
  14936,
  281457,
  68749,
  2221,
  44232,
  22587,
  8822,
  1647,
  14454],
 'addrCd': [1111,
  1111,
  1111,
  1111,
  1111,
  1117,
  1111,
  1114,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1171,
  1111,
  1111,
  1111,
  1111,
  1111,
  1117,
  1111,
  1114,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1171,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168],
 'gungu': ['종로구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '종로구',
  '중구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '송파구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '종로구',
  '중구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '송파구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구'],
 'resNm': ['창덕궁',
  '운현궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '서울역사박물관',
  '덕수궁',
  '서울시립미술관 본관',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '롯데월드',
  '창덕궁',
  '운현궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '서울역사박물관',
  '덕수궁',
  '서울시립미술관 본관',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '롯데월드',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉'],
 'rnum': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12],
 'sido': ['서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시'],
 'yyyymm': ['201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512']}

In [91]:
dic_result_df = pd.DataFrame(dic_result)
dic_result_df

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]

In [100]:
l = []

In [103]:

l.append(list(range(11, 13)))

In [110]:
l

[[1, 2, 3, 4], [5, 6, 7, 8, 9, 10], [11, 12]]

In [109]:
for items in l:
    for _ in items:
        print(items)

[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[5, 6, 7, 8, 9, 10]
[5, 6, 7, 8, 9, 10]
[5, 6, 7, 8, 9, 10]
[5, 6, 7, 8, 9, 10]
[5, 6, 7, 8, 9, 10]
[5, 6, 7, 8, 9, 10]
[11, 12]
[11, 12]

In [111]:
d  = []
d

[]

In [112]:
d.append(1)
d

[1]