국민은행 앱 사용자 리뷰 데이터 JSON 파일을 읽어와서 csv파일로 변환하기

In [1]:
import json
import pandas as pd

In [2]:
with open("./data/com_kbstar_kbbank.json", 'r', encoding="utf-8") as file:
    data = file.read()

In [3]:
data[:100]

'[\n    {\n        "사용자": "박성진 (홀리진)",\n        "별점": "4",\n        "리뷰": "리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면'

In [4]:
reviews = json.loads(data)
len(reviews)

2223

In [6]:
reviews[0]

{'사용자': '박성진 (홀리진)',
 '별점': '4',
 '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
 '날짜': '2025년 3월 2일',
 '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}

In [ ]:
result = {}
for key in reviews[0]:
    temp =  []
    for review in reviews:
        temp.append(review[key])
    result[key] = temp
len(result['별점'])

In [ ]:
df = pd.DataFrame(result)
df

별점은 숫자로 변환해서 넣기, 나머지는 특수문자 제거하기

In [ ]:
for key in reviews[0]:
    for review in reviews:
        print(review[key].replace("?", ""))

In [8]:
result = {}
for key in reviews[0]:
    temp =  []
    for review in reviews:
        if key == '별점':
            temp.append(int(review[key]))
        else:
#             print(type(review[key]))
            temp2 = str(review[key]).replace("?", " ").replace("(", " ").replace(")", " ").replace("!", " ")
            temp.append(temp2)
    result[key] = temp
len(result['별점'])
df = pd.DataFrame(result)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 홀리진,4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요 KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용자     2223 non-null   object
 1   별점      2223 non-null   int64
 2   리뷰      2223 non-null   object
 3   날짜      2223 non-null   object
 4   개발자 응답  2223 non-null   object
dtypes: int64(1), object(4)
memory usage: 87.0+ KB

In [13]:
result2 = {}
for review in reviews:
    for key, value in review.items():
        result2.setdefault(key, []).append(value)
result2_df = pd.DataFrame(result2)
# result2_df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

In [40]:
with open("./data/전국치킨집리스트.json", 'r', encoding="utf-8") as file2:
    chick = file2.read()
data = json.loads(chick)

In [41]:
len(data)

37

* data에는 리스트 요소가 37개 있슴.
* 리스트 요소 1개에는 1000개의 딕셔너리가 있고 그 안에 가게 정보가 있슴
* 가게 정보는 data[0]['body']['items'] 에 있다.
* 가게 정보를 구성하는 key는 39개이다.

['상가업소번호',
 '상호명',
 '지점명',
 '상권업종대분류코드',
 '상권업종대분류명',
 '상권업종중분류코드',
 '상권업종중분류명',
 '상권업종소분류코드',
 '상권업종소분류명',
 '표준산업분류코드',
 '표준산업분류명',
 '시도코드',
 '시도명',
 '시군구코드',
 '시군구명',
 '행정동코드',
 '행정동명',
 '법정동코드',
 '법정동명',
 'PNU코드',
 '대지구분코드',
 '대지구분명',
 '지번본번지',
 '지번부번지',
 '지번주소',
 '도로명코드',
 '도로명',
 '건물본번지',
 '건물부번지',
 '건물관리번호',
 '건물명',
 '도로명주소',
 '구우편번호',
 '신우편번호',
 '동정보',
 '층정보',
 '호정보',
 '경도',
 '위도']

In [53]:
data[0]['body']['items'][0]

{'bizesId': '10027626',
 'bizesNm': '장모님치킨가창점',
 'brchNm': '가창점',
 'indsLclsCd': 'Q',
 'indsLclsNm': '음식',
 'indsMclsCd': 'Q05',
 'indsMclsNm': '닭/오리요리',
 'indsSclsCd': 'Q05A08',
 'indsSclsNm': '후라이드/양념치킨',
 'ksicCd': 'I56193',
 'ksicNm': '치킨 전문점',
 'ctprvnCd': '27',
 'ctprvnNm': '대구광역시',
 'signguCd': '27710',
 'signguNm': '달성군',
 'adongCd': '2771031000',
 'adongNm': '가창면',
 'ldongCd': '2771031024',
 'ldongNm': '가창면',
 'lnoCd': '2771031024101200001',
 'plotSctCd': '1',
 'plotSctNm': '대지',
 'lnoMnno': 120,
 'lnoSlno': 1,
 'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1',
 'rdnmCd': '277103148001',
 'rdnm': '대구광역시 달성군 가창면 가창동로',
 'bldMnno': 6,
 'bldSlno': '',
 'bldMngNo': '2771031024101200004036858',
 'bldNm': '',
 'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6',
 'oldZipcd': '711861',
 'newZipcd': '42938',
 'dongNo': '',
 'flrNo': '1',
 'hoNo': '',
 'lon': 128.644458591419,
 'lat': 35.7826625402814}

In [37]:
result3 = {}
for page in data:
    for item in page['body']['items']:
        for key, value in item.items():
            result3.setdefault(key, []).append(value)
#         print(key, value)
len(result3['bizesId'])

36064

In [39]:
df = pd.DataFrame(result3)
df

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36059,9829515,아리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010200106740003008662,,경기도 동두천시 거북마루로 6,483020,11348,,1,,127.046713,37.895702
36060,9851302,애니치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4785031036104090002008916,,경상북도 칠곡군 지천면 신동로 147,718821,39864,,,,128.488717,35.956631
36061,9867543,에디슨치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1135010600103590001010681,중계5단지주공아파트,서울특별시 노원구 중계로 230,139781,01713,,1,,127.075031,37.651004
36062,9918905,오븐에꾸운닭장유점,장유점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4825031027103150002091993,재영프라자,경상남도 김해시 삼문로 26,621280,51004,,1,,128.803565,35.192491
36063,9967953,웰빙치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011100101360002016167,,강원도 원주시 상지대길 43,220954,26342,,1,,127.937290,37.369591

In [48]:
data[0]['header']['columns']

['상가업소번호',
 '상호명',
 '지점명',
 '상권업종대분류코드',
 '상권업종대분류명',
 '상권업종중분류코드',
 '상권업종중분류명',
 '상권업종소분류코드',
 '상권업종소분류명',
 '표준산업분류코드',
 '표준산업분류명',
 '시도코드',
 '시도명',
 '시군구코드',
 '시군구명',
 '행정동코드',
 '행정동명',
 '법정동코드',
 '법정동명',
 'PNU코드',
 '대지구분코드',
 '대지구분명',
 '지번본번지',
 '지번부번지',
 '지번주소',
 '도로명코드',
 '도로명',
 '건물본번지',
 '건물부번지',
 '건물관리번호',
 '건물명',
 '도로명주소',
 '구우편번호',
 '신우편번호',
 '동정보',
 '층정보',
 '호정보',
 '경도',
 '위도']

In [52]:
result4 = {}
for page in data:
    for item in page['body']['items']:
        for key, value in zip(page['header']['columns'], item.values()):
            result4.setdefault(key, []).append(value)

df2 = pd.DataFrame(result4)
df2

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36059,9829515,아리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010200106740003008662,,경기도 동두천시 거북마루로 6,483020,11348,,1,,127.046713,37.895702
36060,9851302,애니치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4785031036104090002008916,,경상북도 칠곡군 지천면 신동로 147,718821,39864,,,,128.488717,35.956631
36061,9867543,에디슨치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1135010600103590001010681,중계5단지주공아파트,서울특별시 노원구 중계로 230,139781,01713,,1,,127.075031,37.651004
36062,9918905,오븐에꾸운닭장유점,장유점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4825031027103150002091993,재영프라자,경상남도 김해시 삼문로 26,621280,51004,,1,,128.803565,35.192491
36063,9967953,웰빙치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011100101360002016167,,강원도 원주시 상지대길 43,220954,26342,,1,,127.937290,37.369591

# pandas의 json_normalize를 이용해서 쉽게 json에서 DataFrame으로 만들기

In [56]:
pd.json_normalize(data[0]['body']['items'])

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,11927120,두두두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4719034028104640013062144,,경상북도 구미시 해평면 강동로 1671,730873,39154,,1,,128.390989,36.199637
996,11927310,호식이두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4272025029104520007040192,,강원도 홍천군 홍천읍 남산강변로 32,250930,25149,,1,,127.882012,37.685865
997,11927491,또봉이치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2820010200100690027020930,,인천광역시 남동구 풀무로 9-2,405230,21510,,1,,126.709187,37.469419
998,11927616,투마리치킨하늘도시점,하늘도시점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2811014600100330008000001,,인천광역시 중구 운중로 85-1,400811,22359,,1,,126.542880,37.493596
999,11927757,노랑통닭,구리수택점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4131010500104480006008791,구리신성미소지움,경기도 구리시 이문안로 81,471030,11941,101,1,,127.140380,37.592408