In [5]:
import pandas as pd

In [6]:
# dataframe
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}
countries = pd.DataFrame(data)
countries = countries.set_index('country') # 인덱스 지정
countries

                population    area    capital
country
Belgium               11.3   30510   Brussels
France                64.3  671308      Paris
Germany               81.3  357050     Berlin
Netherlands           16.9   41526  Amsterdam
United Kingdom        64.9  244820     London

In [7]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Belgium to United Kingdom
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  5 non-null      float64
 1   area        5 non-null      int64
 2   capital     5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

---

<div class="alert alert-success">
    <b>EXERCISE 01</b>: 인구밀도를 의미하는 `density` 칼럼을 추가하세요. (주의: 현재 'population' 칼럼은 100만 단위로 표기되어 있습니다)  
  
</div>

In [8]:
countries['density'] = countries['population'] * 1000000 / countries['area']

In [9]:
countries

                population    area    capital     density
country
Belgium               11.3   30510   Brussels  370.370370
France                64.3  671308      Paris   95.783158
Germany               81.3  357050     Berlin  227.699202
Netherlands           16.9   41526  Amsterdam  406.973944
United Kingdom        64.9  244820     London  265.092721

<div class="alert alert-success">
    <b>EXERCISE 02</b>: 인구밀도가 300을 초과하는 국가(country)의 수도(capital)과 인구(population)을 선택해주세요.  
  
</div>

In [10]:
countries.loc[countries['density'] > 300, ['capital', 'population']]

               capital  population
country
Belgium       Brussels        11.3
Netherlands  Amsterdam        16.9

<div class="alert alert-success">
    <b>EXERCISE 03</b>: 'density_ratio' 칼럼을 추가해주세요. (density_ratio = 인구밀도/평균 인구밀도)
</div>

In [11]:
countries['density_ratio'] = countries['density'] / countries['density'].mean()
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE 04</b>: 영국(United Kingdom)의 수도(capital)를 'Cambridge'로 변경해주세요.
</div>

In [12]:
countries.loc['United Kingdom', 'capital'] = "Cambridge"
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE 05</b>: 인구 밀도가 100 초과, 300 미만인 국가들을 표시해주세요.  
</div>

In [13]:
countries[(countries["density"] > 100) & (countries["density"] < 300)]

                population    area    capital     density  density_ratio
country
Germany               81.3  357050     Berlin  227.699202       0.833502
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE 06</b>: 수도가 7글자 이상인 국가들을 표시해주세요. (힌트: string의 len( )를 사용하세요.)
</div>

In [14]:
countries[countries["capital"].str.len() > 7]

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE 07</b>: 수도에 'am' 이 포함되는 국가들을 표시해주세요. (힌트: string의 contains( )를 사용하세요.)
</div>

In [15]:
countries[countries["capital"].str.contains("am")]

                population    area    capital     density  density_ratio
country
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

# 영화리뷰 데이터에서 자료 찾기

movie_title_data.tsv 읽어오기

https://drive.google.com/file/d/1cvBtLVyfhfodJK-BXWqBLcopyus9HOIc/view?usp=sharing

In [129]:
titles2 = pd.read_csv("./data/movie_title_data.tsv", low_memory=False, delimiter="\t")
titles2

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
8407394,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2010,\N,\N,"Action,Drama,Family"
8407395,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
8407396,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
8407397,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
8407398,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

In [130]:
titles2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         object
 5   startYear       object
 6   endYear         object
 7   runtimeMinutes  object
 8   genres          object
dtypes: object(9)
memory usage: 577.3+ MB

In [135]:
titles2['startYear'].unique()

array(['1894', '1892', '1893', '1895', '1896', '1898', '1897', '1900',
       '1899', '1901', '1902', '1903', '1905', '1904', '1912', '1907',
       '1906', '1908', '1910', '1909', '1914', '1911', '1913', '1915',
       '1919', '1916', '1917', '1918', '1936', '1925', '1920', '1922',
       '1921', '1923', '2019', '1924', '1928', '1926', '1927', '1929',
       '2000', '1993', '1935', '2014', '1930', '1942', '1934', '1931',
       '1932', '1939', '1937', '1933', '1950', '1938', '1951', '1945',
       '1946', '1996', '1940', '1944', '1949', '1947', '1941', '1952',
       '1970', '1957', '1943', '1959', '1948', '2001', '1953', '2008',
       '1954', '1965', '1983', '1980', '1973', '1961', '1995', '1955',
       '1962', '1958', '1956', '1977', '1960', '1964', '1967', '1968',
       '1963', '1986', '1971', '1969', '1972', '1966', '2021', '2002',
       '1976', '1990', '2020', '1979', '1974', '1978', '1981', '1988',
       '1975', '1989', '1985', '\\N', '2009', '1987', '2010', '2018',
       '2007', '1984', '1982', '1992', '1991', '1994', '1999', '2005',
       '2004', '1998', '1997', '2017', '2013', '2016', '2006', '2003',
       '2012', '2015', '2011', '1891', '1888', '1890', '2022', '1889',
       '2023', '2024', '2025', '2027', '2026', '2028', '1878', '1877',
       '1882', '1881', '1887', '1874', '1883', '1885'], dtype=object)

In [17]:
titles.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   tconst          8407399 non-null  object
 1   titleType       8407399 non-null  object
 2   primaryTitle    8407385 non-null  object
 3   originalTitle   8407385 non-null  object
 4   isAdult         8407399 non-null  object
 5   startYear       8407399 non-null  object
 6   endYear         8407399 non-null  object
 7   runtimeMinutes  8407399 non-null  object
 8   genres          8407389 non-null  object
dtypes: object(9)
memory usage: 577.3+ MB

In [18]:
titles.isna().sum()

tconst             0
titleType          0
primaryTitle      14
originalTitle     14
isAdult            0
startYear          0
endYear            0
runtimeMinutes     0
genres            10
dtype: int64

In [19]:
# print(type(titles[titles['startYear'].isna()]['startYear'][0]))

In [20]:
# titles['startYear'] = titles['startYear'].astype("float16")
# titles['startYear']

In [21]:
import numpy as np

In [31]:
titles.loc[titles['startYear'] == "\\N", 'startYear'] = "0"

In [32]:
titles['startYear'] = titles['startYear'].apply(str)

In [33]:
titles['startYear'].unique()

array(['1894', '1892', '1893', '1895', '1896', '1898', '1897', '1900',
       '1899', '1901', '1902', '1903', '1905', '1904', '1912', '1907',
       '1906', '1908', '1910', '1909', '1914', '1911', '1913', '1915',
       '1919', '1916', '1917', '1918', '1936', '1925', '1920', '1922',
       '1921', '1923', '2019', '1924', '1928', '1926', '1927', '1929',
       '2000', '1993', '1935', '2014', '1930', '1942', '1934', '1931',
       '1932', '1939', '1937', '1933', '1950', '1938', '1951', '1945',
       '1946', '1996', '1940', '1944', '1949', '1947', '1941', '1952',
       '1970', '1957', '1943', '1959', '1948', '2001', '1953', '2008',
       '1954', '1965', '1983', '1980', '1973', '1961', '1995', '1955',
       '1962', '1958', '1956', '1977', '1960', '1964', '1967', '1968',
       '1963', '1986', '1971', '1969', '1972', '1966', '2021', '2002',
       '1976', '1990', '2020', '1979', '1974', '1978', '1981', '1988',
       '1975', '1989', '1985', '0', '2009', '1987', '2010', '2018',
       '2007', '1984', '1982', '1992', '1991', '1994', '1999', '2005',
       '2004', '1998', '1997', '2017', '2013', '2016', '2006', '2003',
       '2012', '2015', '2011', '1891', '1888', '1890', '2022', '1889',
       '2023', '2024', '2025', '2027', '2026', '2028', '1878', '1877',
       '1882', '1881', '1887', '1874', '1883', '1885'], dtype=object)

In [34]:
titles['startYear'] = titles['startYear'].apply("int16")

In [35]:
titles

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
8407394,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2010,\N,\N,"Action,Drama,Family"
8407395,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,\N,\N,"Action,Drama,Family"
8407396,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,\N,\N,"Action,Drama,Family"
8407397,tt9916856,short,The Wind,The Wind,0,2015,\N,27,Short
8407398,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,\N,10,"Adventure,Animation,Comedy"

<div class="alert alert-success">
    <b>EXERCISE 08</b>: titles 데이터프레임에는 몇 개의 영화가 기록되어 있나요?
</div>

In [36]:
len(titles)

8407399

<div class="alert alert-success">
    <b>EXERCISE 09</b>: titles에서 가장 빠른 시기에 제작된 영화 두 개를 표시하세요.  힌트: .sort_values()
</div>

In [37]:
titles[titles["startYear"] > 0].sort_values(by="startYear").head(2)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
5329521,tt3155794,short,Passage de Venus,Passage de Venus,0,1874,\N,1,"Documentary,Short"
3488807,tt14495706,short,La Rosace Magique,La Rosace Magique,0,1877,\N,1,"Animation,Short"

<div class="alert alert-success">
    <b>EXERCISE 10</b>: 제목(title)이 "Hamlet"인 영화는 몇 개가 있나요?
</div>

In [38]:
titles = titles.dropna(subset=['originalTitle', 'primaryTitle'])

In [39]:
len(titles[titles['originalTitle'].str.contains("Hamlet")])

417

<div class="alert alert-success">
    <b>EXERCISE 11</b>: 제목(title)이 "Treasure Island"인 영화를 제작년도(year)의 오름차순에 따라 표시하세요
</div>

In [40]:
titles[(titles['originalTitle'] == "Treasure Island") & (titles['startYear'] > 0)].sort_values(by='startYear')

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
2511,tt0002538,short,Treasure Island,Treasure Island,0,1912,\N,\N,"Adventure,Short"
5032142,tt2440348,short,Treasure Island,Treasure Island,0,1913,\N,\N,"Short,Thriller"
9589,tt0009721,movie,Treasure Island,Treasure Island,0,1917,\N,60,Adventure
11620,tt0011785,movie,Treasure Island,Treasure Island,0,1920,\N,76,Adventure
25459,tt0025907,movie,Treasure Island,Treasure Island,0,1934,\N,110,"Adventure,Family"
...,...,...,...,...,...,...,...,...,...
7423990,tt7821190,tvEpisode,Treasure Island,Treasure Island,0,2018,\N,\N,"Action,Adventure,Animation"
2208762,tt12185946,tvEpisode,Treasure Island,Treasure Island,0,2019,\N,\N,\N
6917550,tt6727462,tvEpisode,Treasure Island,Treasure Island,0,2019,\N,71,"Drama,Fantasy,Mystery"
1431503,tt10815740,tvEpisode,Treasure Island,Treasure Island,0,2019,\N,\N,Comedy
3809301,tt15075064,tvEpisode,Treasure Island,Treasure Island,0,2021,\N,\N,"Animation,Comedy"

<div class="alert alert-success">
    <b>EXERCISE 12</b>: 1950년에서 1959년 사이 몇 개의 영화가 만들어졌나요?(1950 <= 제작년도 <= 1959)
</div>

In [41]:
len(titles[(titles['startYear'] >= 1950) & (titles['startYear'] <= 1959)])

118649

# 타이타닉 자료에서 그룹별 연산하기

원격 DB에 접속해서 titanic 데이터베이스 안에 있는 p_info, t_info, survived 테이블을 불러와 합치고 아래의 문제를 풀어보세요.<br>
<id:kict00, pw:kict00, ip:221.155.18.165:3306, db:titanic>

In [42]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [43]:
engine = create_engine("mysql+pymysql://kict20:kict20@221.155.18.165:3306/titanic")
conn = engine.connect()
passenger = pd.read_sql("p_info", con=conn)
ticket = pd.read_sql("t_info", con=conn)
surv = pd.read_sql("survived", con=conn)
conn.close()
display(passenger)
display(ticket)
display(surv)

,PassengerId,Name,Sex,Age,SibSp,Parch
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,5,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0

     PassengerId            Ticket  Pclass     Fare Cabin Embarked
0              1         A/5 21171       3   7.2500  None        S
1              2          PC 17599       1  71.2833   C85        C
2              3  STON/O2. 3101282       3   7.9250  None        S
3              4            113803       1  53.1000  C123        S
4              5            373450       3   8.0500  None        S
..           ...               ...     ...      ...   ...      ...
886          887            211536       2  13.0000  None        S
887          888            112053       1  30.0000   B42        S
888          889        W./C. 6607       3  23.4500  None        S
889          890            111369       1  30.0000  C148        C
890          891            370376       3   7.7500  None        Q

[891 rows x 6 columns]

     PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]

In [44]:
passenger = passenger.set_index("PassengerId")
ticket = ticket.set_index("PassengerId")
surv = surv.set_index("PassengerId")

In [45]:
data = passenger.join(ticket)
data = data.join(surv)
data

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0
888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0
890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

<div class="alert alert-success">
    <b>EXERCISE 13</b>: 데이터의 상위 5개 행을 출력하세요.
</div>

In [46]:
data.head()

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0

<div class="alert alert-success">
    <b>EXERCISE 14</b>: 데이터의 정보(info)를 출력하세요.
</div>

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      891 non-null    object
 1   Sex       891 non-null    object
 2   Age       714 non-null    float64
 3   SibSp     891 non-null    int64
 4   Parch     891 non-null    int64
 5   Ticket    891 non-null    object
 6   Pclass    891 non-null    int64
 7   Fare      891 non-null    float64
 8   Cabin     204 non-null    object
 9   Embarked  889 non-null    object
 10  Survived  891 non-null    int64
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

<div class="alert alert-success">
    <b>EXERCISE 15</b>: 데이터의 기술통계(describe)를 확인하세요.
</div>

In [48]:
data.describe()

              Age       SibSp       Parch      Pclass        Fare    Survived
count  714.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    29.699118    0.523008    0.381594    2.308642   32.204208    0.383838
std     14.526497    1.102743    0.806057    0.836071   49.693429    0.486592
min      0.420000    0.000000    0.000000    1.000000    0.000000    0.000000
25%     20.125000    0.000000    0.000000    2.000000    7.910400    0.000000
50%     28.000000    0.000000    0.000000    3.000000   14.454200    0.000000
75%     38.000000    1.000000    0.000000    3.000000   31.000000    1.000000
max     80.000000    8.000000    6.000000    3.000000  512.329200    1.000000

<div class="alert alert-success">
    <b>EXERCISE 16</b>: 처음 100명의 데이터를 출력하세요.
</div>

In [50]:
data.iloc[:100, :]

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...
96,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,3,8.0500,None,S,0
97,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,1,34.6542,A5,C,0
98,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,1,63.3583,D10 D12,C,1
99,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,2,23.0000,None,S,1
100,"Kantor, Mr. Sinai",male,34.0,1,0,244367,2,26.0000,None,S,0

<div class="alert alert-success">
    <b>EXERCISE 17</b>: 인덱스가 10~20인 데이터를 출력하세요.
</div>

In [51]:
data.loc[10:20, :]

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,2,30.0708,None,C,1
11,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,3,16.7000,G6,S,1
12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
13,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,3,8.0500,None,S,0
14,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,3,31.2750,None,S,0
15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,3,7.8542,None,S,0
16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,2,16.0000,None,S,1
17,"Rice, Master. Eugene",male,2.0,4,1,382652,3,29.1250,None,Q,0
18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,None,S,1
19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,3,18.0000,None,S,0
20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,None,C,1

<div class="alert alert-success">
    <b>EXERCISE</b>: 컬럼 이름을 모두 출력하세요.
</div>

In [52]:
data.columns

Index(['Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Pclass', 'Fare',
       'Cabin', 'Embarked', 'Survived'],
      dtype='object')

<div class="alert alert-success">
    <b>EXERCISE 18</b>: 데이터의 shape를 확인하세요.
</div>

In [53]:
data.shape

(891, 11)

<div class="alert alert-success">
    <b>EXERCISE 19</b>: 'Age' 컬럼의 평균을 구하세요.
</div>

In [54]:
data['Age'].mean()

np.float64(29.69911764705882)

<div class="alert alert-success">
    <b>EXERCISE 20</b>: 'Survived' 컬럼의 고유값을 확인하세요.
</div>

In [55]:
data['Survived'].unique()

array([0, 1])

<div class="alert alert-success">
    <b>EXERCISE 21</b>: 나이가 30 이상인 승객만 출력하세요.
</div>

In [56]:
data[data['Age'] >= 30]

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
7,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,1,51.8625,E46,S,0
12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
...,...,...,...,...,...,...,...,...,...,...,...
874,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,3,9.0000,None,S,0
880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
882,"Markun, Mr. Johann",male,33.0,0,0,349257,3,7.8958,None,S,0
886,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,3,29.1250,None,Q,0
891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

<div class="alert alert-success">
    <b>EXERCISE 22</b>: 성별이 'female'이고 생존한 승객만 출력하세요.
</div>

In [57]:
data[(data['Sex'] == "female") & (data['Survived'] == 1)]

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,3,11.1333,None,S,1
10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,2,30.0708,None,C,1
...,...,...,...,...,...,...,...,...,...,...,...
875,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,2,24.0000,None,C,1
876,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,3,7.2250,None,C,1
880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,2,26.0000,None,S,1
888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1

<div class="alert alert-success">
    <b>EXERCISE 23</b>: 나이가 10살 이하이고 요금이 20 이상인 승객을 출력하세요.
</div>

In [58]:
data[(data['Age'] <= 10) & (data['Fare'] >= 20)]

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
8,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,3,21.0750,None,S,0
17,"Rice, Master. Eugene",male,2.00,4,1,382652,3,29.1250,None,Q,0
25,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,3,21.0750,None,S,0
44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,2,41.5792,None,C,1
51,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,3,39.6875,None,S,0
59,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,2,27.7500,None,S,1
64,"Skoog, Master. Harald",male,4.00,3,2,347088,3,27.9000,None,S,0
79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,None,S,1
120,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,3,31.2750,None,S,0
148,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,W./C. 6608,3,34.3750,None,S,0
165,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,3,39.6875,None,S,0
166,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,3,20.5250,None,S,1
172,"Rice, Master. Arthur",male,4.00,4,1,382652,3,29.1250,None,Q,0
183,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,3,31.3875,None,S,0
184,"Becker, Master. Richard F",male,1.00,2,1,230136,2,39.0000,F4,S,1
185,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,3,22.0250,None,S,1
194,"Navratil, Master. Michel M",male,3.00,1,1,230080,2,26.0000,F2,S,1
234,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,3,31.3875,None,S,1
238,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,2,26.2500,None,S,1
262,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,3,31.3875,None,S,1
279,"Rice, Master. Eric",male,7.00,4,1,382652,3,29.1250,None,Q,0
298,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,1,151.5500,C22 C26,S,0
306,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,1,151.5500,C22 C26,S,1
341,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,2,26.0000,F2,S,1
375,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,3,21.0750,None,S,0
387,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,3,46.9000,None,S,0
420,"Van Impe, Miss. Catharina",female,10.00,0,2,345773,3,24.1500,None,S,0
446,"Dodge, Master. Washington",male,4.00,0,2,33638,1,81.8583,A34,S,1
481,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,3,46.9000,None,S,0
531,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,2,26.0000,None,S,1
536,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,2,26.2500,None,S,1
542,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,3,31.2750,None,S,0
550,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,2,36.7500,None,S,1
619,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,2,39.0000,F4,S,1
635,"Skoog, Miss. Mabel",female,9.00,3,2,347088,3,27.9000,None,S,0
643,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,3,27.9000,None,S,0
721,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,2,33.0000,None,S,1
751,"Wells, Miss. Joan",female,4.00,1,1,29103,2,23.0000,None,S,1
788,"Rice, Master. George Hugh",male,8.00,4,1,382652,3,29.1250,None,Q,0
789,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,3,20.5750,None,S,1
814,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,3,31.2750,None,S,0
820,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,3,27.9000,None,S,0
825,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,3,39.6875,None,S,0
828,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,2,37.0042,None,C,1
851,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,3,31.2750,None,S,0

<div class="alert alert-success">
    <b>EXERCISE 24</b>: 나이가 결측치인 데이터를 출력하세요.
</div>

In [60]:
data[data['Age'].isna() == True]

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
6,"Moran, Mr. James",male,NaN,0,0,330877,3,8.4583,None,Q,0
18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,None,S,1
20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,None,C,1
27,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,3,7.2250,None,C,0
29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,3,7.8792,None,Q,1
...,...,...,...,...,...,...,...,...,...,...,...
860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,None,C,0
864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,None,S,0
869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,None,S,0
879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,None,S,0
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0

<div class="alert alert-success">
    <b>EXERCISE 25</b>: 나이를 기준으로 오름차순 정렬하세요.
</div>

In [61]:
data.sort_values(by='Age')

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
804,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,3,8.5167,None,C,1
756,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,2,14.5000,None,S,1
645,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,3,19.2583,None,C,1
470,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,3,19.2583,None,C,1
79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,None,S,1
...,...,...,...,...,...,...,...,...,...,...,...
860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,None,C,0
864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,None,S,0
869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,None,S,0
879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,None,S,0
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0

<div class="alert alert-success">
    <b>EXERCISE 26</b>: 요금을 기준으로 내림차순 정렬하고 상위 5명만 출력하세요.
</div>

In [64]:
data.sort_values(by='Fare', ascending=False).head()

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
680,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,1,512.3292,B51 B53 B55,C,1
259,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,1,512.3292,None,C,1
738,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,1,512.3292,B101,C,1
89,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,1,263.0000,C23 C25 C27,S,1
439,"Fortune, Mr. Mark",male,64.0,1,4,19950,1,263.0000,C23 C25 C27,S,0

<div class="alert alert-success">
    <b>EXERCISE 27</b>: 성별로 그룹화하여 생존률 평균을 구하세요.
</div>

In [65]:
data[['Sex', 'Survived']].groupby('Sex').mean()

        Survived
Sex
female  0.742038
male    0.188908

<div class="alert alert-success">
    <b>EXERCISE 28</b>: Pclass별 평균 나이를 구하세요.
</div>

In [69]:
data[['Pclass', 'Age']].groupby('Pclass').mean()

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

<div class="alert alert-success">
    <b>EXERCISE 29</b>: 'Age'에 10을 더한 값을 새로운 컬럼 'Age_plus_10'으로 추가하세요.
</div>

In [70]:
data['Age_plus_10'] = data['Age'] + 10
data

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10
PassengerId,,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0,32.0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,48.0
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1,36.0
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,45.0
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0,37.0
888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,29.0
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0,NaN
890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,36.0
891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0,42.0

<div class="alert alert-success">
    <b>EXERCISE 30</b>: 'Age'가 18 이상이면 '성인', 아니면 '미성년'으로 분류하는 컬럼을 추가하세요.
</div>

In [71]:
data['isadult'] = data['Age'].apply(lambda x: '성인' if x >= 18 else '미성년')
data

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isadult
PassengerId,,,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0,32.0,성인
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,48.0,성인
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1,36.0,성인
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,45.0,성인
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0,37.0,성인
888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,29.0,성인
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0,NaN,미성년
890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,36.0,성인
891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0,42.0,성인

<div class="alert alert-success">
    <b>EXERCISE 31</b>: 'Age'의 결측치를 평균으로 채우세요.
</div>

In [72]:
data['Age'] = data['Age'].fillna(data['Age'].mean())

<div class="alert alert-success">
    <b>EXERCISE 32</b>: 'Cabin' 컬럼의 결측치를 'Unknown'으로 채우세요.
</div>

In [77]:
cabin_na = data[data['Cabin'].isna()==True].index

In [78]:
data['Cabin'] = data['Cabin'].fillna('Unknown')
data.loc[cabin_na]

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isadult
PassengerId,,,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,32.0,성인
3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,36.0,성인
5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,45.0,성인
6,"Moran, Mr. James",male,29.699118,0,0,330877,3,8.4583,Unknown,Q,0,NaN,미성년
8,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,3,21.0750,Unknown,S,0,12.0,미성년
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,"Sutehall, Mr. Henry Jr",male,25.000000,0,0,SOTON/OQ 392076,3,7.0500,Unknown,S,0,35.0,성인
886,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,3,29.1250,Unknown,Q,0,49.0,성인
887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0,37.0,성인
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,NaN,미성년
891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0,42.0,성인

<div class="alert alert-success">
    <b>EXERCISE 33</b>: 중복된 'Ticket' 값을 제거하고 몇 개가 남는지 출력하세요.
</div>

In [82]:
ticket_dupled = data[data['Ticket'].duplicated()].index
data.loc[ticket_dupled]

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isadult
PassengerId,,,,,,,,,,,,,
25,"Palsson, Miss. Torborg Danira",female,8.000000,3,1,349909,3,21.0750,Unknown,S,0,18.0,미성년
72,"Goodwin, Miss. Lillian Amy",female,16.000000,5,2,CA 2144,3,46.9000,Unknown,S,0,26.0,미성년
89,"Fortune, Miss. Mabel Helen",female,23.000000,3,2,19950,1,263.0000,C23 C25 C27,S,1,33.0,성인
118,"Turpin, Mr. William John Robert",male,29.000000,1,0,11668,2,21.0000,Unknown,S,0,39.0,성인
120,"Andersson, Miss. Ellis Anna Maria",female,2.000000,4,2,347082,3,31.2750,Unknown,S,0,12.0,미성년
...,...,...,...,...,...,...,...,...,...,...,...,...,...
877,"Gustafsson, Mr. Alfred Ossian",male,20.000000,0,0,7534,3,9.8458,Unknown,S,0,30.0,성인
880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.000000,0,1,11767,1,83.1583,C50,C,1,66.0,성인
881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.000000,0,1,230433,2,26.0000,Unknown,S,1,35.0,성인
886,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,3,29.1250,Unknown,Q,0,49.0,성인
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,NaN,미성년

In [84]:
len(data.drop_duplicates(subset='Ticket'))

681

<div class="alert alert-success">
    <b>EXERCISE 34</b>: 'Embarked' 컬럼의 고유값과 각각의 개수를 출력하세요.
</div>

In [87]:
data['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

<div class="alert alert-success">
    <b>EXERCISE 35</b>: 인덱스를 'PassengerId'로 설정하세요.
</div>

In [89]:
data.columns

Index(['Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Pclass', 'Fare',
       'Cabin', 'Embarked', 'Survived', 'Age_plus_10', 'isadult'],
      dtype='object')

In [90]:
data = data.reset_index()
data = data.set_index("PassengerId")
data

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isadult
PassengerId,,,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,32.0,성인
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1,48.0,성인
3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,36.0,성인
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1,45.0,성인
5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0,37.0,성인
888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1,29.0,성인
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,NaN,미성년
890,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1,36.0,성인
891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0,42.0,성인

<div class="alert alert-success">
    <b>EXERCISE 36</b>: 인덱스를 초기화하세요.
</div>

In [92]:
data = data.reset_index()
data

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isadult
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,32.0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1,48.0,성인
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,36.0,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1,45.0,성인
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0,37.0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1,29.0,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,NaN,미성년
889,890,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1,36.0,성인
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0,42.0,성인

<div class="alert alert-success">
    <b>EXERCISE 37</b>: 성별과 Pclass의 생존률을 피벗 테이블로 만드세요.
</div>

In [93]:
data.pivot_table(values="Survived", index='Pclass', columns='Sex')

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

<div class="alert alert-success">
    <b>EXERCISE 38</b>: groupby()를 사용하여 각 성별(sex)의 평균 나이(age)를 구하세요.
</div>

In [94]:
data[['Sex', 'Age']].groupby('Sex').mean()

              Age
Sex
female  28.216730
male    30.505824

In [103]:
data.groupby(['Sex'])[['Age']].mean()

              Age
Sex
female  28.216730
male    30.505824

<div class="alert alert-success">
    <b>EXERCISE 39</b>: 전체 승객(passenger)의 평균 생존율을 구하세요.
</div>

In [115]:
round(data['Survived'].mean()*100)

38

In [112]:
round(data['Survived'].sum() / len(data) * 100)

38

<div class="alert alert-success">
    <b>EXERCISE 40</b>: 25세 이하 승객의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [120]:
round(data.loc[data['Age'] <= 25, 'Survived'].mean() * 100)

41

<div class="alert alert-success">
    <b>EXERCISE 41</b>: 남성의 생존율을 구하세요. 여성의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [128]:
print("남성의 생존율: ", round(data.loc[data['Sex'] == 'male', 'Survived'].mean(), 6))
print("여성의 생존율: ", round(data.loc[data['Sex'] == 'female', 'Survived'].mean(), 6))

남성의 생존율:  0.188908
여성의 생존율:  0.742038

<div class="alert alert-success">
    <b>EXERCISE 42</b>: 생존율을 구하는 함수가 작성되어 있습니다. 성별 생존율을 groupby를 활용해 구하기 위해 ?부분을 알맞게 채워주세요.
</div>

In [127]:
def survival_ratio(survived):
    return survived.sum() / len(survived)

In [74]:
data[['Sex', 'Survived']].groupby('Sex').agg(survival_ratio)

        Survived
Sex
female  0.742038
male    0.188908