In [1]:
import pandas as pd

In [2]:
# dataframe
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}
countries = pd.DataFrame(data)
countries = countries.set_index('country') # 인덱스 지정
countries

                population    area    capital
country
Belgium               11.3   30510   Brussels
France                64.3  671308      Paris
Germany               81.3  357050     Berlin
Netherlands           16.9   41526  Amsterdam
United Kingdom        64.9  244820     London

In [3]:
countries.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Belgium to United Kingdom
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  5 non-null      float64
 1   area        5 non-null      int64
 2   capital     5 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 160.0+ bytes

---

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도를 의미하는 `density` 칼럼을 추가하세요. (주의: 현재 'population' 칼럼은 100만 단위로 표기되어 있습니다)  
  
</div>

In [6]:
# countries['density'] 
countries['density']  = countries['population'] * 1000000 / countries['area']
countries

                population    area    capital     density
country
Belgium               11.3   30510   Brussels  370.370370
France                64.3  671308      Paris   95.783158
Germany               81.3  357050     Berlin  227.699202
Netherlands           16.9   41526  Amsterdam  406.973944
United Kingdom        64.9  244820     London  265.092721

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구밀도가 300을 초과하는 국가(country)의 수도(capital)과 인구(population)을 선택해주세요.  
  
</div>

In [8]:
countries.loc[countries['density'] > 300, ['capital', 'population']]

               capital  population
country
Belgium       Brussels        11.3
Netherlands  Amsterdam        16.9

In [9]:
countries[countries['density'] > 300][['capital', 'population']]

               capital  population
country
Belgium       Brussels        11.3
Netherlands  Amsterdam        16.9

<div class="alert alert-success">
    <b>EXERCISE</b>: 'density_ratio' 칼럼을 추가해주세요. (density_ratio = 인구밀도/평균 인구밀도)
</div>

In [10]:
countries['density'].mean()

np.float64(273.1838790074409)

In [12]:
countries['density_ratio'] = countries['density'] / countries['density'].mean()
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 영국(United Kingdom)의 수도(capital)를 'Cambridge'로 변경해주세요.
</div>

In [14]:
countries.loc["United Kingdom", 'capital'] = 'Cambridge'
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

In [17]:
countries.iloc[4, 2] = 'London'
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 인구 밀도가 100 초과, 300 미만인 국가들을 표시해주세요.  
</div>

In [19]:
countries[(countries['density'] > 100) & (countries['density'] < 300)]

                population    area capital     density  density_ratio
country
Germany               81.3  357050  Berlin  227.699202       0.833502
United Kingdom        64.9  244820  London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도가 7글자 이상인 국가들을 표시해주세요. (힌트: string의 len( )를 사용하세요.)
</div>

In [23]:
countries[countries['capital'].str.len() >= 7]

             population   area    capital     density  density_ratio
country
Belgium            11.3  30510   Brussels  370.370370       1.355755
Netherlands        16.9  41526  Amsterdam  406.973944       1.489744

In [26]:
countries[countries['capital'].apply(len) >= 7]

             population   area    capital     density  density_ratio
country
Belgium            11.3  30510   Brussels  370.370370       1.355755
Netherlands        16.9  41526  Amsterdam  406.973944       1.489744

In [30]:
countries['cap_len'] = countries['capital'].apply(len)
countries

,population,area,capital,density,density_ratio,cap_len
country,,,,,,
Belgium,11.3,30510,Brussels,370.370370,1.355755,8
France,64.3,671308,Paris,95.783158,0.350618,5
Germany,81.3,357050,Berlin,227.699202,0.833502,6
Netherlands,16.9,41526,Amsterdam,406.973944,1.489744,9
United Kingdom,64.9,244820,London,265.092721,0.970382,6

In [32]:
countries[countries['cap_len'] >= 7]

             population   area    capital     density  density_ratio  cap_len
country
Belgium            11.3  30510   Brussels  370.370370       1.355755        8
Netherlands        16.9  41526  Amsterdam  406.973944       1.489744        9

<div class="alert alert-success">
    <b>EXERCISE</b>: 수도에 'am' 이 포함되는 국가들을 표시해주세요. (힌트: string의 contains( )를 사용하세요.)
</div>

In [34]:
countries[countries['capital'].str.contains("am")]

             population   area    capital     density  density_ratio  cap_len
country
Netherlands        16.9  41526  Amsterdam  406.973944       1.489744        9

# 영화리뷰 데이터에서 자료 찾기

movie_title_data.tsv 읽어오기

https://drive.google.com/file/d/1cvBtLVyfhfodJK-BXWqBLcopyus9HOIc/view?usp=sharing

In [192]:
titles = pd.read_csv("./data/movie_title_data.tsv", delimiter="\t")

C:\Users\haram\AppData\Local\Temp\ipykernel_27976\3235376442.py:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  titles = pd.read_csv("./data/movie_title_data.tsv", delimiter="\t")

In [193]:
titles.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"

In [197]:
titles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         object
 5   startYear       object
 6   endYear         object
 7   runtimeMinutes  object
 8   genres          object
dtypes: object(9)
memory usage: 577.3+ MB

In [203]:
titles['startYear'].apply(str)

array([1894, 1892, 1893, 1895, 1896, 1898, 1897, 1900, 1899, 1901, 1902,
       1903, 1905, 1904, 1912, 1907, 1906, 1908, 1910, 1909, 1914, 1911,
       1913, 1915, 1919, 1916, 1917, 1918, 1936, 1925, 1920, 1922, 1921,
       1923, 2019, 1924, 1928, 1926, 1927, 1929, 2000, 1993, 1935, 2014,
       1930, 1942, 1934, 1931, 1932, 1939, 1937, 1933, 1950, 1938, 1951,
       1945, 1946, 1996, 1940, 1944, 1949, 1947, 1941, 1952, 1970, 1957,
       1943, 1959, 1948, 2001, 1953, 2008, 1954, 1965, 1983, 1980, 1973,
       1961, 1995, 1955, 1962, 1958, 1956, 1977, 1960, 1964, 1967, 1968,
       1963, 1986, 1971, 1969, 1972, 1966, 2021, 2002, 1976, 1990, 2020,
       1979, 1974, 1978, 1981, 1988, 1975, 1989, '1971', '1972', '1970',
       '1974', '1973', '1976', '1969', '1968', '1985', '\\N', '1981',
       '2009', '1980', '1986', '1965', '1987', '1975', '1978', '1967',
       '1990', '1977', '2010', '2018', '1979', '2007', '1989', '1983',
       '1988', '1984', '1966', '1982', '1992', '1991', '1952', '1963',
       '2001', '1961', '1994', '1993', '1964', '1957', '1999', '1995',
       '2019', '2005', '1953', '2004', '1998', '1947', '2002', '1997',
       '1959', '1996', '2017', '2000', '1945', '1956', '2021', '2013',
       '2016', '2006', '2003', '1955', '1949', '2008', '1960', '1930',
       '1938', '1929', '1944', '1935', '1962', '1919', '1951', '1914',
       '1954', '1958', '1907', '1942', '1918', '1943', '1921', '1927',
       '1941', '1939', '1940', '1937', '1950', '1946', '1916', '1948',
       '1934', '1912', '1911', '1926', '1933', '1936', '1925', '1932',
       '1928', '1917', '1920', '1931', '1913', '1895', '1922', '1923',
       '1924', '1900', '1908', '1915', '1910', '1897', '1905', '1909',
       '1903', '1902', '1901', '1906', '1904', '1898', '1896', '1899',
       '2012', '2014', '2020', '2015', '2011', '1894', '1892', '1893',
       '1891', '1888', '1890', '2022', '1889', '2023', '2024', '2025',
       '2027', '2026', '2028', '1878', '1877', '1882', '1881', '1887',
       '1874', '1883', '1885'], dtype=object)

In [199]:
sy_unique = titles['startYear'].unique()

In [202]:
sy_unique[106]

'1971'

In [201]:
for idx, i in enumerate(sy_unique):
    print(idx, i, type(i))

0 1894 <class 'int'>
1 1892 <class 'int'>
2 1893 <class 'int'>
3 1895 <class 'int'>
4 1896 <class 'int'>
5 1898 <class 'int'>
6 1897 <class 'int'>
7 1900 <class 'int'>
8 1899 <class 'int'>
9 1901 <class 'int'>
10 1902 <class 'int'>
11 1903 <class 'int'>
12 1905 <class 'int'>
13 1904 <class 'int'>
14 1912 <class 'int'>
15 1907 <class 'int'>
16 1906 <class 'int'>
17 1908 <class 'int'>
18 1910 <class 'int'>
19 1909 <class 'int'>
20 1914 <class 'int'>
21 1911 <class 'int'>
22 1913 <class 'int'>
23 1915 <class 'int'>
24 1919 <class 'int'>
25 1916 <class 'int'>
26 1917 <class 'int'>
27 1918 <class 'int'>
28 1936 <class 'int'>
29 1925 <class 'int'>
30 1920 <class 'int'>
31 1922 <class 'int'>
32 1921 <class 'int'>
33 1923 <class 'int'>
34 2019 <class 'int'>
35 1924 <class 'int'>
36 1928 <class 'int'>
37 1926 <class 'int'>
38 1927 <class 'int'>
39 1929 <class 'int'>
40 2000 <class 'int'>
41 1993 <class 'int'>
42 1935 <class 'int'>
43 2014 <class 'int'>
44 1930 <class 'int'>
45 1942 <class 'int'>
46 1934 <class 'int'>
47 1931 <class 'int'>
48 1932 <class 'int'>
49 1939 <class 'int'>
50 1937 <class 'int'>
51 1933 <class 'int'>
52 1950 <class 'int'>
53 1938 <class 'int'>
54 1951 <class 'int'>
55 1945 <class 'int'>
56 1946 <class 'int'>
57 1996 <class 'int'>
58 1940 <class 'int'>
59 1944 <class 'int'>
60 1949 <class 'int'>
61 1947 <class 'int'>
62 1941 <class 'int'>
63 1952 <class 'int'>
64 1970 <class 'int'>
65 1957 <class 'int'>
66 1943 <class 'int'>
67 1959 <class 'int'>
68 1948 <class 'int'>
69 2001 <class 'int'>
70 1953 <class 'int'>
71 2008 <class 'int'>
72 1954 <class 'int'>
73 1965 <class 'int'>
74 1983 <class 'int'>
75 1980 <class 'int'>
76 1973 <class 'int'>
77 1961 <class 'int'>
78 1995 <class 'int'>
79 1955 <class 'int'>
80 1962 <class 'int'>
81 1958 <class 'int'>
82 1956 <class 'int'>
83 1977 <class 'int'>
84 1960 <class 'int'>
85 1964 <class 'int'>
86 1967 <class 'int'>
87 1968 <class 'int'>
88 1963 <class 'int'>
89 1986 <class 'int'>
90 1971 <class 'int'>
91 1969 <class 'int'>
92 1972 <class 'int'>
93 1966 <class 'int'>
94 2021 <class 'int'>
95 2002 <class 'int'>
96 1976 <class 'int'>
97 1990 <class 'int'>
98 2020 <class 'int'>
99 1979 <class 'int'>
100 1974 <class 'int'>
101 1978 <class 'int'>
102 1981 <class 'int'>
103 1988 <class 'int'>
104 1975 <class 'int'>
105 1989 <class 'int'>
106 1971 <class 'str'>
107 1972 <class 'str'>
108 1970 <class 'str'>
109 1974 <class 'str'>
110 1973 <class 'str'>
111 1976 <class 'str'>
112 1969 <class 'str'>
113 1968 <class 'str'>
114 1985 <class 'str'>
115 \N <class 'str'>
116 1981 <class 'str'>
117 2009 <class 'str'>
118 1980 <class 'str'>
119 1986 <class 'str'>
120 1965 <class 'str'>
121 1987 <class 'str'>
122 1975 <class 'str'>
123 1978 <class 'str'>
124 1967 <class 'str'>
125 1990 <class 'str'>
126 1977 <class 'str'>
127 2010 <class 'str'>
128 2018 <class 'str'>
129 1979 <class 'str'>
130 2007 <class 'str'>
131 1989 <class 'str'>
132 1983 <class 'str'>
133 1988 <class 'str'>
134 1984 <class 'str'>
135 1966 <class 'str'>
136 1982 <class 'str'>
137 1992 <class 'str'>
138 1991 <class 'str'>
139 1952 <class 'str'>
140 1963 <class 'str'>
141 2001 <class 'str'>
142 1961 <class 'str'>
143 1994 <class 'str'>
144 1993 <class 'str'>
145 1964 <class 'str'>
146 1957 <class 'str'>
147 1999 <class 'str'>
148 1995 <class 'str'>
149 2019 <class 'str'>
150 2005 <class 'str'>
151 1953 <class 'str'>
152 2004 <class 'str'>
153 1998 <class 'str'>
154 1947 <class 'str'>
155 2002 <class 'str'>
156 1997 <class 'str'>
157 1959 <class 'str'>
158 1996 <class 'str'>
159 2017 <class 'str'>
160 2000 <class 'str'>
161 1945 <class 'str'>
162 1956 <class 'str'>
163 2021 <class 'str'>
164 2013 <class 'str'>
165 2016 <class 'str'>
166 2006 <class 'str'>
167 2003 <class 'str'>
168 1955 <class 'str'>
169 1949 <class 'str'>
170 2008 <class 'str'>
171 1960 <class 'str'>
172 1930 <class 'str'>
173 1938 <class 'str'>
174 1929 <class 'str'>
175 1944 <class 'str'>
176 1935 <class 'str'>
177 1962 <class 'str'>
178 1919 <class 'str'>
179 1951 <class 'str'>
180 1914 <class 'str'>
181 1954 <class 'str'>
182 1958 <class 'str'>
183 1907 <class 'str'>
184 1942 <class 'str'>
185 1918 <class 'str'>
186 1943 <class 'str'>
187 1921 <class 'str'>
188 1927 <class 'str'>
189 1941 <class 'str'>
190 1939 <class 'str'>
191 1940 <class 'str'>
192 1937 <class 'str'>
193 1950 <class 'str'>
194 1946 <class 'str'>
195 1916 <class 'str'>
196 1948 <class 'str'>
197 1934 <class 'str'>
198 1912 <class 'str'>
199 1911 <class 'str'>
200 1926 <class 'str'>
201 1933 <class 'str'>
202 1936 <class 'str'>
203 1925 <class 'str'>
204 1932 <class 'str'>
205 1928 <class 'str'>
206 1917 <class 'str'>
207 1920 <class 'str'>
208 1931 <class 'str'>
209 1913 <class 'str'>
210 1895 <class 'str'>
211 1922 <class 'str'>
212 1923 <class 'str'>
213 1924 <class 'str'>
214 1900 <class 'str'>
215 1908 <class 'str'>
216 1915 <class 'str'>
217 1910 <class 'str'>
218 1897 <class 'str'>
219 1905 <class 'str'>
220 1909 <class 'str'>
221 1903 <class 'str'>
222 1902 <class 'str'>
223 1901 <class 'str'>
224 1906 <class 'str'>
225 1904 <class 'str'>
226 1898 <class 'str'>
227 1896 <class 'str'>
228 1899 <class 'str'>
229 2012 <class 'str'>
230 2014 <class 'str'>
231 2020 <class 'str'>
232 2015 <class 'str'>
233 2011 <class 'str'>
234 1894 <class 'str'>
235 1892 <class 'str'>
236 1893 <class 'str'>
237 1891 <class 'str'>
238 1888 <class 'str'>
239 1890 <class 'str'>
240 2022 <class 'str'>
241 1889 <class 'str'>
242 2023 <class 'str'>
243 2024 <class 'str'>
244 2025 <class 'str'>
245 2027 <class 'str'>
246 2026 <class 'str'>
247 2028 <class 'str'>
248 1878 <class 'str'>
249 1877 <class 'str'>
250 1882 <class 'str'>
251 1881 <class 'str'>
252 1887 <class 'str'>
253 1874 <class 'str'>
254 1883 <class 'str'>
255 1885 <class 'str'>

In [198]:
for i in titles['startYear'][100:200]:
    print(i, type(i))

1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1896 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1896 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1900 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1896 <class 'int'>
1897 <class 'int'>
1897 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1896 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1899 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>
1898 <class 'int'>

In [53]:
titles.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   tconst          8407399 non-null  object
 1   titleType       8407399 non-null  object
 2   primaryTitle    8407385 non-null  object
 3   originalTitle   8407385 non-null  object
 4   isAdult         8407399 non-null  object
 5   startYear       8407399 non-null  object
 6   endYear         8407399 non-null  object
 7   runtimeMinutes  8407399 non-null  object
 8   genres          8407389 non-null  object
dtypes: object(9)
memory usage: 577.3+ MB

<div class="alert alert-success">
    <b>EXERCISE</b>: titles 데이터프레임에는 몇 개의 영화가 기록되어 있나요?
</div>

In [54]:
len(titles)

8407399

<div class="alert alert-success">
    <b>EXERCISE</b>: titles에서 가장 빠른 시기에 제작된 영화 두 개를 표시하세요.  힌트: .sort_values()
</div>

In [55]:
titles['startYear'].astype("int")

ValueError: invalid literal for int() with base 10: '\\N'

In [56]:
newline_index = titles[titles['startYear'] == "\\N"].index

In [58]:
titles.loc[titles['startYear'] == "\\N", 'startYear'] = 0

In [59]:
titles.loc[newline_index]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
65766,tt0067098,tvEpisode,Willi Forst,Willi Forst,0,0,\N,55,\N
69710,tt0071158,tvEpisode,The Arcata Promise,The Arcata Promise,0,0,\N,\N,Drama
71895,tt0073399,movie,Atlantic City Jackpot,The Money,0,0,\N,88,"Action,Drama"
83818,tt0085677,tvEpisode,High Country,High Country,0,0,\N,\N,Sport
88271,tt0090238,movie,Unternehmen Geigenkasten,Unternehmen Geigenkasten,0,0,\N,82,"Crime,Family"
...,...,...,...,...,...,...,...,...,...
8407285,tt9916616,short,Terror,Terror,0,0,\N,13,"Drama,Short"
8407287,tt9916620,movie,The Copeland Case,The Copeland Case,0,0,\N,\N,Drama
8407301,tt9916652,short,Untitled well- being Documentary,Untitled well- being Documentary,0,0,\N,\N,Short
8407307,tt9916664,short,Untitled Land Army Girls Documentary,Untitled Land Army Girls Documentary,0,0,\N,\N,Short
8407325,tt9916702,short,Loving London: The Playground,Loving London: The Playground,0,0,\N,\N,"Drama,Short"

In [61]:
titles['startYear'] = titles['startYear'].astype(int)

In [62]:
titles['startYear'].dtype

dtype('int64')

In [66]:
titles[titles['startYear'] != 0].sort_values(by='startYear').head(2)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
5329521,tt3155794,short,Passage de Venus,Passage de Venus,0,1874,\N,1,"Documentary,Short"
3488807,tt14495706,short,La Rosace Magique,La Rosace Magique,0,1877,\N,1,"Animation,Short"

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(originalTitle)이 "Hamlet"인 영화는 몇 개가 있나요?
</div>

In [69]:
titles['originalTitle'].isna().sum()

np.int64(14)

In [77]:
no_na_titles = titles[titles['originalTitle'].isna() == False]
len(no_na_titles[no_na_titles['originalTitle'].str.contains("Hamlet")])

417

In [78]:
no_na_titles[no_na_titles['originalTitle'] == "Hamlet"]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
594,tt0000598,short,"Hamlet, Prince of Denmark",Hamlet,0,1907,\N,10,"Drama,Short"
876,tt0000886,movie,"Hamlet, Prince of Denmark",Hamlet,0,1910,\N,\N,Drama
1228,tt0001240,movie,Hamlet,Hamlet,0,1911,\N,\N,Drama
1229,tt0001241,short,Hamlet,Hamlet,0,1910,\N,20,"Drama,Short"
1230,tt0001242,short,Hamlet,Hamlet,0,1908,\N,\N,"Drama,Short"
...,...,...,...,...,...,...,...,...,...
7347169,tt7656792,tvEpisode,Hamlet,Hamlet,0,2017,\N,\N,Animation
7413345,tt7798632,movie,Hamlet,Hamlet,0,0,\N,\N,Comedy
7476376,tt7934018,tvMovie,Hamlet,Hamlet,0,1983,\N,\N,Drama
7609545,tt8219328,tvMovie,Hamlet,Hamlet,0,2018,\N,191,Drama
8306453,tt9703966,movie,Hamlet,Hamlet,0,0,\N,\N,Drama

<div class="alert alert-success">
    <b>EXERCISE</b>: 제목(originalTitle)이 "Treasure Island"인 영화를 제작년도(startYear)의 오름차순에 따라 표시하세요
</div>

In [82]:
titles[(titles['originalTitle'] == "Treasure Island") & (titles['startYear'] != 0)].sort_values(by="startYear")

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
2511,tt0002538,short,Treasure Island,Treasure Island,0,1912,\N,\N,"Adventure,Short"
5032142,tt2440348,short,Treasure Island,Treasure Island,0,1913,\N,\N,"Short,Thriller"
9589,tt0009721,movie,Treasure Island,Treasure Island,0,1917,\N,60,Adventure
11620,tt0011785,movie,Treasure Island,Treasure Island,0,1920,\N,76,Adventure
25459,tt0025907,movie,Treasure Island,Treasure Island,0,1934,\N,110,"Adventure,Family"
...,...,...,...,...,...,...,...,...,...
7423990,tt7821190,tvEpisode,Treasure Island,Treasure Island,0,2018,\N,\N,"Action,Adventure,Animation"
2208762,tt12185946,tvEpisode,Treasure Island,Treasure Island,0,2019,\N,\N,\N
1431503,tt10815740,tvEpisode,Treasure Island,Treasure Island,0,2019,\N,\N,Comedy
6917550,tt6727462,tvEpisode,Treasure Island,Treasure Island,0,2019,\N,71,"Drama,Fantasy,Mystery"
3809301,tt15075064,tvEpisode,Treasure Island,Treasure Island,0,2021,\N,\N,"Animation,Comedy"

<div class="alert alert-success">
    <b>EXERCISE</b>: 1950년에서 1959년 사이 몇 개의 영화가 만들어졌나요?(1950 <= 제작년도 <= 1959)
</div>

In [84]:
len(titles[(titles['startYear'] >= 1950) & (titles['startYear'] <= 1959)])

118649

# 타이타닉 자료에서 그룹별 연산하기

원격 DB에 접속해서 titanic 데이터베이스 안에 있는 p_info, t_info, survived 테이블을 불러와 합치고 아래의 문제를 풀어보세요.<br>
<id:kict00, pw:kict00, ip:221.155.18.165:3306, db:titanic>

In [2]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb
engine = create_engine("mysql+pymysql://kict20:kict20@221.155.18.165:3306/titanic")
conn = engine.connect()
p_info = pd.read_sql("p_info", con=conn)
t_info = pd.read_sql("t_info", con=conn)
survived = pd.read_sql("survived", con=conn)
conn.close()

In [86]:
p_info

,PassengerId,Name,Sex,Age,SibSp,Parch
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,5,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0

In [87]:
t_info

     PassengerId            Ticket  Pclass     Fare Cabin Embarked
0              1         A/5 21171       3   7.2500  None        S
1              2          PC 17599       1  71.2833   C85        C
2              3  STON/O2. 3101282       3   7.9250  None        S
3              4            113803       1  53.1000  C123        S
4              5            373450       3   8.0500  None        S
..           ...               ...     ...      ...   ...      ...
886          887            211536       2  13.0000  None        S
887          888            112053       1  30.0000   B42        S
888          889        W./C. 6607       3  23.4500  None        S
889          890            111369       1  30.0000  C148        C
890          891            370376       3   7.7500  None        Q

[891 rows x 6 columns]

In [88]:
survived

     PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]

In [3]:
data = pd.merge(p_info, t_info, how='inner', on="PassengerId")
data = pd.merge(data, survived, how='inner', on="PassengerId")
data

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

In [91]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    object
 2   Sex          891 non-null    object
 3   Age          714 non-null    float64
 4   SibSp        891 non-null    int64
 5   Parch        891 non-null    int64
 6   Ticket       891 non-null    object
 7   Pclass       891 non-null    int64
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
 11  Survived     891 non-null    int64
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 상위 5개 행을 출력하세요.
</div>

In [92]:
data.head()

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 정보(info)를 출력하세요.
</div>

In [93]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    object
 2   Sex          891 non-null    object
 3   Age          714 non-null    float64
 4   SibSp        891 non-null    int64
 5   Parch        891 non-null    int64
 6   Ticket       891 non-null    object
 7   Pclass       891 non-null    int64
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
 11  Survived     891 non-null    int64
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 기술통계(describe)를 확인하세요.
</div>

In [97]:
data.describe()

,PassengerId,Age,SibSp,Parch,Pclass,Fare,Survived
count,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,29.699118,0.523008,0.381594,2.308642,32.204208,0.383838
std,257.353842,14.526497,1.102743,0.806057,0.836071,49.693429,0.486592
min,1.000000,0.420000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,223.500000,20.125000,0.000000,0.000000,2.000000,7.910400,0.000000
50%,446.000000,28.000000,0.000000,0.000000,3.000000,14.454200,0.000000
75%,668.500000,38.000000,1.000000,0.000000,3.000000,31.000000,1.000000
max,891.000000,80.000000,8.000000,6.000000,3.000000,512.329200,1.000000

<div class="alert alert-success">
    <b>EXERCISE</b>: 처음 100명의 데이터를 출력하세요.
</div>

In [103]:
data.loc[:99, :]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,3,8.0500,None,S,0
96,97,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,1,34.6542,A5,C,0
97,98,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,1,63.3583,D10 D12,C,1
98,99,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,2,23.0000,None,S,1
99,100,"Kantor, Mr. Sinai",male,34.0,1,0,244367,2,26.0000,None,S,0

In [102]:
data.iloc[:100, :]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,3,8.0500,None,S,0
96,97,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,1,34.6542,A5,C,0
97,98,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,1,63.3583,D10 D12,C,1
98,99,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,2,23.0000,None,S,1
99,100,"Kantor, Mr. Sinai",male,34.0,1,0,244367,2,26.0000,None,S,0

In [104]:
pd.set_option('display.max_rows', 100)

In [105]:
data.head(100)

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,3,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.00,0,0,373450,3,8.0500,None,S,0
5,6,"Moran, Mr. James",male,NaN,0,0,330877,3,8.4583,None,Q,0
6,7,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,1,51.8625,E46,S,0
7,8,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,3,21.0750,None,S,0
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,3,11.1333,None,S,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,2,30.0708,None,C,1
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,3,16.7000,G6,S,1
11,12,"Bonnell, Miss. Elizabeth",female,58.00,0,0,113783,1,26.5500,C103,S,1
12,13,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,3,8.0500,None,S,0
13,14,"Andersson, Mr. Anders Johan",male,39.00,1,5,347082,3,31.2750,None,S,0
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,3,7.8542,None,S,0
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,0,0,248706,2,16.0000,None,S,1
16,17,"Rice, Master. Eugene",male,2.00,4,1,382652,3,29.1250,None,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,None,S,1
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.00,1,0,345763,3,18.0000,None,S,0
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,None,C,1
20,21,"Fynney, Mr. Joseph J",male,35.00,0,0,239865,2,26.0000,None,S,0
21,22,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,2,13.0000,D56,S,1
22,23,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,3,8.0292,None,Q,1
23,24,"Sloper, Mr. William Thompson",male,28.00,0,0,113788,1,35.5000,A6,S,1
24,25,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,3,21.0750,None,S,0
25,26,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.00,1,5,347077,3,31.3875,None,S,1
26,27,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,3,7.2250,None,C,0
27,28,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,1,263.0000,C23 C25 C27,S,0
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,3,7.8792,None,Q,1
29,30,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,3,7.8958,None,S,0
30,31,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,1,27.7208,None,C,0
31,32,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,1,146.5208,B78,C,1
32,33,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,3,7.7500,None,Q,1
33,34,"Wheadon, Mr. Edward H",male,66.00,0,0,C.A. 24579,2,10.5000,None,S,0
34,35,"Meyer, Mr. Edgar Joseph",male,28.00,1,0,PC 17604,1,82.1708,None,C,0
35,36,"Holverson, Mr. Alexander Oskar",male,42.00,1,0,113789,1,52.0000,None,S,0
36,37,"Mamee, Mr. Hanna",male,NaN,0,0,2677,3,7.2292,None,C,1
37,38,"Cann, Mr. Ernest Charles",male,21.00,0,0,A./5. 2152,3,8.0500,None,S,0
38,39,"Vander Planke, Miss. Augusta Maria",female,18.00,2,0,345764,3,18.0000,None,S,0
39,40,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,3,11.2417,None,C,1
40,41,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,3,9.4750,None,S,0
41,42,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.00,1,0,11668,2,21.0000,None,S,0
42,43,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,3,7.8958,None,C,0
43,44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,2,41.5792,None,C,1
44,45,"Devaney, Miss. Margaret Delia",female,19.00,0,0,330958,3,7.8792,None,Q,1
45,46,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,3,8.0500,None,S,0
46,47,"Lennon, Mr. Denis",male,NaN,1,0,370371,3,15.5000,None,Q,0
47,48,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,3,7.7500,None,Q,1
48,49,"Samaan, Mr. Youssef",male,NaN,2,0,2662,3,21.6792,None,C,0
49,50,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.00,1,0,349237,3,17.8000,None,S,0
50,51,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,3,39.6875,None,S,0
51,52,"Nosworthy, Mr. Richard Cater",male,21.00,0,0,A/4. 39886,3,7.8000,None,S,0
52,53,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,1,76.7292,D33,C,1
53,54,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.00,1,0,2926,2,26.0000,None,S,1
54,55,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,1,61.9792,B30,C,0
55,56,"Woolner, Mr. Hugh",male,NaN,0,0,19947,1,35.5000,C52,S,1
56,57,"Rugg, Miss. Emily",female,21.00,0,0,C.A. 31026,2,10.5000,None,S,1
57,58,"Novel, Mr. Mansouer",male,28.50,0,0,2697,3,7.2292,None,C,0
58,59,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,2,27.7500,None,S,1
59,60,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,3,46.9000,None,S,0
60,61,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,3,7.2292,None,C,0
61,62,"Icard, Miss. Amelie",female,38.00,0,0,113572,1,80.0000,B28,None,1
62,63,"Harris, Mr. Henry Birkhardt",male,45.00,1,0,36973,1,83.4750,C83,S,0
63,64,"Skoog, Master. Harald",male,4.00,3,2,347088,3,27.9000,None,S,0
64,65,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,1,27.7208,None,C,0
65,66,"Moubarek, Master. Gerios",male,NaN,1,1,2661,3,15.2458,None,C,1
66,67,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,2,10.5000,F33,S,1
67,68,"Crease, Mr. Ernest James",male,19.00,0,0,S.P. 3464,3,8.1583,None,S,0
68,69,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,3,7.9250,None,S,1
69,70,"Kink, Mr. Vincenz",male,26.00,2,0,315151,3,8.6625,None,S,0
70,71,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0,C.A. 33111,2,10.5000,None,S,0
71,72,"Goodwin, Miss. Lillian Amy",female,16.00,5,2,CA 2144,3,46.9000,None,S,0
72,73,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,2,73.5000,None,S,0
73,74,"Chronopoulos, Mr. Apostolos",male,26.00,1,0,2680,3,14.4542,None,C,0
74,75,"Bing, Mr. Lee",male,32.00,0,0,1601,3,56.4958,None,S,1
75,76,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,348123,3,7.6500,F G73,S,0
76,77,"Staneff, Mr. Ivan",male,NaN,0,0,349208,3,7.8958,None,S,0
77,78,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,3,8.0500,None,S,0
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,None,S,1
79,80,"Dowdell, Miss. Elizabeth",female,30.00,0,0,364516,3,12.4750,None,S,1
80,81,"Waelens, Mr. Achille",male,22.00,0,0,345767,3,9.0000,None,S,0
81,82,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,345779,3,9.5000,None,S,1
82,83,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,3,7.7875,None,Q,1
83,84,"Carrau, Mr. Francisco M",male,28.00,0,0,113059,1,47.1000,None,S,0
84,85,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,2,10.5000,None,S,1
85,86,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.00,3,0,3101278,3,15.8500,None,S,1
86,87,"Ford, Mr. William Neal",male,16.00,1,3,W./C. 6608,3,34.3750,None,S,0
87,88,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,3,8.0500,None,S,0
88,89,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,1,263.0000,C23 C25 C27,S,1
89,90,"Celotti, Mr. Francesco",male,24.00,0,0,343275,3,8.0500,None,S,0
90,91,"Christmann, Mr. Emil",male,29.00,0,0,343276,3,8.0500,None,S,0
91,92,"Andreasson, Mr. Paul Edvin",male,20.00,0,0,347466,3,7.8542,None,S,0
92,93,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0,W.E.P. 5734,1,61.1750,E31,S,0
93,94,"Dean, Mr. Bertram Frank",male,26.00,1,2,C.A. 2315,3,20.5750,None,S,0
94,95,"Coxon, Mr. Daniel",male,59.00,0,0,364500,3,7.2500,None,S,0
95,96,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,3,8.0500,None,S,0
96,97,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,1,34.6542,A5,C,0
97,98,"Greenfield, Mr. William Bertram",male,23.00,0,1,PC 17759,1,63.3583,D10 D12,C,1
98,99,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1,231919,2,23.0000,None,S,1
99,100,"Kantor, Mr. Sinai",male,34.00,1,0,244367,2,26.0000,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스가 10~20인 데이터를 출력하세요.
</div>

In [106]:
data.loc[10:20, :]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,3,16.7000,G6,S,1
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
12,13,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,3,8.0500,None,S,0
13,14,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,3,31.2750,None,S,0
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,3,7.8542,None,S,0
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,2,16.0000,None,S,1
16,17,"Rice, Master. Eugene",male,2.0,4,1,382652,3,29.1250,None,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,None,S,1
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,3,18.0000,None,S,0
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,None,C,1
20,21,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,2,26.0000,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 컬럼 이름을 모두 출력하세요.
</div>

In [107]:
data.columns

Index(['PassengerId', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Pclass', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='object')

<div class="alert alert-success">
    <b>EXERCISE</b>: 데이터의 shape를 확인하세요.
</div>

In [108]:
data.shape

(891, 12)

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age' 컬럼의 평균을 구하세요.
</div>

In [110]:
data['Age'].mean()

np.float64(29.69911764705882)

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Survived' 컬럼의 고유값을 확인하세요.
</div>

In [111]:
data['Survived'].unique()

array([0, 1])

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 30 이상인 승객만 출력하세요.
</div>

In [113]:
data[data['Age'] >= 30]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
6,7,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,1,51.8625,E46,S,0
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,3,9.0000,None,S,0
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
881,882,"Markun, Mr. Johann",male,33.0,0,0,349257,3,7.8958,None,S,0
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,3,29.1250,None,Q,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별이 'female'이고 생존한 승객만 출력하세요.
</div>

In [115]:
data[(data['Sex'] == "female") & (data['Survived'] == 1)]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,3,11.1333,None,S,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,2,30.0708,None,C,1
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,2,24.0000,None,C,1
875,876,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,3,7.2250,None,C,1
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,2,26.0000,None,S,1
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 10살 이하이고 요금이 20 이상인 승객을 출력하세요.
</div>

In [118]:
data[(data['Age'] <= 10) & (data['Fare'] >= 20)]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
7,8,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,3,21.0750,None,S,0
16,17,"Rice, Master. Eugene",male,2.00,4,1,382652,3,29.1250,None,Q,0
24,25,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,3,21.0750,None,S,0
43,44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,2,41.5792,None,C,1
50,51,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,3,39.6875,None,S,0
58,59,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,2,27.7500,None,S,1
63,64,"Skoog, Master. Harald",male,4.00,3,2,347088,3,27.9000,None,S,0
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,None,S,1
119,120,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,3,31.2750,None,S,0
147,148,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,W./C. 6608,3,34.3750,None,S,0
164,165,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,3,39.6875,None,S,0
165,166,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,3,20.5250,None,S,1
171,172,"Rice, Master. Arthur",male,4.00,4,1,382652,3,29.1250,None,Q,0
182,183,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,3,31.3875,None,S,0
183,184,"Becker, Master. Richard F",male,1.00,2,1,230136,2,39.0000,F4,S,1
184,185,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,3,22.0250,None,S,1
193,194,"Navratil, Master. Michel M",male,3.00,1,1,230080,2,26.0000,F2,S,1
233,234,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,3,31.3875,None,S,1
237,238,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,2,26.2500,None,S,1
261,262,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,3,31.3875,None,S,1
278,279,"Rice, Master. Eric",male,7.00,4,1,382652,3,29.1250,None,Q,0
297,298,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,1,151.5500,C22 C26,S,0
305,306,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,1,151.5500,C22 C26,S,1
340,341,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,2,26.0000,F2,S,1
374,375,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,3,21.0750,None,S,0
386,387,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,3,46.9000,None,S,0
419,420,"Van Impe, Miss. Catharina",female,10.00,0,2,345773,3,24.1500,None,S,0
445,446,"Dodge, Master. Washington",male,4.00,0,2,33638,1,81.8583,A34,S,1
480,481,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,3,46.9000,None,S,0
530,531,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,2,26.0000,None,S,1
535,536,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,2,26.2500,None,S,1
541,542,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,3,31.2750,None,S,0
549,550,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,2,36.7500,None,S,1
618,619,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,2,39.0000,F4,S,1
634,635,"Skoog, Miss. Mabel",female,9.00,3,2,347088,3,27.9000,None,S,0
642,643,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,3,27.9000,None,S,0
720,721,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,2,33.0000,None,S,1
750,751,"Wells, Miss. Joan",female,4.00,1,1,29103,2,23.0000,None,S,1
787,788,"Rice, Master. George Hugh",male,8.00,4,1,382652,3,29.1250,None,Q,0
788,789,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,3,20.5750,None,S,1
813,814,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,3,31.2750,None,S,0
819,820,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,3,27.9000,None,S,0
824,825,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,3,39.6875,None,S,0
827,828,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,2,37.0042,None,C,1
850,851,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,3,31.2750,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이가 결측치인 데이터를 출력하세요.
</div>

In [122]:
# data[data['Age'].isna() == True]
data[data['Age'].isna()]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
5,6,"Moran, Mr. James",male,NaN,0,0,330877,3,8.4583,None,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,None,S,1
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,None,C,1
26,27,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,3,7.2250,None,C,0
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,3,7.8792,None,Q,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,None,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,None,S,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,None,S,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,None,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 나이를 기준으로 오름차순 정렬하세요.
</div>

In [123]:
data.sort_values(by="Age")

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
803,804,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,3,8.5167,None,C,1
755,756,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,2,14.5000,None,S,1
644,645,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,3,19.2583,None,C,1
469,470,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,3,19.2583,None,C,1
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,None,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,None,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,None,S,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,None,S,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,None,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0

In [125]:
data[data['Age'].isna() == False].sort_values(by='Age')

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
803,804,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,3,8.5167,None,C,1
755,756,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,2,14.5000,None,S,1
644,645,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,3,19.2583,None,C,1
469,470,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,3,19.2583,None,C,1
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,None,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
116,117,"Connors, Mr. Patrick",male,70.50,0,0,370369,3,7.7500,None,Q,0
493,494,"Artagaveytia, Mr. Ramon",male,71.00,0,0,PC 17609,1,49.5042,None,C,0
96,97,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,1,34.6542,A5,C,0
851,852,"Svensson, Mr. Johan",male,74.00,0,0,347060,3,7.7750,None,S,0
630,631,"Barkworth, Mr. Algernon Henry Wilson",male,80.00,0,0,27042,1,30.0000,A23,S,1

<div class="alert alert-success">
    <b>EXERCISE</b>: 요금을 기준으로 내림차순 정렬하고 상위 5명만 출력하세요.
</div>

In [129]:
data.sort_values(by='Fare', ascending=False).head()

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
679,680,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,1,512.3292,B51 B53 B55,C,1
258,259,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,1,512.3292,None,C,1
737,738,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,1,512.3292,B101,C,1
88,89,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,1,263.0000,C23 C25 C27,S,1
438,439,"Fortune, Mr. Mark",male,64.0,1,4,19950,1,263.0000,C23 C25 C27,S,0

In [128]:
data.sort_values(by='Fare', ascending=False)[:5]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
679,680,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,1,512.3292,B51 B53 B55,C,1
258,259,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,1,512.3292,None,C,1
737,738,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,1,512.3292,B101,C,1
88,89,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,1,263.0000,C23 C25 C27,S,1
438,439,"Fortune, Mr. Mark",male,64.0,1,4,19950,1,263.0000,C23 C25 C27,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별로 그룹화하여 생존률 평균을 구하세요.
</div>

In [130]:
data[['Sex', 'Survived']].groupby('Sex').mean()

        Survived
Sex
female  0.742038
male    0.188908

<div class="alert alert-success">
    <b>EXERCISE</b>: Pclass별 평균 나이를 구하세요.
</div>

In [138]:
data.groupby('Pclass')[['Age']].mean()

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

In [131]:
data[['Pclass', 'Age']].groupby('Pclass').mean()

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'에 10을 더한 값을 새로운 컬럼 'Age_plus_10'으로 추가하세요.
</div>

In [139]:
data['Age_plus_10'] = data['Age'] + 10
data

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0,32.0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,48.0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1,36.0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,45.0
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0,37.0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,29.0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0,NaN
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,36.0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0,42.0

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'가 18 이상이면 '성인', 아니면 '미성년'으로 분류하는 컬럼을 추가하세요.
</div>

In [141]:
data['isAdult'] = data['Age'].apply(lambda x:"성인" if x >= 18 else '미성년')
data

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isAdult
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0,32.0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,48.0,성인
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1,36.0,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,45.0,성인
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0,37.0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,29.0,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0,NaN,미성년
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,36.0,성인
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0,42.0,성인

In [142]:
import numpy as np

In [144]:
data['Age'].apply(lambda x: np.where(x>=18,"성인", "미성년"))

0       성인
1       성인
2       성인
3       성인
4       성인
      ...
886     성인
887     성인
888    미성년
889     성인
890     성인
Name: Age, Length: 891, dtype: object

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Age'의 결측치를 평균으로 채우세요.
</div>

In [8]:
data[data['Age'].isna()]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
5,6,"Moran, Mr. James",male,NaN,0,0,330877,3,8.4583,None,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,None,S,1
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,None,C,1
26,27,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,3,7.2250,None,C,0
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,3,7.8792,None,Q,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,None,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,None,S,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,None,S,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,None,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0

In [147]:
age_na_index = data[data['Age'].isna()].index

In [148]:
data['Age'].mean()

np.float64(29.69911764705882)

In [150]:
data['Age'] = data['Age'].fillna(data['Age'].mean())

In [151]:
data.loc[age_na_index]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isAdult
5,6,"Moran, Mr. James",male,29.699118,0,0,330877,3,8.4583,None,Q,0,NaN,미성년
17,18,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,2,13.0000,None,S,1,NaN,미성년
19,20,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,3,7.2250,None,C,1,NaN,미성년
26,27,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,3,7.2250,None,C,0,NaN,미성년
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,3,7.8792,None,Q,1,NaN,미성년
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,29.699118,0,0,2629,3,7.2292,None,C,0,NaN,미성년
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,29.699118,8,2,CA. 2343,3,69.5500,None,S,0,NaN,미성년
868,869,"van Melkebeke, Mr. Philemon",male,29.699118,0,0,345777,3,9.5000,None,S,0,NaN,미성년
878,879,"Laleff, Mr. Kristo",male,29.699118,0,0,349217,3,7.8958,None,S,0,NaN,미성년
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,None,S,0,NaN,미성년

In [152]:
data['Age'].isna().sum()

np.int64(0)

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Cabin' 컬럼의 결측치를 'Unknown'으로 채우세요.
</div>

In [154]:
cabin_na_idx = data[data['Cabin'].isna()].index

In [155]:
data['Cabin'] = data['Cabin'].fillna('Unknown')

In [156]:
data.loc[cabin_na_idx]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isAdult
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,32.0,성인
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,36.0,성인
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,45.0,성인
5,6,"Moran, Mr. James",male,29.699118,0,0,330877,3,8.4583,Unknown,Q,0,NaN,미성년
7,8,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,3,21.0750,Unknown,S,0,12.0,미성년
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,"Sutehall, Mr. Henry Jr",male,25.000000,0,0,SOTON/OQ 392076,3,7.0500,Unknown,S,0,35.0,성인
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,3,29.1250,Unknown,Q,0,49.0,성인
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0,37.0,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,NaN,미성년
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0,42.0,성인

In [157]:
data['Cabin'].isna().sum()

np.int64(0)

<div class="alert alert-success">
    <b>EXERCISE</b>: 중복된 'Ticket' 값을 제거하고 몇 개가 남는지 출력하세요.
</div>

In [160]:
data[data['Ticket'].duplicated()]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isAdult
24,25,"Palsson, Miss. Torborg Danira",female,8.000000,3,1,349909,3,21.0750,Unknown,S,0,18.0,미성년
71,72,"Goodwin, Miss. Lillian Amy",female,16.000000,5,2,CA 2144,3,46.9000,Unknown,S,0,26.0,미성년
88,89,"Fortune, Miss. Mabel Helen",female,23.000000,3,2,19950,1,263.0000,C23 C25 C27,S,1,33.0,성인
117,118,"Turpin, Mr. William John Robert",male,29.000000,1,0,11668,2,21.0000,Unknown,S,0,39.0,성인
119,120,"Andersson, Miss. Ellis Anna Maria",female,2.000000,4,2,347082,3,31.2750,Unknown,S,0,12.0,미성년
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
876,877,"Gustafsson, Mr. Alfred Ossian",male,20.000000,0,0,7534,3,9.8458,Unknown,S,0,30.0,성인
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.000000,0,1,11767,1,83.1583,C50,C,1,66.0,성인
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.000000,0,1,230433,2,26.0000,Unknown,S,1,35.0,성인
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,3,29.1250,Unknown,Q,0,49.0,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,NaN,미성년

In [164]:
data = data.drop_duplicates(subset='Ticket')
data['Ticket'].duplicated().sum()

np.int64(0)

<div class="alert alert-success">
    <b>EXERCISE</b>: 'Embarked' 컬럼의 고유값과 각각의 개수를 출력하세요.
</div>

In [165]:
data['Embarked'].value_counts()

Embarked
S    494
C    120
Q     66
Name: count, dtype: int64

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 'PassengerId'로 설정하세요.
</div>

In [168]:
data = data.set_index('PassengerId')
data

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isAdult
PassengerId,,,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,Unknown,S,0,32.0,성인
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,48.0,성인
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,36.0,성인
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,45.0,성인
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,Unknown,S,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,3,7.0500,Unknown,S,0,35.0,성인
887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,Unknown,S,0,37.0,성인
888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,29.0,성인
890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,36.0,성인
891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,Unknown,Q,0,42.0,성인

<div class="alert alert-success">
    <b>EXERCISE</b>: 인덱스를 초기화하세요.
</div>

In [169]:
data = data.reset_index()
data

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,Age_plus_10,isAdult
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,Unknown,S,0,32.0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,48.0,성인
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,36.0,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,45.0,성인
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,Unknown,S,0,45.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,885,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,3,7.0500,Unknown,S,0,35.0,성인
677,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,Unknown,S,0,37.0,성인
678,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,29.0,성인
679,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,36.0,성인
680,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,Unknown,Q,0,42.0,성인

<div class="alert alert-success">
    <b>EXERCISE</b>: 성별과 Pclass의 생존률을 피벗 테이블로 만드세요.
</div>

In [170]:
data.pivot_table(values='Survived', index='Pclass', columns='Sex')

Sex       female      male
Pclass
1       0.960784  0.354167
2       0.910714  0.130952
3       0.595960  0.118644

In [171]:
data.pivot_table(values='Survived', index='Sex', columns='Pclass')

Pclass         1         2         3
Sex
female  0.960784  0.910714  0.595960
male    0.354167  0.130952  0.118644

<div class="alert alert-success">
    <b>EXERCISE</b>: groupby()를 사용하여 각 성별(sex)의 평균 나이(age)를 구하세요.
</div>

In [172]:
data[['Sex', 'Age']].groupby('Sex').mean()

              Age
Sex
female  28.778955
male    31.504328

<div class="alert alert-success">
    <b>EXERCISE</b>: 전체 승객(passenger)의 평균 생존율을 구하세요.
</div>

In [173]:
data['Survived'].mean()

np.float64(0.3509544787077827)

In [175]:
data['Survived'].sum() / len(data['Survived'])

np.float64(0.3509544787077827)

<div class="alert alert-success">
    <b>EXERCISE</b>: 25세 이하 승객의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [178]:
data.loc[data['Age'] <= 25, 'Survived'].mean()

np.float64(0.35096153846153844)

<div class="alert alert-success">
    <b>EXERCISE</b>: 남성의 생존율을 구하세요. 여성의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [181]:
print("남성의 생존율: ", data.loc[data['Sex'] == 'male', 'Survived'].mean())
print("남성의 생존율: ", data.loc[data['Sex'] == 'female', 'Survived'].mean())

남성의 생존율:  0.16842105263157894
남성의 생존율:  0.7718446601941747

In [182]:
data[['Sex', 'Survived']].groupby('Sex').mean()

        Survived
Sex
female  0.771845
male    0.168421

<div class="alert alert-success">
    <b>EXERCISE</b>: 생존율을 구하는 함수가 작성되어 있습니다. 성별 생존율을 groupby를 활용해 구해주세요.
</div>

In [6]:
def survival_ratio(survived):
    print(survived)
    print(type(survived))
    return survived.sum() / len(survived)

In [7]:
data[['Sex', 'Survived', 'Pclass']].groupby('Sex').agg(survival_ratio)

1      1
2      1
3      1
8      1
9      1
      ..
880    1
882    0
885    0
887    1
888    0
Name: Survived, Length: 314, dtype: int64
<class 'pandas.core.series.Series'>
0      0
4      0
5      0
6      0
7      0
      ..
883    0
884    0
886    0
889    1
890    0
Name: Survived, Length: 577, dtype: int64
<class 'pandas.core.series.Series'>
1      1
2      3
3      1
8      3
9      2
      ..
880    2
882    3
885    3
887    1
888    3
Name: Pclass, Length: 314, dtype: int64
<class 'pandas.core.series.Series'>
0      3
4      3
5      3
6      1
7      3
      ..
883    2
884    3
886    2
889    1
890    3
Name: Pclass, Length: 577, dtype: int64
<class 'pandas.core.series.Series'>

        Survived    Pclass
Sex
female  0.742038  2.159236
male    0.188908  2.389948