In [1]:
import pandas as pd

In [17]:
df=pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/bicycle/seoul_bi.csv")
df.head()

         대여일자  대여시간  대여소번호 대여구분코드 성별 연령대코드  이용건수    운동량   탄소량     이동거리  사용시간
0  2021-06-01     0   3541    정기권  F  ~10대     1   0.00  0.00     0.00     8
1  2021-06-01     0    765    정기권  F  ~10대     1  27.21  0.35  1526.81    19
2  2021-06-01     0   2637    정기권  F  ~10대     1  41.40  0.37  1608.56    18
3  2021-06-01     0   2919    정기권  F  ~10대     1   0.00  0.00     0.00    75
4  2021-06-01     0    549    정기권  F  ~10대     1  13.04  0.17   731.55     6

In [13]:
result=df['대여일자'].value_counts().sort_index().to_frame()
result
result[result.대여일자 == result.대여일자.max()].index[0]

            count
대여일자
2021-06-01  48081
2021-06-02  56100
2021-06-03  18985
2021-06-04  56788
2021-06-05  52730
2021-06-06  47787
2021-06-07  52623
2021-06-08  55623
2021-06-09  54507
2021-06-10  36992
2021-06-11  52089
2021-06-12  48569
2021-06-13  43131
2021-06-14  54945

In [19]:
result = df['대여일자'].value_counts().sort_index().to_frame(name='count')
answer = result[result.대여일자  == result.대여일자.max()].index[0]

AttributeError: 'DataFrame' object has no attribute '대여일자'

In [20]:
result = df['대여일자'].value_counts().sort_index().to_frame(name='count')
answer = result[result['count'] == result['count'].max()].index[0]

In [21]:
answer

'2021-06-04'

In [24]:
df['대여일자']=pd.to_datetime(df['대여일자'])
df['day_name']=df['대여일자'].dt.day_name()

In [25]:
df['day_name']

0         Tuesday
1         Tuesday
2         Tuesday
3         Tuesday
4         Tuesday
           ...
678945     Monday
678946     Monday
678947     Monday
678948     Monday
678949     Monday
Name: day_name, Length: 678950, dtype: object

In [27]:
result=df.day_name.value_counts().to_frame()
result

            count
day_name
Wednesday  110607
Friday     108877
Monday     107568
Tuesday    103704
Saturday   101299
Sunday      90918
Thursday    55977

In [32]:
result=df.groupby(['day_name','대여소번호']).size().to_frame('size').sort_values(['day_name','size']).reset_index()

In [37]:
answer=result.drop_duplicates('day_name',keep='first').reset_index(drop=True)
answer

    day_name  대여소번호  size
0     Friday    484     1
1     Monday    484     1
2   Saturday   1376     1
3     Sunday    467     1
4   Thursday    371     1
5    Tuesday    865     1
6  Wednesday    381     1

In [38]:
df

,대여일자,대여시간,대여소번호,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,사용시간,day_name
0,2021-06-01,0,3541,정기권,F,~10대,1,0.00,0.00,0.00,8,Tuesday
1,2021-06-01,0,765,정기권,F,~10대,1,27.21,0.35,1526.81,19,Tuesday
2,2021-06-01,0,2637,정기권,F,~10대,1,41.40,0.37,1608.56,18,Tuesday
3,2021-06-01,0,2919,정기권,F,~10대,1,0.00,0.00,0.00,75,Tuesday
4,2021-06-01,0,549,정기권,F,~10대,1,13.04,0.17,731.55,6,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
678945,2021-06-14,23,4623,정기권,M,60대,1,32.92,0.30,1279.01,37,Monday
678946,2021-06-14,23,2331,정기권,M,60대,1,11.88,0.09,400.00,4,Monday
678947,2021-06-14,23,722,정기권,M,60대,1,53.28,0.48,2070.00,20,Monday
678948,2021-06-14,23,3787,정기권,M,70대~,1,121.25,1.18,5103.30,86,Monday
678949,2021-06-14,23,1911,정기권,M,70대~,1,42.18,0.38,1638.70,28,Monday

In [47]:
result=df.groupby(['연령대코드']).mean(['이동거리'])
result

            대여시간        대여소번호      이용건수         이동거리       사용시간
연령대코드
20대    14.897262  1673.958903  1.133523  3211.890552  26.758754
30대    14.586733  1667.261619  1.104064  3341.443859  28.193036
40대    13.897011  1635.875948  1.079774  3514.857416  30.223774
50대    13.394857  1637.048589  1.042199  3593.668100  30.006872
60대    12.685089  1622.496786  1.018664  3538.145737  31.379096
70대~   12.941432  1661.867369  1.018593  3085.039641  30.089867
~10대   15.319269  1682.186134  1.099689  2634.426279  24.666269

In [52]:
answer=result[['이동거리']]
answer

              이동거리
연령대코드
20대    3211.890552
30대    3341.443859
40대    3514.857416
50대    3593.668100
60대    3538.145737
70대~   3085.039641
~10대   2634.426279

In [53]:
df

,대여일자,대여시간,대여소번호,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,사용시간,day_name
0,2021-06-01,0,3541,정기권,F,~10대,1,0.00,0.00,0.00,8,Tuesday
1,2021-06-01,0,765,정기권,F,~10대,1,27.21,0.35,1526.81,19,Tuesday
2,2021-06-01,0,2637,정기권,F,~10대,1,41.40,0.37,1608.56,18,Tuesday
3,2021-06-01,0,2919,정기권,F,~10대,1,0.00,0.00,0.00,75,Tuesday
4,2021-06-01,0,549,정기권,F,~10대,1,13.04,0.17,731.55,6,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
678945,2021-06-14,23,4623,정기권,M,60대,1,32.92,0.30,1279.01,37,Monday
678946,2021-06-14,23,2331,정기권,M,60대,1,11.88,0.09,400.00,4,Monday
678947,2021-06-14,23,722,정기권,M,60대,1,53.28,0.48,2070.00,20,Monday
678948,2021-06-14,23,3787,정기권,M,70대~,1,121.25,1.18,5103.30,86,Monday
678949,2021-06-14,23,1911,정기권,M,70대~,1,42.18,0.38,1638.70,28,Monday

In [57]:
df['대여일자']=='2021-06-07'

0         False
1         False
2         False
3         False
4         False
          ...
678945    False
678946    False
678947    False
678948    False
678949    False
Name: 대여일자, Length: 678950, dtype: bool

In [58]:
df['대여일자']=pd.to_datetime(df['대여일자'])

In [63]:
result=df[(df.연령대코드 =='~10대')&(df.대여일자==pd.to_datetime('2021-06-07'))].이용건수.mean()

In [64]:
print(result)

1.0863309352517985

In [65]:
df

,대여일자,대여시간,대여소번호,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,사용시간,day_name
0,2021-06-01,0,3541,정기권,F,~10대,1,0.00,0.00,0.00,8,Tuesday
1,2021-06-01,0,765,정기권,F,~10대,1,27.21,0.35,1526.81,19,Tuesday
2,2021-06-01,0,2637,정기권,F,~10대,1,41.40,0.37,1608.56,18,Tuesday
3,2021-06-01,0,2919,정기권,F,~10대,1,0.00,0.00,0.00,75,Tuesday
4,2021-06-01,0,549,정기권,F,~10대,1,13.04,0.17,731.55,6,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...
678945,2021-06-14,23,4623,정기권,M,60대,1,32.92,0.30,1279.01,37,Monday
678946,2021-06-14,23,2331,정기권,M,60대,1,11.88,0.09,400.00,4,Monday
678947,2021-06-14,23,722,정기권,M,60대,1,53.28,0.48,2070.00,20,Monday
678948,2021-06-14,23,3787,정기권,M,70대~,1,121.25,1.18,5103.30,86,Monday
678949,2021-06-14,23,1911,정기권,M,70대~,1,42.18,0.38,1638.70,28,Monday

In [66]:
df['sex']=df['성별'].map(lambda x: '남' if x in ['M','m'] else '여')
answer=df[['sex','이동거리']].groupby('sex').mean()
display(answer)

            이동거리
sex
남    3209.110871
여    3468.575025

In [67]:
df=pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/happy2/happiness.csv")
df.head()

,행복랭킹,나라명,점수,상대GDP,사회적지원,행복기대치,선택의 자유도,관대함,부패에 대한인식,년도
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019

In [71]:
df

,행복랭킹,나라명,점수,상대GDP,사회적지원,행복기대치,선택의 자유도,관대함,부패에 대한인식,년도
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,2019
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,2019
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,2019
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,2019
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,2019
...,...,...,...,...,...,...,...,...,...,...
307,152,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064,2018
308,153,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097,2018
309,154,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106,2018
310,155,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038,2018
311,156,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076,2018

In [70]:
df[df.행복랭킹 ==10]['점수'].mean()

7.259

In [81]:
happy=df[df.행복랭킹<=50][['년도','점수']].groupby('년도').mean()
happy

           점수
년도
2018  6.64678
2019  6.67002

In [82]:
len(df[['행복랭킹','나라명']])

312

In [83]:
- len(df[['행복랭킹','나라명']]

SyntaxError: incomplete input (431270211.py, line 1)

In [84]:
result = len(df[['행복랭킹','나라명']]) - len(df[['행복랭킹','나라명']].drop_duplicates())

In [85]:
result

15