In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv",sep="\t")

In [5]:
df

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,3308904636,1503076540231,1944,9,2,1,2,2,0,2,...,10,2,0,4,0,55,-1,90,238,157
51486,3215685759,1496957179355,3304,9,2,1,1,2,2,2,...,11,7,4,4,1,157,55,119,154,105
51487,3322765040,1504029863961,2156,9,2,2,2,2,0,1,...,10,2,0,2,0,113,122,53,11,157
51488,3256675373,1499562036246,1475,9,2,2,2,2,0,2,...,11,3,0,1,0,154,39,51,90,114
51489,3317333020,1503612754059,1445,9,1,1,1,1,1,2,...,1,0,0,1,0,11,157,141,31,18

In [6]:
df.head()

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18

In [9]:
df.shape
print('행: ',df.shape[0])
print('열: ',df.shape[1])

행:  51490
열:  61

In [10]:
df.columns

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHeraldKills', 't2_ban1', 't2_ban2', 't2_ban3', 't2_ban4',
       't2_ban5'],
      dtype='object')

In [11]:
df.columns[5]

'firstBlood'

In [13]:
df['firstBlood'].dtype

dtype('int64')

In [14]:
df.index

RangeIndex(start=0, stop=51490, step=1)

In [17]:
df.iloc[2,5]

2

In [21]:
df=pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv",encoding='euc-kr')

In [22]:
df.tail(3)

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.0
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.5
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.8

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB

In [26]:
df.select_dtypes(exclude='object').columns

Index(['id', '거주인구', '근무인구', '방문인구', '총 유동인구', '평균 속도', '평균 소요 시간', '평균 기온',
       '일강수량', '평균 풍속'],
      dtype='object')

In [27]:
df.select_dtypes(include='object').columns

Index(['일자', '시도명', '읍면동명'], dtype='object')

In [28]:
df.isnull().sum()

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB

In [30]:
df.describe()

,id,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
count,9621.000000,9.621000e+03,9621.000000,9621.000000,9.621000e+03,9621.000000,9621.000000,9621.000000,9621.000000,9621.000000
mean,27258.000000,3.174315e+05,35471.201510,195889.561802,5.487922e+05,41.109084,37.215873,13.550828,6.972426,2.753171
std,2777.487804,2.982079e+05,40381.214775,140706.090325,4.608802e+05,8.758631,12.993786,7.745515,27.617260,1.498538
min,22448.000000,9.305552e+03,1407.936000,11538.322000,2.225181e+04,24.333000,12.667000,-9.600000,0.000000,0.000000
25%,24853.000000,9.539939e+04,12074.498000,99632.153000,2.216910e+05,34.250000,27.889000,7.600000,0.000000,1.700000
50%,27258.000000,2.221105e+05,21960.928000,152805.335000,3.866935e+05,39.640000,34.500000,13.400000,0.000000,2.400000
75%,29663.000000,4.106671e+05,40192.032000,236325.109000,6.406918e+05,49.105000,46.176000,19.700000,1.500000,3.400000
max,32068.000000,1.364504e+06,263476.965000,723459.209000,2.066484e+06,103.000000,172.200000,30.400000,587.500000,13.333000

In [31]:
df['거주인구']

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: 거주인구, Length: 9621, dtype: float64

In [35]:
df['평균 속도'].quantile(0.75)-df['평균 속도'].quantile(0.25)

14.854999999999997

In [34]:
df['평균 속도']

0       39.556
1       32.900
2       29.538
3       30.000
4       41.583
         ...
9616    44.514
9617    48.609
9618    41.053
9619    46.595
9620    40.863
Name: 평균 속도, Length: 9621, dtype: float64

In [40]:
df.읍면동명.nunique()

41

In [41]:
 df.읍면동명.unique()

array(['도두동', '외도동', '이도2동', '일도1동', '대천동', '서홍동', '한경면', '송산동', '조천읍',
       '일도2동', '영천동', '예래동', '대륜동', '삼도1동', '이호동', '건입동', '중앙동', '삼양동',
       '삼도2동', '이도1동', '남원읍', '대정읍', '정방동', '효돈동', '아라동', '한림읍', '구좌읍',
       '용담1동', '오라동', '화북동', '연동', '표선면', '중문동', '성산읍', '안덕면', '천지동',
       '노형동', '동홍동', '용담2동', '봉개동', '애월읍'], dtype=object)

In [6]:
df=pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv')

In [47]:
tempt=df.loc[df['quantity']==3]
tempt.head()

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75

In [49]:
tempt.head().reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price
0,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
1,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
2,284,3,Canned Soft Drink,[Diet Coke],$3.75
3,338,3,Bottled Water,NaN,$3.27
4,350,3,Canned Soft Drink,[Sprite],$3.75

In [52]:
newdf=df[['quantity','item_price']]
newdf

      quantity item_price
0            1     $2.39
1            1     $3.39
2            1     $3.39
3            1     $2.39
4            2    $16.98
...        ...        ...
4617         1    $11.75
4618         1    $11.75
4619         1    $11.25
4620         1     $8.75
4621         1     $8.75

[4622 rows x 2 columns]

In [56]:
df['new_price']=df['item_price'].str[1:].astype('float')

In [57]:
df['new_price']

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: new_price, Length: 4622, dtype: float64

In [61]:
df.loc[df['item_name']=='Chicken Salad Bowl'].reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
1,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50,22.50
2,94,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$22.50,22.50
3,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
4,137,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$17.50,17.50
...,...,...,...,...,...,...
105,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$17.50,17.50
106,1822,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",$11.25,11.25
107,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
108,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
109,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [64]:
df.loc[(df['new_price']<=9) & (df['item_name']=='Chicken Salad Bowl')]
# 괄호 처리를 해야 함, &

,order_id,quantity,item_name,choice_description,item_price,new_price
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
256,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
526,220,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Sour ...",$8.75,8.75
528,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
529,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
568,234,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$8.75,8.75
585,240,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$8.75,8.75
693,286,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Sour Cream, Cheese, Lett...",$8.75,8.75
702,289,1,Chicken Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$8.75,8.75
762,314,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
1109,458,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
1460,592,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$8.75,8.75
1471,598,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
1483,602,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
1547,628,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
1601,649,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
1621,654,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
1756,709,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",$8.75,8.75
1977,798,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",$8.75,8.75
2031,818,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
2113,850,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]",$8.75,8.75
2224,896,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Sour Cream,...",$8.75,8.75
2314,926,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream]]",$8.75,8.75
2728,1083,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75,8.75
2858,1136,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
2883,1145,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Sour ...",$8.75,8.75
2897,1152,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, Cheese]",$8.75,8.75
2989,1189,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
3033,1206,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",$8.75,8.75
3069,1222,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$8.75,8.75
3117,1243,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",$8.75,8.75
3259,1305,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
3261,1305,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
3310,1327,1,Chicken Salad Bowl,[Fresh Tomato Salsa],$8.75,8.75
3315,1329,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce]]",$8.75,8.75
3381,1357,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Lettuce]]",$8.75,8.75
3411,1368,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Lettuce]]",$8.75,8.75
3623,1450,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",$8.75,8.75
3656,1461,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
3706,1483,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Chees...",$8.75,8.75
3712,1483,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Chees...",$8.75,8.75
3790,1517,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
3798,1521,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
3974,1592,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Lettu...",$8.75,8.75
3997,1601,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
4012,1606,1,Chicken Salad Bowl,[Fresh Tomato Salsa],$8.75,8.75
4035,1615,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$8.75,8.75
4064,1627,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4205,1679,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Chees...",$8.75,8.75
4207,1679,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75,8.75
4333,1730,1,Chicken Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Cheese]]",$8.75,8.75
4352,1738,1,Chicken Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$8.75,8.75
4439,1769,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4520,1797,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$8.75,8.75
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [67]:
df.sort_values('new_price').reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,471,1,Bottled Water,NaN,$1.09,1.09
1,338,1,Canned Soda,[Coca Cola],$1.09,1.09
2,1575,1,Canned Soda,[Dr. Pepper],$1.09,1.09
3,47,1,Canned Soda,[Dr. Pepper],$1.09,1.09
4,1014,1,Canned Soda,[Coca Cola],$1.09,1.09
...,...,...,...,...,...,...
4617,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
4618,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
4619,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
4620,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
4621,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25

In [68]:
df.loc[df['item_name'].str.contains('Chips')]

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
6,3,1,Side of Chips,NaN,$1.69,1.69
10,5,1,Chips and Guacamole,NaN,$4.45,4.45
14,7,1,Chips and Guacamole,NaN,$4.45,4.45
...,...,...,...,...,...,...
4596,1826,1,Chips and Guacamole,NaN,$4.45,4.45
4600,1827,1,Chips and Guacamole,NaN,$4.45,4.45
4605,1828,1,Chips and Guacamole,NaN,$4.45,4.45
4613,1831,1,Chips,NaN,$2.15,2.15
4616,1832,1,Chips and Guacamole,NaN,$4.45,4.45

In [69]:
df.iloc[:,::2]

      order_id                              item_name item_price
0            1           Chips and Fresh Tomato Salsa     $2.39
1            1                                   Izze     $3.39
2            1                       Nantucket Nectar     $3.39
3            1  Chips and Tomatillo-Green Chili Salsa     $2.39
4            2                           Chicken Bowl    $16.98
...        ...                                    ...        ...
4617      1833                          Steak Burrito    $11.75
4618      1833                          Steak Burrito    $11.75
4619      1834                     Chicken Salad Bowl    $11.25
4620      1834                     Chicken Salad Bowl     $8.75
4621      1834                     Chicken Salad Bowl     $8.75

[4622 rows x 3 columns]

In [73]:
df.sort_values('new_price',ascending=False).rest_index(drop=True)

AttributeError: 'DataFrame' object has no attribute 'rest_index'

In [75]:
temp=df.loc[(df.item_name =='Steak Salad') | (df.item_name =='Bowl')]

In [76]:
temp.drop_duplicates('item_name')

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99

In [80]:
mean2=df['new_price'].mean()

In [79]:
mean

7.464335785374297

In [82]:
df.loc[df['new_price']>=mean2]

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [85]:
df.loc[df['item_name']=='Izze','item_name']='Fizzy Lizzy'

In [94]:
df['choice_description'].isnull().sum()

1246

In [98]:
df.loc[df['choice_description'].isnull(),'choice_description']='NoData'
df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
1,1,1,Fizzy Lizzy,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [101]:
df[df['choice_description'].str.contains('Black')]

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
...,...,...,...,...,...,...
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25,11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25,9.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75

In [103]:
(~df['choice_description'].str.contains('Vegetables')).sum()

3900

In [105]:
df[df['item_name'].str.startswith('N')]

,order_id,quantity,item_name,choice_description,item_price,new_price
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
173,77,1,Nantucket Nectar,[Apple],$3.39,3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78,6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39,3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78,6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39,3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39,3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39,3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39,3.39

In [111]:
df.loc[df['item_name'].str.len()>=15]

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
10,5,1,Chips and Guacamole,NoData,$4.45,4.45
...,...,...,...,...,...,...
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75,8.75
4616,1832,1,Chips and Guacamole,NoData,$4.45,4.45
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [116]:
lst=[1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]
df.loc[df['new_price'].isin(lst)]
len(df)

4622

# 3. Grouping

In [7]:
df=pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv')

In [118]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [121]:
# df.groupby('host_name').size()
df['host_name'].value_counts().sort_index()

host_name
'Cil                        1
(Ari) HENRY LEE             1
(Email hidden by Airbnb)    6
(Mary) Haiy                 1
-TheQueensCornerLot         1
                           ..
단비                          1
빈나                          1
소정                          2
진                           1
현선                          1
Name: count, Length: 11452, dtype: int64

In [122]:
df['host_name'].value_counts().sort_values(ascending=False).to_frame(name='counts')
# result = df['host_name'].value_counts().sort_values(ascending=False).to_frame(name='counts')

                  counts
host_name
Michael              417
David                403
Sonder (NYC)         327
John                 294
Alex                 279
...                  ...
Martin & Soledad       1
Soheil                 1
Keno                   1
Keagon                 1
Ilgar & Aysel          1

[11452 rows x 1 columns]

In [127]:
df.groupby(['neighbourhood_group','neighbourhood'],as_index=False).size()

    neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]

In [128]:
Ans= df.groupby(['neighbourhood_group','neighbourhood'], as_index=False).size().groupby(['neighbourhood_group'], as_index=False).max()

In [132]:
df.groupby(['neighbourhood_group','price']).groupby('neighbourhood_group').agg(['mean','var','max','min'])

AttributeError: 'DataFrameGroupBy' object has no attribute 'groupby'

In [133]:
df[['neighbourhood_group','price']].groupby('neighbourhood_group').agg(['mean','var','max','min'])

                          price
                           mean           var    max min
neighbourhood_group
Bronx                 87.496792  11386.885081   2500   0
Brooklyn             124.383207  34921.719135  10000   0
Manhattan            196.875814  84904.159185  10000   0
Queens                99.517649  27923.130227  10000  10
Staten Island        114.812332  77073.088342   5000  13

In [137]:
df[['neighbourhood_group','reviews_per_month']].groupby('neighbourhood_group').agg(['mean','var','max','min'])

                    reviews_per_month
                                 mean       var    max   min
neighbourhood_group
Bronx                        1.837831  2.799878  10.34  0.02
Brooklyn                     1.283212  2.299040  14.00  0.01
Manhattan                    1.272131  2.651206  58.50  0.01
Queens                       1.941200  4.897848  20.94  0.01
Staten Island                1.872580  2.840895  10.12  0.02

In [141]:
df[['neighbourhood','neighbourhood_group','price']].groupby(['neighbourhood','neighbourhood_group']).price.mean()

neighbourhood    neighbourhood_group
Allerton         Bronx                   87.595238
Arden Heights    Staten Island           67.250000
Arrochar         Staten Island          115.000000
Arverne          Queens                 171.779221
Astoria          Queens                 117.187778
                                           ...
Windsor Terrace  Brooklyn               138.993631
Woodhaven        Queens                  67.170455
Woodlawn         Bronx                   60.090909
Woodrow          Staten Island          700.000000
Woodside         Queens                  85.097872
Name: price, Length: 221, dtype: float64

In [144]:
df.groupby(['neighbourhood','neighbourhood_group']).price.mean().unstack()

neighbourhood_group,Bronx,Brooklyn,Manhattan,Queens,Staten Island
neighbourhood,,,,,
Allerton,87.595238,NaN,NaN,NaN,NaN
Arden Heights,NaN,NaN,NaN,NaN,67.25
Arrochar,NaN,NaN,NaN,NaN,115.00
Arverne,NaN,NaN,NaN,171.779221,NaN
Astoria,NaN,NaN,NaN,117.187778,NaN
...,...,...,...,...,...
Windsor Terrace,NaN,138.993631,NaN,NaN,NaN
Woodhaven,NaN,NaN,NaN,67.170455,NaN
Woodlawn,60.090909,NaN,NaN,NaN,NaN
Woodrow,NaN,NaN,NaN,NaN,700.00
Woodside,NaN,NaN,NaN,85.097872,NaN

In [3]:
df.groupby(['neighbourhood','neighbourhood_group']).price.mean().unstack().fillna(-99)

KeyError: 'neighbourhood'

In [12]:
new=df.loc[df['neighbourhood_group'].str.contains('Queens')]

In [14]:
new.groupby(['neighbourhood']).price.agg(['mean','var','max','min'])

                           mean            var    max  min
neighbourhood
Arverne              171.779221   37383.411141   1500   35
Astoria              117.187778  122428.811196  10000   25
Bay Terrace          142.000000    6816.400000    258   32
Bayside              157.948718  166106.470985   2600   30
Bayswater             87.470588    2330.889706    230   45
Belle Harbor         171.500000    8226.571429    350   85
Bellerose             99.357143    3093.016484    240   42
Breezy Point         213.333333    1008.333333    250  195
Briarwood            105.875000   18503.165909   1000   30
Cambria Heights       81.730769    2960.604615    250   31
College Point         88.000000    6445.555556    400   44
Corona                59.171875    2430.557292    359   23
Ditmars Steinway      95.029126    4214.112785    600   22
Douglaston            82.750000    2347.071429    178   40
East Elmhurst         81.183784    4369.487779    700   16
Edgemere              94.727273    4219.418182    200   40
Elmhurst              80.459916    3896.563005    443   15
Far Rockaway         165.862069   52575.980296    900   35
Flushing              93.514085   12417.177448   1500   15
Forest Hills         121.625000   44533.368881   2350   16
Fresh Meadows         99.500000    6394.451613    375   39
Glendale              90.796296    3230.882250    299   25
Hollis                88.642857    1483.016484    175   50
Holliswood           135.750000    5091.583333    239   79
Howard Beach         115.400000    4241.936842    250   40
Jackson Heights       80.897849    2150.470590    260   23
Jamaica               95.770563    8067.047130   1000   10
Jamaica Estates      182.947368   29006.052632    750   35
Jamaica Hills        132.125000   11304.696429    325   50
Kew Gardens           88.375000    2632.306452    219   35
Kew Gardens Hills    112.307692    6230.621538    399   40
Laurelton             95.333333    4355.529412    254   34
Little Neck           75.200000    2368.700000    149   32
Long Island City     127.465549   15529.503009   2000   30
Maspeth               83.645455    2223.607089    245   11
Middle Village       109.580645    3537.118280    265   28
Neponsit             274.666667    5625.333333    350  200
Ozone Park            85.274194    1705.415389    200   25
Queens Village        83.933333    2386.470056    320   25
Rego Park             83.877358    3659.003863    300   21
Richmond Hill         87.117021    3474.147449    300   28
Ridgewood             77.184397    2629.311889    375   20
Rockaway Beach       132.178571    6254.622078    545   49
Rosedale              76.694915    2963.939801    350   22
South Ozone Park      82.400000    4619.989744    400   29
Springfield Gardens   94.235294    2490.848739    300   40
St. Albans           100.828947    9489.903684    600   25
Sunnyside             84.865014    2727.746922    600   12
Whitestone           107.545455   13632.072727    400   35
Woodhaven             67.170455    1642.464864    250   10
Woodside              85.097872    5001.900636    500   28

In [20]:
Ans=df.groupby(['neighbourhood_group','room_type']).size().unstack()
(Ans.loc[:,:]=Ans.values/Ans.sum(axis=1).values.reshape(-1,1))

SyntaxError: cannot assign to subscript here. Maybe you meant '==' instead of '='? (236853574.py, line 2)

In [19]:
df.groupby(['neighbourhood_group','room_type']).size()

neighbourhood_group  room_type
Bronx                Entire home/apt      379
                     Private room         652
                     Shared room           60
Brooklyn             Entire home/apt     9559
                     Private room       10132
                     Shared room          413
Manhattan            Entire home/apt    13199
                     Private room        7982
                     Shared room          480
Queens               Entire home/apt     2096
                     Private room        3372
                     Shared room          198
Staten Island        Entire home/apt      176
                     Private room         188
                     Shared room            9
dtype: int64

# 4. Apply, Map

In [5]:
import pandas as pd

In [6]:
df=pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv')

In [23]:
df.shape

(10127, 19)

In [24]:
df['Income_Category']

0           $60K - $80K
1        Less than $40K
2          $80K - $120K
3        Less than $40K
4           $60K - $80K
              ...
10122       $40K - $60K
10123       $40K - $60K
10124    Less than $40K
10125       $40K - $60K
10126    Less than $40K
Name: Income_Category, Length: 10127, dtype: object

In [25]:
dic = {
    'Unknown'        : 'N',
    'Less than $40K' : 'a',
    '$40K - $60K'    : 'b',
    '$60K - $80K'    : 'c',
    '$80K - $120K'   : 'd',
    '$120K +'        : 'e'   
}

df['newIncome']=df['Income_Category'].map(lambda x:dic[x])
df['newIncome']

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

In [2]:
dic={
  "Unknown : N",
"Less than $40K : a",
"$40K - $60K : b",
"$60K - $80K : c",
"$80K - $120K : d",
"$120K +’ : e"
    }

In [8]:
df['AgeState']  = df.Customer_Age.map(lambda x: x//10 *10)
Ans = df['AgeState'].value_counts().sort_index()

In [9]:
Ans

AgeState
20     195
30    1841
40    4561
50    2998
60     530
70       2
Name: count, dtype: int64

In [11]:
# df['Education_Level'].contains
df['newEduLevel'] = df.Education_Level.map(lambda x : 1 if 'Graduate' in x else 0)
df['newEduLevel'].value_counts()

newEduLevel
0    6483
1    3644
Name: count, dtype: int64

In [16]:
df['newLimit']=df['Credit_Limit'].map(lambda x : 1 if x>=4500 else 0)

In [17]:
df['newLimit'].value_counts()

newLimit
1    5096
0    5031
Name: count, dtype: int64

In [23]:
df['Gender']=df['Gender'].map(lambda x: 'male' if x=='M' else 'female' )

In [26]:
df['Gender'].value_counts()

Gender
female    5358
male      4769
Name: count, dtype: int64

In [25]:
df['Gender'] = df['Gender'].map(lambda x: 'male' if x == 'M' else 'female' if x == 'F' else x)

# 5. Time Series

In [27]:
df=pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   object
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: float64(12), object(1)
memory usage: 667.8+ KB

In [ ]:
df.

In [33]:
df['Yr_Mo_Dy']=pd.to_datetime(df.Yr_Mo_Dy)
df.Yr_Mo_Dy

0      2061-01-01
1      2061-01-02
2      2061-01-03
3      2061-01-04
4      2061-01-05
          ...
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   datetime64[ns]
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 667.8 KB

In [35]:
df['Yr_Mo_Dy'].dt.year.unique()

array([2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978])

In [37]:
df['weekday']=df.Yr_Mo_Dy.dt.weekday

In [38]:
df['weekday']

0       5
1       6
2       0
3       1
4       2
       ..
6569    2
6570    3
6571    4
6572    5
6573    6
Name: weekday, Length: 6574, dtype: int32

In [39]:
df['weekday'].map(lambda x:1 if x in [5,6] else 0)

0       1
1       1
2       0
3       0
4       0
       ..
6569    0
6570    0
6571    0
6572    1
6573    1
Name: weekday, Length: 6574, dtype: int64

In [45]:
df.groupby(df['Yr_Mo_Dy'].dt.month).mean()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday
Yr_Mo_Dy,,,,,,,,,,,,,,
1,2025-02-04 22:40:00.000000000,14.847325,12.914560,13.299624,7.199498,11.667734,8.054839,11.819355,9.512047,9.543208,10.053566,14.550520,18.028763,2.998208
2,2025-02-20 00:22:40.629921280,13.710906,12.111122,12.879132,6.942411,11.551772,7.633858,11.206024,9.341437,9.313169,9.518051,13.728898,17.156142,3.001969
3,2025-04-05 04:00:00.000000000,13.158687,11.505842,12.648118,7.265907,11.554516,7.959409,11.310179,9.635896,9.700324,10.096953,13.810609,16.909317,2.996416
4,2025-05-05 16:00:00.000000000,12.555648,10.429759,12.204815,6.898037,10.677667,7.441389,10.221315,8.909056,8.930870,9.158019,12.664759,14.937611,3.012963
5,2025-06-05 04:00:00.000000000,11.724032,10.145619,11.550394,6.307487,10.224301,6.942061,8.797738,8.452903,8.040806,8.524857,12.767258,13.736039,2.978495
6,2025-07-05 16:00:00.000000000,10.451317,8.949704,10.361315,5.652278,9.529926,6.410093,8.009556,7.920796,7.639796,7.729185,12.246407,12.861818,3.009259
7,2025-08-05 04:00:00.000000000,9.992007,8.357778,9.349642,5.416935,9.302634,5.972348,7.843501,7.262760,7.544480,7.321416,11.676505,12.800789,3.010753
8,2025-09-05 04:00:00.000000000,10.213411,8.415143,9.993441,5.270681,8.901559,5.891057,7.772312,6.842025,7.240573,7.002783,11.110090,12.565943,2.987455
9,2025-10-05 16:00:00.000000000,11.458519,9.981002,10.756883,5.615176,9.766315,6.566222,8.609722,7.745677,7.610556,7.689278,12.686389,14.761963,3.011111
10,2025-11-05 04:00:00.000000000,12.660610,11.010681,11.453943,6.065215,10.550251,7.159910,9.387778,8.726308,8.347181,8.850376,14.155323,16.697151,2.994624
11,2025-12-05 16:00:00.000000000,13.200722,11.639500,12.293407,6.247611,10.501130,7.134333,10.814861,8.427167,8.604000,8.943167,13.815741,18.114185,2.994444
12,2026-01-05 04:00:00.000000000,14.446398,12.353602,13.212276,6.829910,11.301254,7.963710,11.849050,9.209355,9.447258,9.627670,14.259516,18.697599,3.014337

In [43]:
df.groupby(['Yr_Mo_Dy'])

In [46]:
df.fillna(method='ffill').fillna(method='bfill')

C:\Users\Admin\AppData\Local\Temp\ipykernel_2868\3344607385.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill').fillna(method='bfill')

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday
0,2061-01-01,15.04,14.96,13.17,9.29,12.62,9.87,13.67,10.25,10.83,12.58,18.50,15.04,5
1,2061-01-02,14.71,14.96,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,6
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,10.04,8.50,7.67,12.75,12.71,0
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08,2
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46,3
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58,4
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79,5
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08,6

In [48]:
df.groupby(df['Yr_Mo_Dy'].dt.to_period('M')).mean()

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday
Yr_Mo_Dy,,,,,,,,,,,,,,
1971-01,1971-01-16 00:00:00,15.098065,13.398387,13.080000,6.364194,11.342258,7.759677,10.297419,8.350000,8.979355,8.666774,14.392581,16.360000,3.193548
1971-02,1971-02-14 12:00:00,11.724643,9.757143,10.311786,5.242143,9.676786,5.492143,8.683929,7.075000,8.272857,7.833571,12.883929,15.863214,3.000000
1971-03,1971-03-16 00:00:00,10.844839,8.243226,11.228387,5.629032,8.960000,5.486774,9.061935,6.700000,8.494516,7.758387,11.510000,15.678387,2.806452
1971-04,1971-04-15 12:00:00,9.884333,6.848000,11.187667,4.891333,8.165000,5.319000,6.688000,5.856667,7.512667,6.051333,9.014000,12.301000,3.033333
1971-05,1971-05-16 00:00:00,11.200645,8.883548,9.564839,4.888387,8.322903,5.423226,5.875806,7.230323,7.494839,7.122581,11.926129,13.107742,3.064516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2070-08,2070-08-16 00:00:00,9.561613,8.389677,9.485161,4.765806,8.016774,5.660323,5.986774,5.536129,6.849677,6.336129,10.348065,11.870645,3.193548
2070-09,2070-09-15 12:00:00,11.926667,12.082333,11.035333,6.509333,11.482000,7.693000,8.184000,7.921000,9.359667,8.430667,13.995333,15.865667,2.833333
2070-10,2070-10-16 00:00:00,13.354839,11.937097,11.378710,6.665806,11.728387,8.450000,10.874839,10.113871,10.560645,9.052581,15.552903,19.790323,3.000000
2070-11,2070-11-15 12:00:00,13.721667,11.998333,12.118667,6.504000,10.861000,8.169333,10.266000,8.232333,10.010333,8.312000,13.270667,17.852667,3.166667
2070-12,2070-12-16 00:00:00,12.788710,9.659032,14.111935,5.684516,10.013548,6.186129,9.073871,6.961290,8.178387,7.634839,10.878065,17.411613,2.806452

In [49]:
df['RPT'].diff()

0        NaN
1      -0.33
2       3.79
3      -7.92
4       2.75
        ...
6569    3.75
6570   -4.37
6571    0.79
6572    4.50
6573    1.83
Name: RPT, Length: 6574, dtype: float64

In [51]:
df[['RPT','VAL']].rolling(7).mean()

            RPT        VAL
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
6569  11.868571   9.362857
6570  11.904286   9.595714
6571  13.017143  10.011429
6572  13.285714  10.118571
6573  14.951429  11.801429

[6574 rows x 2 columns]

## 미세먼지

In [52]:
df=pd.read_csv("https://raw.githubusercontent.com/Datamanim/pandas/main/seoul_pm.csv")

In [53]:
df.head()

,(년-월-일:시),PM10등급,PM10,PM2.5등급,PM2.5,오존등급,오존,이산화질소등급,이산화질소,일산화탄소등급,일산화탄소,아황산가스등급,아황산가스
0,2021-05-15:15,보통,47.0,보통,19.0,좋음,0.017,좋음,0.023,좋음,0.4,좋음,0.003
1,2021-05-15:14,보통,43.0,보통,20.0,좋음,0.024,좋음,0.019,좋음,0.3,좋음,0.003
2,2021-05-15:13,보통,34.0,보통,24.0,보통,0.035,좋음,0.017,좋음,0.4,좋음,0.004
3,2021-05-15:12,보통,41.0,보통,27.0,보통,0.037,좋음,0.020,좋음,0.4,좋음,0.004
4,2021-05-15:11,보통,51.0,보통,34.0,보통,0.033,좋음,0.023,좋음,0.4,좋음,0.005

In [56]:
def change_date(x):
    import datetime
    hour = x.split(':')[1]
    date = x.split(":")[0]
    
    if hour =='24':
        hour ='00:00:00'
        
        FinalDate = pd.to_datetime(date +" "+hour) +datetime.timedelta(days=1)
        
    else:
        hour = hour +':00:00'
        FinalDate = pd.to_datetime(date +" "+hour)
    
    return FinalDate

df['(년-월-일:시)'] = df['(년-월-일:시)'].apply(change_date)

Ans = df

In [57]:
df['dayName']=df['(년-월-일:시)'].dt.day_name()

In [61]:
Ans1=df.groupby(['dayName','PM10등급'],as_index=False).size()
Ans2=Ans1.pivot(index='dayName',columns='PM10등급',values='size').fillna(0)

In [62]:
df.set_index('(년-월-일:시)',inplace=True,drop=True)

# 6. Pivot

In [63]:
df=pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/under5MortalityRate.csv')

In [64]:
df.drop('Indicator',axis=1,inplace=True)

# 2회독

## Apply, Map

In [2]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                10127 non-null  int64
 1   CLIENTNUM                 10127 non-null  int64
 2   Attrition_Flag            10127 non-null  object
 3   Customer_Age              10127 non-null  int64
 4   Gender                    10127 non-null  object
 5   Dependent_count           10127 non-null  int64
 6   Education_Level           10127 non-null  object
 7   Marital_Status            10127 non-null  object
 8   Income_Category           10127 non-null  object
 9   Card_Category             10127 non-null  object
 10  Months_on_book            10127 non-null  int64
 11  Total_Relationship_Count  10127 non-null  int64
 12  Months_Inactive_12_mon    10127 non-null  int64
 13  Contacts_Count_12_mon     10127 non-null  int64
 14  Credit_Limit              10127 non-null  float64
 15  Total_Revolving_Bal       10127 non-null  int64
 16  Avg_Open_To_Buy           10127 non-null  float64
 17  Total_Amt_Chng_Q4_Q1      10127 non-null  float64
 18  Total_Trans_Amt           10127 non-null  int64
dtypes: float64(3), int64(10), object(6)
memory usage: 1.5+ MB

In [5]:
dic={
    'Unknown' : 'N',
'Less than $40K' : 'a',
'$40K - $60K' : 'b',
'$60K - $80K' : 'c',
'$80K - $120K' : 'd',
'$120K +' : 'e'
}

df['newIncome']=df['Income_Category'].map(lambda x: dic[x])
df['newIncome']

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

In [7]:
def changeCategory(x):
    if x=='Unkown':
        return 'N'
    elif x =='Less than $40K':
        return 'a'
    elif x =='$40K - $60K':   
        return 'b'
    elif x =='$60K - $80K':    
        return 'c'
    elif x =='$80K - $120K':   
        return 'd'
    elif x =='$120K +' :     
        return 'e'

df['newIncome']=df['Income_Category'].apply(changeCategory)
df['newIncome']

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

In [10]:
# df['Education_Level'].str.contains('Graduate')

df['newEduLevel']=df['Education_Level'].map(lambda x: 1 if 'Graduate' in x else 0)
df['newEduLevel'].value_counts()

newEduLevel
0    6483
1    3644
Name: count, dtype: int64

In [11]:
df['newLimit']=df['Credit_Limit'].map(lambda x: 1 if 4500<=x else 0 )

In [12]:
df['newLimit'].value_counts()

newLimit
1    5096
0    5031
Name: count, dtype: int64

# 5 Time_Series

In [13]:
df=pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   object
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: float64(12), object(1)
memory usage: 667.8+ KB

In [16]:
df['Yr_Mo_Dy']=pd.to_datetime(df.Yr_Mo_Dy)

In [17]:
df['Yr_Mo_Dy'].dt.year.unique()

array([2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978], dtype=int32)