In [1]:
print('a')

a

In [2]:
import json
import pandas as pd
import requests

In [3]:
def json_unpack(data):
    result={}
    for item in data['items']:
        for key,value in item.items():
            result.setdefault(key,[]).append(value)
    return result

In [4]:
url='https://openapi.naver.com/v1/search/book.json'
word=input()
payload={'query':word, 'distplay':20, 'start':11, 'sort':'date'}
headers={'X-Naver-Client-Id': 'YhDZdPHyjsCZJxZAEDAt','X-Naver-Client-Secret':'4qRCp_G_Eq'}

야구

In [5]:
r=requests.get(url, params=payload, headers=headers)
# print(r.url)
# print(r.status_code)
data=r.json()
result_df=json_unpack(data)

In [6]:
data

{'lastBuildDate': 'Tue, 01 Apr 2025 13:39:07 +0900',
 'total': 536,
 'start': 11,
 'display': 10,
 'items': [{'title': '한 야구소년의 성장통',
   'link': 'https://search.shopping.naver.com/book/catalog/52997727022',
   'image': 'https://shopping-phinf.pstatic.net/main_5299772/52997727022.20250219072112.jpg',
   'author': '박진우',
   'discount': '8600',
   'publisher': '부크크(bookk)',
   'pubdate': '20250201',
   'isbn': '9791141980214',
   'description': '뒤늦은 도전을 하는 야구소년의 달콤쌉쌀한 인생 이야기. 작가의 자전적 경험에 기반한 이야기이지만, 스포츠의 길을 걷는 여러 사람들에게 감동과 반성의 계기를 줄 수 있는 이야기이다. 이 책의 주인공은 성인이 되어 어떤 삶을 살고 있을까?'},
  {'title': '프로야구 생존기 15 (누구보다 절박한 그들의 야구)',
   'link': 'https://search.shopping.naver.com/book/catalog/52629214535',
   'image': 'https://shopping-phinf.pstatic.net/main_5262921/52629214535.20250123125306.jpg',
   'author': '최훈',
   'discount': '12600',
   'publisher': '대원씨아이',
   'pubdate': '20250124',
   'isbn': '9791142308062',
   'description': '마지막으로 영웅 씨\n영웅 씨는 자신감을 갖기에 충분한 사람이에요\n\n최고의 성적을 거두고 잇는 사이에도 벼랑 끝으로 몰려 있는 기분에서 벗어나지 못하는 노영웅. 야구의 신에게 은총받은 것만 같은 그의 피지컬과는 반대로 노영웅의 멘탈은 늘 막다른 곳으로 밀린다. 이제 육식동물의 본성을 떠올려야 할 순간이다.'},
  {'title': '어린이 야구 캠프 (초등 야구 가이드)',
   'link': 'https://search.shopping.naver.com/book/catalog/52423944623',
   'image': 'https://shopping-phinf.pstatic.net/main_5242394/52423944623.20250114084734.jpg',
   'author': '김동훈',
   'discount': '16920',
   'publisher': '상수리',
   'pubdate': '20250117',
   'isbn': '9791155719978',
   'description': '대한민국 야구의 재미를 모두 담다!\n협동, 규칙 준수, 끈기, 매너 등을 배울 수 있는 스포츠 야구!『어린이 야구 캠프』는 이런 야구의 매력을 어린이의 눈높이에 맞춰 흥미진진하게 전달합니다. 특히 야구를 좋아하거나 처음 관심을 가지기 시작한 아이들에게 야구의 규칙에서부터  프로야구의 역사와 구단, 유명 선수들의 이야기까지 알차게 구성된 이 책은 "야구를 좋아하는 자녀를 둔 부모님들의 필수템"이 될 것입니다.\n\n우리나라 프로야구는 언제부터 시작되었나요?\n우리나라에 야구가 처음 소개된 건 1905년, 하지만 프로야구가 탄생한건 한참 뒤입니다.\n야구가 처음 소개되고 어떤 이야기를 지나 우리나라의 프로야구가 탄생했는지 『어린이 야구 캠프』를 보면 알 수 있습니다.\n\nKIA 타이거즈는 포스트시즌을 몇번이나 진출했을까요?\n누적관중 천만을 돌파하기까지 대한민국 프로야구 구단은 진화해왔습니다. 『어린이 야구 캠프』’야구 부록’ 에서 KBO 구단들의 창단, 전신, 한국시리즈 통산 전적, 포스트시즌 진출 기록등 모든 것을 다룹니다. QR코드로 응원가도 들어보세요!\n\n복잡한 야구 사인 들은 어떻게 외워요?\n지구력과 영리한 두뇌가 필요한 야구에 선수와 감독이 주고받는 사인은 복잡해 보입니다.\n야구팬으로서 궁금한 감독과 선수, 선수들이 서로의 사인을 어떻게 외우는지 『어린이 야구 캠프』3회에서 확인해 볼 수 있습니다.\n\n『어린이 야구 캠프』는 단순히 읽는 책이 아니라 부모와 자녀가 함께 성장하며 야구의 재미와 가치를 느낄 수 있는 특별한 경험을 제공합니다. 이번 개정판은 더욱 풍성한 콘텐츠와 그림과 이미지로 읽는 디자인으로 새롭게 태어났습니다. 지금 바로 야구를 좋아하는 아이와 함께하는 첫걸음을 시작해보세요!'},
  {'title': '야구 보러 갈래?',
   'link': 'https://search.shopping.naver.com/book/catalog/52594023275',
   'image': 'https://shopping-phinf.pstatic.net/main_5259402/52594023275.20250124100000.jpg',
   'author': '양민혜',
   'discount': '16200',
   'publisher': '창조와지식',
   'pubdate': '20250115',
   'isbn': '9791160038446',
   'description': '얘들아, 야구 보러 갈래? 아이들에게 같이 야구 보러 가자고 손을 건네는 그림책. 우리네 인생과 꼭 닮은 야구를 통해 아이들이 야구를 가깝게 느끼고, 부모님과 친구들의 손을 잡고 야구장으로 향하는 발걸음이 하나 둘 늘어나길 바랍니다. 야구공, 글러브, 야구 방망이 등 야구와 관련된 귀여운 캐릭터들이 무엇이라 말하며 야구 보러 가자고 하는지 함께 그림책 속으로 들어가 봅시다.'},
  {'title': '거문고 타고, 야구하고 스포츠에 진심이었던 전통예술인 이야기',
   'link': 'https://search.shopping.naver.com/book/catalog/52595950752',
   'image': 'https://shopping-phinf.pstatic.net/main_5259595/52595950752.20250124095937.jpg',
   'author': '이진원',
   'discount': '8550',
   'publisher': '민속원',
   'pubdate': '20241230',
   'isbn': '9788928520343',
   'description': '근대기 스포츠와 예술 두 분야에서 일가를 이룬 예인들을 모아보았다. 거문고 명인으로 야구선수 포수 박석기를 비롯하여, 장흥기, 고재덕, 안비취, 조택원, 김성기 등이 남긴 발자취를 더듬어 스포츠와 예술의 상호 관련성을 음미해 본다.\n\n예술과 스포츠는 그 밀접한 관계를 고대 올림픽과 같은 과거의 역사 속에서도, 현재 통섭, 융합되어 행해지고 있는 스포츠에서도 찾아볼 수 있다. 더욱 주목되는 것은 예술과 스포츠의 많은 유사성으로 인해 예술과 스포츠에 함께 뛰어난 실력을 선보였던 명인, 명창을 찾아볼 수 있다는 것이다. 이 책에서는 야구와 거문고, 피리와 택견, 탁구와 대금, 노래와 골프, 테니스와 무용, 그리고 활과 거문고 등 두 분야에 능통했던 예술인들을 조명해 보았다.'},
  {'title': 'Why? 스포츠 농구 (배구 / 농구 / 야구 / 축구 / 프로게이머)',
   'link': 'https://search.shopping.naver.com/book/catalog/52079219623',
   'image': 'https://shopping-phinf.pstatic.net/main_5207921/52079219623.20241226071929.jpg',
   'author': '민초',
   'discount': '12170',
   'publisher': '예림당',
   'pubdate': '20241215',
   'isbn': '9788930280259',
   'description': 'Why? 스포츠의 다섯 번째 이야기 \n화려하고 속도감 넘치는 실내 스포츠, 농구의 모든 것!\n\n어린이에게 스포츠 속 즐거움과 더불어 도전ㆍ경쟁ㆍ용기ㆍ결속ㆍ배려 등의 건강한 삶의 가치를 들려주는 스포츠 학습만화 시리즈, 〈Why? 스포츠〉! 다섯 번째 편은 빠르고 화려한 경기로, 전 세계적으로 많은 팬을 보유하고 있는 글로벌 인기 스포츠 농구에 관한 모든 것을 담았다. 농구의 탄생, 매력 포인트, 포지션, 기본기 및 전술 등에 대해 알아보고, 어린 주인공의 성장 일기를 통해 농구 선수가 갖춰야 할 핵심 역량과 자세를 두루 배워 보자.'},
  {'title': '지붕 뚫고 홈런 스포츠 과학 (야구부터 e스포츠까지, 세상 모든 경기장의 과학)',
   'link': 'https://search.shopping.naver.com/book/catalog/51779321622',
   'image': 'https://shopping-phinf.pstatic.net/main_5177932/51779321622.20241207071020.jpg',
   'author': '고호관',
   'discount': '15030',
   'publisher': '휴머니스트',
   'pubdate': '20241209',
   'isbn': '9791170872764',
   'description': '1. 경기장에서 만나는 열두 가지 스포츠 과학\n- 야구장, 축구장, 펜싱장, e스포츠 경기장···\n  흥미진진 이야기가 가득한 공간 속으로\n- 과학의 시선으로 스포츠를 즐기는 방법\n\n스포츠를 좋아하는 사람이라면 누구나 한번쯤 경기장에 방문한 경험이 있을 것이다. 직접 플레이어가 되어 필드를 누비고, 좋아하는 팀을 응원하는 등 현장의 즐거움을 느끼기 위해 많은 사람이 경기장을 찾는다. 선수와 심판, 운동 역학과 기술, 건축 등 각종 이야기가 모여 있는 경기장에는 운동을 하거나 경기를 보는 것만큼이나 과학적으로 즐길 거리로 가득하다.\n《지붕 뚫고 홈런 스포츠 과학》은 국내 최대 스포츠센터를 설계한 건축가 화자의 안내를 따라 센터 내 열두 개 경기장을 차례로 탐방하며 그 속에 담긴 과학을 알아보는 책이다. 건축을 공부하고 수학·과학 잡지 기자로 활동해 온 저자 고호관은 경기장 안팎의 과학 지식을 청소년의 눈높이에서 능수능란하게 풀어낸다.\n저자는 과학의 시선으로 스포츠를 즐기는 흥미로운 방법을 제안한다. ‘돔구장에선 홈런이 더 잘 나올까?’ ‘축구장 잔디를 사시사철 푸르게 유지할 순 없을까?’ ‘펜싱의 전자 판정기는 얼마나 정확할까?’ 등 유익하고 기발한 질문을 따라가다 보면 튼튼한 설계를 책임지는 수학적 원리부터 선수의 동작과 장비에 담긴 물리학, 스포츠 테크와 AI 등 첨단 기술의 원리까지 자연스레 익힐 수 있다.\n\n2. 치고, 넣고, 달리고!\n   찰나의 승부에 담긴 물리·건축·기하학을 찾아서\n- 돔 지붕부터 백보드, 코트, 경사로, AR·VR까지\n  눈길에 닿는 모든 것이 과학이다!\n- 낯선 지식의 연결고리가 되어 줄 ‘취미 밀착’ 과학책\n\n이 책에서 다루는 스포츠는 축구･야구와 같은 구기 종목부터 육상･수영 등의 맨몸 운동, 스키･썰매와 같은 겨울 종목뿐만 아니라 첨단 장비와 기술을 활용하는 펜싱･e스포츠까지 매우 다양하다. 각각의 스포츠에 필요한 신체 능력과 경기를 위한 장비와 공간, 그리고 신체 움직임과 도구 사용 시 역학 등 소개하는 과학과 수학 지식 또한 그 폭이 넓다.\n이를테면 돔구장의 지붕에서는 도형의 특성을 이용한 트러스 구조를, 농구 골대의 백보드에서는 압축력과 인장력으로 깨지지 않는 강화유리의 원리를, 수영장 레인에서는 물 위에서 잘 뜨게 해 주는 인체 중심의 특징을 알려준다. 정신 스포츠인 바둑에 담긴 경우의 수를 비롯해 비교적 최근 만들어진 e스포츠 경기장에서는 AR, VR 등 장비 속 첨단 기술을 하나하나 살펴본다. 이처럼 《지붕 뚫고 홈런 스포츠 과학》은 찰나의 승부가 벌어지는 동안 미처 눈여겨보지 못했던 경기장 곳곳의 과학을 다채롭게 소개한다.\n인기 스포츠뿐만 아니라 하계, 동계 등 전 영역의 스포츠를 망라하는 구성은 과학이 어렵고 낯설게 느껴지는 청소년에게 진입 장벽을 낮춰 준다. 낯섦을 누그러뜨리는 가장 좋은 방법은 그 속에서 나에게 익숙한 것을 찾아내는 것일 테다. 수학 시간은 고역이지만 자투리 시간 짬을 내 겨루는 축구 한판은 언제든 재밌다면, ‘직관’이 주는 짜릿함과 한뜻으로 같은 팀을 응원하는 소속감을 즐긴다면, 중요한 국제 대회나 경기 하이라이트 영상을 챙겨 보는 취미를 가졌다면 이 책은 과학의 문을 여는 좋은 출발점이 되어 줄 것이다.\n\n3. 과학부터 스포츠까지 모르는 게 없는\n   팔방미인 이야기꾼을 만나다\n- 책장이 술술 넘어가는 스토리텔링의 힘\n- 일상의 문제를 해결하는 과학적 상상력\n\n이 책은 국내 최대의 스포츠센터라는 가상의 공간을 설계한 건축가 화자가 그곳을 방문한 사람들과 함께 센터 곳곳의 경기장을 탐방하면서 전개된다. 특히 센터 설계와 관련된 에피소드를 곁들여 독자에게 친근하게 말을 거는 설정은 책장을 넘기는 재미를 선사하며 내용에 몰입하도록 한다. 건축과 과학, 스포츠까지 다방면에 식견을 갖춘 화자를 따라 스포츠의 역사부터 기술의 필요성과 변화, 승부에 미치는 영향 등 물 흐르듯 이어지는 풍성한 이야기를 만날 수 있다. 장마다 배치된 활기 넘치는 일러스트는 생생한 현장의 분위기를 더해 준다.\n관련 분야의 진로를 생각하고 있는 청소년이라면 일상에서 맞닥뜨리는 문제의식으로부터 과학적 해법을 찾아가는 이 책의 서술이 더욱 반가울 것이다. 독자는 경기장을 만든 사람의 관점에서 오늘날 기술이 뛰어난 경기력과 공정한 판정, 합리적인 설비에 대한 고민 끝에 진보해 왔음을 이해하고, 건축가의 제안을 따라 더 나은 경기를 위해 미래에는 어떤 기술이 필요할지 스스로 상상해 볼 수 있다.\n열두 가지 스포츠 중 좋아하는 것이 하나라도 있다면 그 장에서 독서를 시작해 보자. 경기장 탐방의 흐름을 따라가면서도 각 장을 독립적으로 읽어도 충분히 이해할 수 있도록 편집했다. 좋아하면 시선이 열리고, 확장된 시선으로 새로운 흥미를 발견할 수 있다. 그 시작을 함께할 과학책을 찾고 있다면 《지붕 뚫고 홈런 스포츠 과학》을 일독해 보길 권한다.'},
  {'title': '오타니, 만화 속 야구 영웅 (투수도 타자도, 오타니처럼!)',
   'link': 'https://search.shopping.naver.com/book/catalog/51403372620',
   'image': 'https://shopping-phinf.pstatic.net/main_5140337/51403372620.20241116072453.jpg',
   'author': '채빈',
   'discount': '13500',
   'publisher': '깊은나무',
   'pubdate': '20241205',
   'isbn': '9791191979640',
   'description': '#어떻게 역사상 가장 위대한 야구 선수가 되었는지에 관한 비밀\n#꿈을 향해 나아가는 모든 사람에게 영감을 주는 이야기\n#오타니 쇼헤이의 긍정적인 마음과 끊임없는 노력\n\n100년을 뛰어넘은 전설, 오타니 쇼헤이!\n이도류를 넘어 삼도류로, 새로운 역사를 쓰다\n\n천재 야구선수 오타니 쇼헤이는 미국 야구 역사를 지배했던 전설의 선수 베이브 루스를 100년 만에 넘어섰습니다. 투수와 타자를 겸비한 이도류에, 도루까지 장착한 ‘삼도류’의 무기를 가진 오타니는 이제 단순한 스포츠 선수가 아닙니다. 그는 지금 전 세계가 사랑하고 주목하는 스포츠 아이콘입니다. 그의 경기는 야구팬들뿐만이 아니라, 꿈을 가진 모든 이에게 용기와 영감을 선사합니다. 이 책은 오타니가 메이저리그를 평정하며 기록한 빛나는 순간들과 그 뒤에 숨겨진 노력, 그리고 그의 따뜻한 인간미를 담아냈습니다. 지금, 야구를 사랑하는 이들이라면 놓칠 수 없는 그의 뜨거운 이야기를 만나보세요.'},
  {'title': '꿈과 도전을 향해 - 야구, 여행, 그리고 나의 이야기 [양장]',
   'link': 'https://search.shopping.naver.com/book/catalog/51896757625',
   'image': 'https://shopping-phinf.pstatic.net/main_5189675/51896757625.20241212063957.jpg',
   'author': '박성준',
   'discount': '26100',
   'publisher': '퍼플',
   'pubdate': '20241202',
   'isbn': '9788924141702',
   'description': "'꿈과 도전을 향해 - 야구, 여행, 그리고 나의 이야기' 는 '비전북 프로젝트 - 'AI로 꿈을 담다' 를 통해 제작된 '박성준의 인생 첫 에세이' 입니다. \n나만의 스토리에 AI를 활용하여 책을 제작하는 모든 과정은 정말 즐겁고 행복한 시간이었습니다. \n이 책이 많은 이들에게 즐겁게 읽혀지길 바라며 더불어 독자 분들도 직접 책을 만드는 즐거움을 꼭 느낄 수 있기를 바랍니다."},
  {'title': '나의 인생, 나의 야구 (야구장에서 자라고 무등산에서 철들다)',
   'link': 'https://search.shopping.naver.com/book/catalog/51093015622',
   'image': 'https://shopping-phinf.pstatic.net/main_5109301/51093015622.20241102071327.jpg',
   'author': '김성한^김은식',
   'discount': '16200',
   'publisher': '이로츠',
   'pubdate': '20241101',
   'isbn': '9791198020949',
   'description': '야구장을 거닐며 생각한 것들\n\n프로야구 원년에 투수와 타자를 겸하며 10승-10홈런, 타점왕을 동시에 기록했던 해태 타이\n거즈의 팔방미인. 프로야구 최초로 20홈런-20도루, 30홈런을 달성했으며 페넌트레이스 MVP 2회, 홈런왕 3회, 5년 연속 골든글러브를 수상하며 1980~90년대 V9에 빛나는 타이거즈 왕조시대를 연 주역. 하지만 그가 남긴 숱한 기록들은 프로스포츠라는 경쟁의 바다에서 가라앉지 않기 위해 허우적거리다가 떠오른 물거품 같은 것이었는지도 모른다. 그가 견뎌낸 시련과 남몰래 흘렸을 눈물은 얼마나 가슴 저리고 뜨거웠을까. 국가대표 꿈을 이루고 은행원이 되어 어엿한 가족의 가장이 되고 싶었던, 한 사람의 지난 발자취가 오늘을 살아가는 우리에게 기억할 만한 문장이 된다.'}]}

In [84]:
data['items']

[{'title': '자바 스크립트 웹 프로그래밍 (다양한 예제로 설명하는)',
  'link': 'https://search.shopping.naver.com/book/catalog/51259188635',
  'image': 'https://shopping-phinf.pstatic.net/main_5125918/51259188635.20250225071032.jpg',
  'author': '조동영^이완권',
  'discount': '25000',
  'publisher': '북스홀릭퍼블리싱',
  'pubdate': '20241031',
  'isbn': '9791162891247',
  'description': '이 책은 자바스크립트 웹 프로그래밍을 다룬다. 이 책의 구성은 크게 자바스크립트 기본 문법을 다루는 부분(1장~5장)과 자바스크립트를 이용하는 웹 클라이언트 프로그래밍을 다루는 부분(6장~11장)으로 구성된다. 1장은 웹에서 자바스크립트의 역할을, 2장부터 5장까지는 자바스크립트의 기본 문법을 설명하고, Node.js 실행환경에서 자바스크립트를 실행한다. 그리고 6장부터 11장은 웹 클라이언트 프로그래밍으로 자바스크립트를 이용한 HTML DOM 프로그래밍 방법으로 설명하고, 웹브라우저 환경에서 자바스크립트를 실행한다. 자바스크립트 웹 프로그래밍을 위해서는 각 장의 모든 내용들을 이해해야 하지만 특히 7장의 HTML DOM 프로그래밍이 중요하며, 9장은 jQuery 라이브러리를 이용해서 좀더 간결하게 프로그래밍하는 방법을 다룬다.'},
 {'title': '헬로 Bun (차세대 자바스크립트 런타임+올인원 개발 키트를 만나다)',
  'link': 'https://search.shopping.naver.com/book/catalog/50639934625',
  'image': 'https://shopping-phinf.pstatic.net/main_5063993/50639934625.20241003091154.jpg',
  'author': '서대영',
  'discount': '19800',
  'publisher': '제이펍',
  'pubdate': '20241022',
  'isbn': '9791193926710',
  'description': '타입스크립트와 JSX를 아우르는 런타임 Bun으로 만나는 차세대 웹 개발\n\n느리고 복잡한 노드 생태계의 판도를 바꾸기 위해, 차세대 자바스크립트 런타임이자 올인원 개발 키트인 Bun이 탄생했다. 자바스크립트/타입스크립트/JSX 코드를 바로 실행할 수 있고, 패키지 매니저, 모듈 시스템, 테스트 러너, 번들러, DB 등 다양한 기능을 내장했는데도 성능은 노드나 디노를 압도한다. 이 책은 Bun을 본격적으로 살펴보는 최초의 책으로서 Bun 기초부터 시나리오별 활용법과 예제 프로젝트까지, 웹 개발이 얼마나 우아할 수 있는지 보여준다.'},
 {'title': '방구석 부트캠프 자바 (기본으로 돌아가 체계적으로 시작하는 견고한 개발자 되기)',
  'link': 'https://search.shopping.naver.com/book/catalog/50737873628',
  'image': 'https://shopping-phinf.pstatic.net/main_5073787/50737873628.20241010071030.jpg',
  'author': '김경록',
  'discount': '28800',
  'publisher': '리코멘드',
  'pubdate': '20241021',
  'isbn': '9791194084051',
  'description': '여러분의 방구석을 실리콘밸리로 만들어 줄 58일간의 자바 부트캠프\n\n『방구석 부트캠프 자바』는 자바를 실용적이고 체계적으로 학습하기 위한 입문서다. 코딩은 AI가 더 잘하는 시대가 맞지만, AI 시대에 필요한 종합적인 개발자 역량은 단순한 코딩 기술을 넘어, 복잡한 문제를 창의적으로 해결하는 능력, 프로젝트 전체를 조망하고 효과적으로 협업할 수 있는 의사소통 능력, 그리고 빠르게 변화하는 기술 환경에 적응하며 지속적으로 학습할 수 있는 자기 주도적 학습 능력이 요구된다. 무엇보다 AI 도구를 효과적으로 활용하여 업무 효율성을 높이는 것은 AI 시대를 살아가는 개발자의 필수 역량이다. 이 책은 그러한 흐름에 발맞춰 단순히 자바 언어의 문법, 명령어 등과 같은 기술 습득에 그치지 않고 만들고자 하는 것을 논리적 사고 단계에 따라 하나씩 업그레이드하면서 상황에 맞게, 예측할 수 있게, 읽기 편하게 코딩하는 방법을 알려주는 것에 초점을 맞추고 있다.\n자바의 모든 것을 알려주고 있다고 할 순 없지만 적어도 이 책으로 자바를 시작한 독자가 포기하지 않고 끝까지 학습한 후, 이 책에서 이해한 것을 바탕으로 프로그래밍에 흥미를 느끼고 더 공부해 보고 싶다고 느끼도록 하는 것을 목표로 한다. 프로그래밍을 처음 시작한다면, 자바를 처음 시작한다면 더도 덜도 말고 딱 58일 과정으로 구성된 체계적인 학습 구조를 통해 프로그래밍에 입문할 수 있기를 바란다.'},
 {'title': '도망가자, 바다면 더 좋고 (이도훈 에세이)',
  'link': 'https://search.shopping.naver.com/book/catalog/50488152618',
  'image': 'https://shopping-phinf.pstatic.net/main_5048815/50488152618.20240927070943.jpg',
  'author': '맺음',
  'discount': '15300',
  'publisher': '일단',
  'pubdate': '20241009',
  'isbn': '9791198869609',
  'description': '"답답하고 들끓는 마음이 더울지는 몰라도\n우리, 더 울지는 말기로 해요."\n\n5년이란 오랜 시간 동안 위로를 건네준\n‘이도훈 (맺음)’ 작가의 신작이 2년 만에 출간되었다.\n\n그간 농축된 감성이 그대의 메마른 감정에\n긍정적인 영향을 가져다줄 것이다.\n\n총 4장으로 이뤄진 이번 책에서는\n사계절에 어우러지는 이야기가 가득 담겨 있으며,\n이도훈 작가만의 독보적인 문체의 다정함을\n힘껏 끌어안을 수 있을 것이다.\n\n평소 ‘가독성이 좋은 글’로 \n수만 독자에게 사랑받은 청년 작가의 진심.\n\n이번 『도망가자, 바다면 더 좋고』를 통해\n우리에게 어떤 길을 안내할지 \n함께 문장을 누비길 바란다.'},
 {'title': '코믹 실격문장의 최강 현자 13 (세계 최강의 현자가 더욱 강해지기 위해 환생했습니다, 노엔 코믹스)',
  'link': 'https://search.shopping.naver.com/book/catalog/50259598621',
  'image': 'https://shopping-phinf.pstatic.net/main_5025959/50259598621.20240910175427.jpg',
  'author': '칸쇼&효코(Friendly Land) 지음, 카자바나 후우카 그림, 박소현 옮김, 신코 쇼',
  'discount': '4950',
  'publisher': '데이즈엔터',
  'pubdate': '20240926',
  'isbn': '9791138051415',
  'description': '일찍이 [현자]라 불렸던 마법사가 마법 전투에 최적화된 문장을 얻기 위해 미래로 환생한다. 그러나 마법 이론이 퇴화한 미래에선 그 문장은 「실격문장」이라 불리며 멸시당하고 있었다.\n문장의 정보를 뒤틀어 마법 이론을 퇴화시킨 건 마족이었다.\n마티아스는 인간을 멸망시키려는 마족과의 싸움을 펼쳐 나간다!\n마족들을 이용해 다양한 음모를 전개하던 강대한 적.\n그 마족의 이름은 자리디아스. 전에 없던 강대한 마력과 전투력을 가진 마족으로, 마티아스는 “지금의 우리들은 당해낼 수 없다.”고 단언하는데….\n\n대인기 이세계 「문장」 판타지 제13탄!\n원작자의 번외편도 수록!'},
 {'title': '파이썬과 자바스크립트로 배우는 OpenAI 프로그래밍 (OpenAI API 기본 개념부터 프롬프트 작성, 이미지 생성, 노코드 툴 사용, 나만의 AI 모델 제작까지)',
  'link': 'https://search.shopping.naver.com/book/catalog/49255961633',
  'image': 'https://shopping-phinf.pstatic.net/main_4925596/49255961633.20240720092118.jpg',
  'author': '쇼다 쓰야노',
  'discount': '28800',
  'publisher': '제이펍',
  'pubdate': '20240816',
  'isbn': '9791193926284',
  'description': '실용적이고 효율적인 OpenAI API 활용법\n\nOpenAI API를 활용하면 AI와 상호작용을 하면서 원하는 용도에 특화된 AI 봇을 만들 수 있으며 이미지 생성과 제품 정보를 학습시킨 AI 모델을 제작할 수도 있다. 이 책에서는 OpenAI API 개념을 알아본 후 원하는 결과를 도출하는 프롬프트 작성법, DALL-E를 통한 이미지 생성법, 제품 데이터를 활용한 AI 모델 제작 방법 등을 파이썬과 자바스크립트로 나누어 살펴본다. 파워 플랫폼 및 노코드 툴 사용법은 물론 다양한 개발 환경에서 API를 사용하는 방법도 알려준다. AI가 필수인 시대에서 최강의 무기인 OpenAI API를 제대로 활용해보자.'},
 {'title': '기본기가 탄탄한 자바 개발자 (모던 자바의 새로운 기능을 배우고 자바 전문가가 되는 법)',
  'link': 'https://search.shopping.naver.com/book/catalog/49379976618',
  'image': 'https://shopping-phinf.pstatic.net/main_4937997/49379976618.20240727071259.jpg',
  'author': '벤저민 J. 에번스^Clark, Jason^마르테인 페르뷔르흐',
  'discount': '40500',
  'publisher': '제이펍',
  'pubdate': '20240814',
  'isbn': '9791193926277',
  'description': 'JVM부터 성능, 동시성, 컨테이너화 등 고급 기술까지\n\n자바는 엔터프라이즈 소프트웨어 엔지니어링의 핵심이다. 훌륭한 자바 개발자가 되기 위해선 기본기를 갖춰야 한다. 이 책은 자바 8 이후 자바 생태계와 릴리스 주기가 어떻게 변화했는지 살펴보며, 특히 자바 11 및 17에 추가된 새로운 기능을 설명한다. 자바 모듈 및 동시성 모델, 클래스 로딩과 같은 강력한 기능부터 성능 최적화와 바이트코드를 위한 고급 기술 그리고 테스트 중심 개발과 컨테이너 기반 배포와 같은 필수 최신 기술까지 알아본다. 코틀린 및 클로저 등 다른 JVM 언어까지 다뤄 자바 기술을 한층 더 업그레이드하고 탄탄한 기반을 다질 수 있도록 도와준다.'},
 {'title': '자바를 이용한 영상처리 프로그래밍',
  'link': 'https://search.shopping.naver.com/book/catalog/49815969652',
  'image': 'https://shopping-phinf.pstatic.net/main_4981596/49815969652.20240816201524.jpg',
  'author': '류석원',
  'discount': '21800',
  'publisher': '부크크(bookk)',
  'pubdate': '20240812',
  'isbn': '9791141099473',
  'description': '4차 산업시대에 각광을 받고 있는 인공지능은 오늘날 인간의 능력과 비슷하게 발전하고 있으며, 그 한계를 넘기 위해 인간은 인공지능 분야에 무한한 투자를 하고 있습니다.  이러한 인공지능 개발에 있어서 영상처리는 입력장치 개발에 중요한 부분을 담당합니다. 이 책은 현재 많은 개발자들이 사용하는 자바 프로그래밍 언어를 사용하여 디지털 형태의 이미지 효과를 구현하는 영상처리 프로그래밍 기법에 대해 설명합니다.'},
 {'title': '쉽게 설명한 자바스크립트 알고리즘 (쉬운 설명과 실용적 예제로 배우는 알고리즘)',
  'link': 'https://search.shopping.naver.com/book/catalog/49800298622',
  'image': 'https://shopping-phinf.pstatic.net/main_4980029/49800298622.20240816071140.jpg',
  'author': '한상훈',
  'discount': '15300',
  'publisher': '영진닷컴',
  'pubdate': '20240809',
  'isbn': '9788931477252',
  'description': "초급 웹 개발자를 위한 가장 쉬운 알고리즘 교재\n\n자바스크립트는 이제 웹 개발의 중심에 서 있는 필수 언어입니다. 하지만 많은 개발자들이 '알고리즘'이라는 단어만 들어도 두려움을 느끼곤 합니다. 이 책은 초보 개발자들이 쉽게 이해할 수 있도록 알고리즘의 기초부터 실용적인 예제까지 다룹니다. 특정 코드가 최고의 성능을 내지 않더라도 다양한 해결책을 통해 더 나은 코드를 작성하는 방법을 안내합니다. 학문적인 내용은 최소화하고, 실무에서 유용한 알고리즘을 재미있게 배울 수 있도록 구성되었습니다.\n\n【 대상 독자층 】\n- 알고리즘 공부가 필요한 자바스크립트 개발자\n- 자바스크립트 개발자 취업 준비생"},
 {'title': '자바스크립트 + 리액트 디자인 패턴 (자바스크립트와 리액트의 최신 패턴과 렌더링, 성능 패턴까지)',
  'link': 'https://search.shopping.naver.com/book/catalog/49335174628',
  'image': 'https://shopping-phinf.pstatic.net/main_4933517/49335174628.20240725071120.jpg',
  'author': '애디 오스마니',
  'discount': '25200',
  'publisher': '한빛미디어',
  'pubdate': '20240801',
  'isbn': '9791169212571',
  'description': '20가지 이상의 디자인 패턴으로 배우는 최신 웹 개발\n\n유지보수가 쉬운 구조적인 코드를 만들고 싶은가요? 최신 웹 개발 모범 사례를 참고하고 싶은가요? 그렇다면 『자바스크립트 + 리액트 디자인 패턴』이 해답입니다. 이 책은 모듈, 믹스인, 관찰자, 중재자 패턴을 포함한 최신 디자인 패턴을 자바스크립트와 리액트에 적용하는 방법을 소개합니다. 그리고 코드 스플리팅, 서버 사이드 렌더링 등 실무에 필요한 성능과 렌더링 관련 내용을 실용적인 예제와 함께 설명합니다. 또한, 여러 안티 패턴도 함께 다루고 있어 웹 개발을 할 때 흔하게 발생하는 실수를 줄이는 노하우까지 배울 수 있습니다. 이 책에 담긴 20가지 이상의 디자인 패턴을 익혀 더 나은 웹 개발자에 한 걸음 더 다가가세요.'}]

In [7]:
result_df

{'title': ['한 야구소년의 성장통',
  '프로야구 생존기 15 (누구보다 절박한 그들의 야구)',
  '어린이 야구 캠프 (초등 야구 가이드)',
  '야구 보러 갈래?',
  '거문고 타고, 야구하고 스포츠에 진심이었던 전통예술인 이야기',
  'Why? 스포츠 농구 (배구 / 농구 / 야구 / 축구 / 프로게이머)',
  '지붕 뚫고 홈런 스포츠 과학 (야구부터 e스포츠까지, 세상 모든 경기장의 과학)',
  '오타니, 만화 속 야구 영웅 (투수도 타자도, 오타니처럼!)',
  '꿈과 도전을 향해 - 야구, 여행, 그리고 나의 이야기 [양장]',
  '나의 인생, 나의 야구 (야구장에서 자라고 무등산에서 철들다)'],
 'link': ['https://search.shopping.naver.com/book/catalog/52997727022',
  'https://search.shopping.naver.com/book/catalog/52629214535',
  'https://search.shopping.naver.com/book/catalog/52423944623',
  'https://search.shopping.naver.com/book/catalog/52594023275',
  'https://search.shopping.naver.com/book/catalog/52595950752',
  'https://search.shopping.naver.com/book/catalog/52079219623',
  'https://search.shopping.naver.com/book/catalog/51779321622',
  'https://search.shopping.naver.com/book/catalog/51403372620',
  'https://search.shopping.naver.com/book/catalog/51896757625',
  'https://search.shopping.naver.com/book/catalog/51093015622'],
 'image': ['https://shopping-phinf.pstatic.net/main_5299772/52997727022.20250219072112.jpg',
  'https://shopping-phinf.pstatic.net/main_5262921/52629214535.20250123125306.jpg',
  'https://shopping-phinf.pstatic.net/main_5242394/52423944623.20250114084734.jpg',
  'https://shopping-phinf.pstatic.net/main_5259402/52594023275.20250124100000.jpg',
  'https://shopping-phinf.pstatic.net/main_5259595/52595950752.20250124095937.jpg',
  'https://shopping-phinf.pstatic.net/main_5207921/52079219623.20241226071929.jpg',
  'https://shopping-phinf.pstatic.net/main_5177932/51779321622.20241207071020.jpg',
  'https://shopping-phinf.pstatic.net/main_5140337/51403372620.20241116072453.jpg',
  'https://shopping-phinf.pstatic.net/main_5189675/51896757625.20241212063957.jpg',
  'https://shopping-phinf.pstatic.net/main_5109301/51093015622.20241102071327.jpg'],
 'author': ['박진우',
  '최훈',
  '김동훈',
  '양민혜',
  '이진원',
  '민초',
  '고호관',
  '채빈',
  '박성준',
  '김성한^김은식'],
 'discount': ['8600',
  '12600',
  '16920',
  '16200',
  '8550',
  '12170',
  '15030',
  '13500',
  '26100',
  '16200'],
 'publisher': ['부크크(bookk)',
  '대원씨아이',
  '상수리',
  '창조와지식',
  '민속원',
  '예림당',
  '휴머니스트',
  '깊은나무',
  '퍼플',
  '이로츠'],
 'pubdate': ['20250201',
  '20250124',
  '20250117',
  '20250115',
  '20241230',
  '20241215',
  '20241209',
  '20241205',
  '20241202',
  '20241101'],
 'isbn': ['9791141980214',
  '9791142308062',
  '9791155719978',
  '9791160038446',
  '9788928520343',
  '9788930280259',
  '9791170872764',
  '9791191979640',
  '9788924141702',
  '9791198020949'],
 'description': ['뒤늦은 도전을 하는 야구소년의 달콤쌉쌀한 인생 이야기. 작가의 자전적 경험에 기반한 이야기이지만, 스포츠의 길을 걷는 여러 사람들에게 감동과 반성의 계기를 줄 수 있는 이야기이다. 이 책의 주인공은 성인이 되어 어떤 삶을 살고 있을까?',
  '마지막으로 영웅 씨\n영웅 씨는 자신감을 갖기에 충분한 사람이에요\n\n최고의 성적을 거두고 잇는 사이에도 벼랑 끝으로 몰려 있는 기분에서 벗어나지 못하는 노영웅. 야구의 신에게 은총받은 것만 같은 그의 피지컬과는 반대로 노영웅의 멘탈은 늘 막다른 곳으로 밀린다. 이제 육식동물의 본성을 떠올려야 할 순간이다.',
  '대한민국 야구의 재미를 모두 담다!\n협동, 규칙 준수, 끈기, 매너 등을 배울 수 있는 스포츠 야구!『어린이 야구 캠프』는 이런 야구의 매력을 어린이의 눈높이에 맞춰 흥미진진하게 전달합니다. 특히 야구를 좋아하거나 처음 관심을 가지기 시작한 아이들에게 야구의 규칙에서부터  프로야구의 역사와 구단, 유명 선수들의 이야기까지 알차게 구성된 이 책은 "야구를 좋아하는 자녀를 둔 부모님들의 필수템"이 될 것입니다.\n\n우리나라 프로야구는 언제부터 시작되었나요?\n우리나라에 야구가 처음 소개된 건 1905년, 하지만 프로야구가 탄생한건 한참 뒤입니다.\n야구가 처음 소개되고 어떤 이야기를 지나 우리나라의 프로야구가 탄생했는지 『어린이 야구 캠프』를 보면 알 수 있습니다.\n\nKIA 타이거즈는 포스트시즌을 몇번이나 진출했을까요?\n누적관중 천만을 돌파하기까지 대한민국 프로야구 구단은 진화해왔습니다. 『어린이 야구 캠프』’야구 부록’ 에서 KBO 구단들의 창단, 전신, 한국시리즈 통산 전적, 포스트시즌 진출 기록등 모든 것을 다룹니다. QR코드로 응원가도 들어보세요!\n\n복잡한 야구 사인 들은 어떻게 외워요?\n지구력과 영리한 두뇌가 필요한 야구에 선수와 감독이 주고받는 사인은 복잡해 보입니다.\n야구팬으로서 궁금한 감독과 선수, 선수들이 서로의 사인을 어떻게 외우는지 『어린이 야구 캠프』3회에서 확인해 볼 수 있습니다.\n\n『어린이 야구 캠프』는 단순히 읽는 책이 아니라 부모와 자녀가 함께 성장하며 야구의 재미와 가치를 느낄 수 있는 특별한 경험을 제공합니다. 이번 개정판은 더욱 풍성한 콘텐츠와 그림과 이미지로 읽는 디자인으로 새롭게 태어났습니다. 지금 바로 야구를 좋아하는 아이와 함께하는 첫걸음을 시작해보세요!',
  '얘들아, 야구 보러 갈래? 아이들에게 같이 야구 보러 가자고 손을 건네는 그림책. 우리네 인생과 꼭 닮은 야구를 통해 아이들이 야구를 가깝게 느끼고, 부모님과 친구들의 손을 잡고 야구장으로 향하는 발걸음이 하나 둘 늘어나길 바랍니다. 야구공, 글러브, 야구 방망이 등 야구와 관련된 귀여운 캐릭터들이 무엇이라 말하며 야구 보러 가자고 하는지 함께 그림책 속으로 들어가 봅시다.',
  '근대기 스포츠와 예술 두 분야에서 일가를 이룬 예인들을 모아보았다. 거문고 명인으로 야구선수 포수 박석기를 비롯하여, 장흥기, 고재덕, 안비취, 조택원, 김성기 등이 남긴 발자취를 더듬어 스포츠와 예술의 상호 관련성을 음미해 본다.\n\n예술과 스포츠는 그 밀접한 관계를 고대 올림픽과 같은 과거의 역사 속에서도, 현재 통섭, 융합되어 행해지고 있는 스포츠에서도 찾아볼 수 있다. 더욱 주목되는 것은 예술과 스포츠의 많은 유사성으로 인해 예술과 스포츠에 함께 뛰어난 실력을 선보였던 명인, 명창을 찾아볼 수 있다는 것이다. 이 책에서는 야구와 거문고, 피리와 택견, 탁구와 대금, 노래와 골프, 테니스와 무용, 그리고 활과 거문고 등 두 분야에 능통했던 예술인들을 조명해 보았다.',
  'Why? 스포츠의 다섯 번째 이야기 \n화려하고 속도감 넘치는 실내 스포츠, 농구의 모든 것!\n\n어린이에게 스포츠 속 즐거움과 더불어 도전ㆍ경쟁ㆍ용기ㆍ결속ㆍ배려 등의 건강한 삶의 가치를 들려주는 스포츠 학습만화 시리즈, 〈Why? 스포츠〉! 다섯 번째 편은 빠르고 화려한 경기로, 전 세계적으로 많은 팬을 보유하고 있는 글로벌 인기 스포츠 농구에 관한 모든 것을 담았다. 농구의 탄생, 매력 포인트, 포지션, 기본기 및 전술 등에 대해 알아보고, 어린 주인공의 성장 일기를 통해 농구 선수가 갖춰야 할 핵심 역량과 자세를 두루 배워 보자.',
  '1. 경기장에서 만나는 열두 가지 스포츠 과학\n- 야구장, 축구장, 펜싱장, e스포츠 경기장···\n  흥미진진 이야기가 가득한 공간 속으로\n- 과학의 시선으로 스포츠를 즐기는 방법\n\n스포츠를 좋아하는 사람이라면 누구나 한번쯤 경기장에 방문한 경험이 있을 것이다. 직접 플레이어가 되어 필드를 누비고, 좋아하는 팀을 응원하는 등 현장의 즐거움을 느끼기 위해 많은 사람이 경기장을 찾는다. 선수와 심판, 운동 역학과 기술, 건축 등 각종 이야기가 모여 있는 경기장에는 운동을 하거나 경기를 보는 것만큼이나 과학적으로 즐길 거리로 가득하다.\n《지붕 뚫고 홈런 스포츠 과학》은 국내 최대 스포츠센터를 설계한 건축가 화자의 안내를 따라 센터 내 열두 개 경기장을 차례로 탐방하며 그 속에 담긴 과학을 알아보는 책이다. 건축을 공부하고 수학·과학 잡지 기자로 활동해 온 저자 고호관은 경기장 안팎의 과학 지식을 청소년의 눈높이에서 능수능란하게 풀어낸다.\n저자는 과학의 시선으로 스포츠를 즐기는 흥미로운 방법을 제안한다. ‘돔구장에선 홈런이 더 잘 나올까?’ ‘축구장 잔디를 사시사철 푸르게 유지할 순 없을까?’ ‘펜싱의 전자 판정기는 얼마나 정확할까?’ 등 유익하고 기발한 질문을 따라가다 보면 튼튼한 설계를 책임지는 수학적 원리부터 선수의 동작과 장비에 담긴 물리학, 스포츠 테크와 AI 등 첨단 기술의 원리까지 자연스레 익힐 수 있다.\n\n2. 치고, 넣고, 달리고!\n   찰나의 승부에 담긴 물리·건축·기하학을 찾아서\n- 돔 지붕부터 백보드, 코트, 경사로, AR·VR까지\n  눈길에 닿는 모든 것이 과학이다!\n- 낯선 지식의 연결고리가 되어 줄 ‘취미 밀착’ 과학책\n\n이 책에서 다루는 스포츠는 축구･야구와 같은 구기 종목부터 육상･수영 등의 맨몸 운동, 스키･썰매와 같은 겨울 종목뿐만 아니라 첨단 장비와 기술을 활용하는 펜싱･e스포츠까지 매우 다양하다. 각각의 스포츠에 필요한 신체 능력과 경기를 위한 장비와 공간, 그리고 신체 움직임과 도구 사용 시 역학 등 소개하는 과학과 수학 지식 또한 그 폭이 넓다.\n이를테면 돔구장의 지붕에서는 도형의 특성을 이용한 트러스 구조를, 농구 골대의 백보드에서는 압축력과 인장력으로 깨지지 않는 강화유리의 원리를, 수영장 레인에서는 물 위에서 잘 뜨게 해 주는 인체 중심의 특징을 알려준다. 정신 스포츠인 바둑에 담긴 경우의 수를 비롯해 비교적 최근 만들어진 e스포츠 경기장에서는 AR, VR 등 장비 속 첨단 기술을 하나하나 살펴본다. 이처럼 《지붕 뚫고 홈런 스포츠 과학》은 찰나의 승부가 벌어지는 동안 미처 눈여겨보지 못했던 경기장 곳곳의 과학을 다채롭게 소개한다.\n인기 스포츠뿐만 아니라 하계, 동계 등 전 영역의 스포츠를 망라하는 구성은 과학이 어렵고 낯설게 느껴지는 청소년에게 진입 장벽을 낮춰 준다. 낯섦을 누그러뜨리는 가장 좋은 방법은 그 속에서 나에게 익숙한 것을 찾아내는 것일 테다. 수학 시간은 고역이지만 자투리 시간 짬을 내 겨루는 축구 한판은 언제든 재밌다면, ‘직관’이 주는 짜릿함과 한뜻으로 같은 팀을 응원하는 소속감을 즐긴다면, 중요한 국제 대회나 경기 하이라이트 영상을 챙겨 보는 취미를 가졌다면 이 책은 과학의 문을 여는 좋은 출발점이 되어 줄 것이다.\n\n3. 과학부터 스포츠까지 모르는 게 없는\n   팔방미인 이야기꾼을 만나다\n- 책장이 술술 넘어가는 스토리텔링의 힘\n- 일상의 문제를 해결하는 과학적 상상력\n\n이 책은 국내 최대의 스포츠센터라는 가상의 공간을 설계한 건축가 화자가 그곳을 방문한 사람들과 함께 센터 곳곳의 경기장을 탐방하면서 전개된다. 특히 센터 설계와 관련된 에피소드를 곁들여 독자에게 친근하게 말을 거는 설정은 책장을 넘기는 재미를 선사하며 내용에 몰입하도록 한다. 건축과 과학, 스포츠까지 다방면에 식견을 갖춘 화자를 따라 스포츠의 역사부터 기술의 필요성과 변화, 승부에 미치는 영향 등 물 흐르듯 이어지는 풍성한 이야기를 만날 수 있다. 장마다 배치된 활기 넘치는 일러스트는 생생한 현장의 분위기를 더해 준다.\n관련 분야의 진로를 생각하고 있는 청소년이라면 일상에서 맞닥뜨리는 문제의식으로부터 과학적 해법을 찾아가는 이 책의 서술이 더욱 반가울 것이다. 독자는 경기장을 만든 사람의 관점에서 오늘날 기술이 뛰어난 경기력과 공정한 판정, 합리적인 설비에 대한 고민 끝에 진보해 왔음을 이해하고, 건축가의 제안을 따라 더 나은 경기를 위해 미래에는 어떤 기술이 필요할지 스스로 상상해 볼 수 있다.\n열두 가지 스포츠 중 좋아하는 것이 하나라도 있다면 그 장에서 독서를 시작해 보자. 경기장 탐방의 흐름을 따라가면서도 각 장을 독립적으로 읽어도 충분히 이해할 수 있도록 편집했다. 좋아하면 시선이 열리고, 확장된 시선으로 새로운 흥미를 발견할 수 있다. 그 시작을 함께할 과학책을 찾고 있다면 《지붕 뚫고 홈런 스포츠 과학》을 일독해 보길 권한다.',
  '#어떻게 역사상 가장 위대한 야구 선수가 되었는지에 관한 비밀\n#꿈을 향해 나아가는 모든 사람에게 영감을 주는 이야기\n#오타니 쇼헤이의 긍정적인 마음과 끊임없는 노력\n\n100년을 뛰어넘은 전설, 오타니 쇼헤이!\n이도류를 넘어 삼도류로, 새로운 역사를 쓰다\n\n천재 야구선수 오타니 쇼헤이는 미국 야구 역사를 지배했던 전설의 선수 베이브 루스를 100년 만에 넘어섰습니다. 투수와 타자를 겸비한 이도류에, 도루까지 장착한 ‘삼도류’의 무기를 가진 오타니는 이제 단순한 스포츠 선수가 아닙니다. 그는 지금 전 세계가 사랑하고 주목하는 스포츠 아이콘입니다. 그의 경기는 야구팬들뿐만이 아니라, 꿈을 가진 모든 이에게 용기와 영감을 선사합니다. 이 책은 오타니가 메이저리그를 평정하며 기록한 빛나는 순간들과 그 뒤에 숨겨진 노력, 그리고 그의 따뜻한 인간미를 담아냈습니다. 지금, 야구를 사랑하는 이들이라면 놓칠 수 없는 그의 뜨거운 이야기를 만나보세요.',
  "'꿈과 도전을 향해 - 야구, 여행, 그리고 나의 이야기' 는 '비전북 프로젝트 - 'AI로 꿈을 담다' 를 통해 제작된 '박성준의 인생 첫 에세이' 입니다. \n나만의 스토리에 AI를 활용하여 책을 제작하는 모든 과정은 정말 즐겁고 행복한 시간이었습니다. \n이 책이 많은 이들에게 즐겁게 읽혀지길 바라며 더불어 독자 분들도 직접 책을 만드는 즐거움을 꼭 느낄 수 있기를 바랍니다.",
  '야구장을 거닐며 생각한 것들\n\n프로야구 원년에 투수와 타자를 겸하며 10승-10홈런, 타점왕을 동시에 기록했던 해태 타이\n거즈의 팔방미인. 프로야구 최초로 20홈런-20도루, 30홈런을 달성했으며 페넌트레이스 MVP 2회, 홈런왕 3회, 5년 연속 골든글러브를 수상하며 1980~90년대 V9에 빛나는 타이거즈 왕조시대를 연 주역. 하지만 그가 남긴 숱한 기록들은 프로스포츠라는 경쟁의 바다에서 가라앉지 않기 위해 허우적거리다가 떠오른 물거품 같은 것이었는지도 모른다. 그가 견뎌낸 시련과 남몰래 흘렸을 눈물은 얼마나 가슴 저리고 뜨거웠을까. 국가대표 꿈을 이루고 은행원이 되어 어엿한 가족의 가장이 되고 싶었던, 한 사람의 지난 발자취가 오늘을 살아가는 우리에게 기억할 만한 문장이 된다.']}

In [71]:
df=pd.DataFrame(result_df)
df

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"[큰글자책] 긴데요,의 김대호 씨 (짧은글)",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324927...,양귀자,9000,지성사,20180309,9788978893541,어르신의 책읽기 권리를 찾아드리기 위한 국내 최초의 기획 '어르신 이야기책'. '어...
1,[큰글자책] 박치기 사랑 (짧은글),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324936...,양귀자,9000,지성사,20180309,9788978893503,어르신의 책읽기 권리를 찾아드리기 위한 국내 최초의 기획 '어르신 이야기책'. '어...
2,"[큰글자책] 아슬아슬했던 시절, 목단꽃 이불 밑에 숨은 사연 (짧은글)",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324977...,양귀자,9000,지성사,20180309,9788978893572,어르신의 책읽기 권리를 찾아드리기 위한 국내 최초의 기획 '어르신 이야기책'. '어...
3,양귀자: 원미동 시인(The Poet of Wonmi-dong) (The Poet ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,양귀자,7650,아시아,20150417,9788994006291,“문학 한류” 향하는 코리안 모던 픽션 시리즈 - 『원미동 시인』\n\n「원미동 시...
4,바이링궐 에디션 한국 대표 소설 110-2 (산업화),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325437...,김승옥^황석영^윤흥길^신상웅^양귀자,41850,아시아,20150415,9791156620907,산업화 Industrialization\n\n전쟁이 남긴 폐허를 딛고 한국은 근대화...
5,길모퉁이에서 만난 사람 (양귀자 인물소설),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324877...,양귀자,10800,쓰다,20150201,9788998441067,개인 하나하나가 간직한 암호들을 해독하는 과정!\n\n양귀자의 인물소설 『길모퉁이에...
6,누리야 누리야 (양귀자 장편동화),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324871...,양귀자,9000,쓰다,20150120,9788998441050,양귀자 장편동화 『누리야 누리야』. 이 책은 힘들고 지쳐 쓰러질 것만 같은 시간 속...
7,슬픔도 힘이 된다 (양귀자 소설집),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324363...,양귀자,10800,쓰다,20141115,9788998441043,이 책은 작가 양귀자가 1987년부터 1993년에 쓴 중·단편 다섯 편을 모아 펴낸...
8,부엌신 (또 다른 인생이야기),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324902...,양귀자,9000,쓰다,20130620,9788998441036,‘어머니가 차려주는 식탁’에서 벌어진 5년 동안의 울고 울었던 장사의 기록!\n\n...
9,천년의 사랑 (양귀자 장편소설),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324903...,양귀자,13500,쓰다,20130420,9788998441029,그 사랑은 천년 전에 예정된 것이었다!\n\n‘천년’과 ‘환생’이라는 문화코드를 일...

In [8]:
print('전체 검색 페이지: ', data['total'])

전체 검색 페이지:  536

In [9]:
print('검색할 페이지수: ', data['total']//100)

검색할 페이지수:  5

# 네이버 API로 검색한 결과 최대한 가져오기
* 1회 네이버 서버에 요청
* 응답에서 total을 찾아서 display로 나누어 총 반복할 페이지 산출
* 반복문 작성 및 종료 조건 설정
* 1페이지 결과를 데이터 프레임으로 만들고 리스트에 append
* 반복이 끝난 후 리스트에 append된 데이터 프레임을 1개로 합침

In [11]:
cnt=0
last=data['total']//100+1

url='https://openapi.naver.com/v1/search/book.json'
word=input()
headers={'X-Naver-Client-Id': 'YhDZdPHyjsCZJxZAEDAt','X-Naver-Client-Secret':'4qRCp_G_Eq'}

result={}
while cnt!=last:
    
        cnt+=1
        print(cnt)
        
        payload['start']=cnt*10+1
        
        r=requests.get(url, params=payload, headers=headers)
        data=r.json()
        
        for item in data['items']:
            for key,value in item.items():
                result.setdefault(key,[]).append(value)
df=pd.DataFrame(result_df)
df

야구
1
2
3
4
5
6

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,한 야구소년의 성장통,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_529977...,박진우,8600,부크크(bookk),20250201,9791141980214,뒤늦은 도전을 하는 야구소년의 달콤쌉쌀한 인생 이야기. 작가의 자전적 경험에 기반한...
1,프로야구 생존기 15 (누구보다 절박한 그들의 야구),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526292...,최훈,12600,대원씨아이,20250124,9791142308062,마지막으로 영웅 씨\n영웅 씨는 자신감을 갖기에 충분한 사람이에요\n\n최고의 성적...
2,어린이 야구 캠프 (초등 야구 가이드),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_524239...,김동훈,16920,상수리,20250117,9791155719978,"대한민국 야구의 재미를 모두 담다!\n협동, 규칙 준수, 끈기, 매너 등을 배울 수..."
3,야구 보러 갈래?,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_525940...,양민혜,16200,창조와지식,20250115,9791160038446,"얘들아, 야구 보러 갈래? 아이들에게 같이 야구 보러 가자고 손을 건네는 그림책. ..."
4,"거문고 타고, 야구하고 스포츠에 진심이었던 전통예술인 이야기",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_525959...,이진원,8550,민속원,20241230,9788928520343,근대기 스포츠와 예술 두 분야에서 일가를 이룬 예인들을 모아보았다. 거문고 명인으로...
5,Why? 스포츠 농구 (배구 / 농구 / 야구 / 축구 / 프로게이머),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_520792...,민초,12170,예림당,20241215,9788930280259,"Why? 스포츠의 다섯 번째 이야기 \n화려하고 속도감 넘치는 실내 스포츠, 농구의..."
6,"지붕 뚫고 홈런 스포츠 과학 (야구부터 e스포츠까지, 세상 모든 경기장의 과학)",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_517793...,고호관,15030,휴머니스트,20241209,9791170872764,"1. 경기장에서 만나는 열두 가지 스포츠 과학\n- 야구장, 축구장, 펜싱장, e스..."
7,"오타니, 만화 속 야구 영웅 (투수도 타자도, 오타니처럼!)",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_514033...,채빈,13500,깊은나무,20241205,9791191979640,#어떻게 역사상 가장 위대한 야구 선수가 되었는지에 관한 비밀\n#꿈을 향해 나아가...
8,"꿈과 도전을 향해 - 야구, 여행, 그리고 나의 이야기 [양장]",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_518967...,박성준,26100,퍼플,20241202,9788924141702,"'꿈과 도전을 향해 - 야구, 여행, 그리고 나의 이야기' 는 '비전북 프로젝트 -..."
9,"나의 인생, 나의 야구 (야구장에서 자라고 무등산에서 철들다)",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_510930...,김성한^김은식,16200,이로츠,20241101,9791198020949,야구장을 거닐며 생각한 것들\n\n프로야구 원년에 투수와 타자를 겸하며 10승-10...

In [16]:
df.to_csv('야구2.csv',encoding='utf-8',index=False)