# 정적 웹페이지 수집하기
* 순수 HTML, CSS로 만들어진 페이지
* javascrip로 내용을 갱신하지 않는 페이지

# yes24 베스트셀러 자료 수집하기

In [165]:
import pandas as pd
import requests
import time
from bs4 import BeautifulSoup as bs

In [ ]:
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=24

In [162]:
url = "https://www.yes24.com/product/category/bestseller"
payload = dict(categoryNumber="001", pageNumber=1, pageSize=120)
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
soup = bs(r.content, "lxml")
time.sleep(5)
# soup

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200

* 전체 yes24 베스트셀러 페이지중 책 정보가 들어있는 곳: ul#yesBestList
* ul#yesBestList 아래의 li에 책 1권의 정보가 들어있음.

In [125]:
# soup.select_one("ul#yesBestList").select("li")

In [126]:
# yes24 전체 페이지에서 책 정보가 들어있는 부분만 잘라서 book_list에 저장
book_list = soup.select("ul#yesBestList > li")

In [166]:
result = {}
for idx, book in enumerate(book_list):
    print(f"{idx}/{len(book_list)} 추출중", end="\r")
    # 책 제목
    book_title = book.select_one(".gd_name").text
    # 저자
    author = book.select_one(".info_row.info_pubGrp a").text
    # 출판사
    publisher = book.select_one(".authPub.info_pub a").text
    # 출간일
    date_pub = book.select_one(".authPub.info_date").text
    # 가격
    price = book.select_one(".info_row.info_price em.yes_b").text
    # 평점
    rating = book.select_one(".rating_grade em.yes_b").text if book.select_one(".rating_grade em.yes_b") != None else 0.0
    # 리뷰수
    n_reviews = book.select_one(".info_row.info_rating em.txC_blue").text if book.select_one(".info_row.info_rating em.txC_blue") != None else 0
    
    keys = ['book_title', 'author', 'publisher', 'date_pub', 'price', 'rating', 'n_reviews']
    values = [book_title, author, publisher, date_pub, price, rating, n_reviews]
    for key, value in zip(keys, values):
        result.setdefault(key, []).append(value)

for key, value in result.items():
    print(key, len(value))
    
df = pd.DataFrame(result)
df

book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120

,book_title,author,publisher,date_pub,price,rating,n_reviews
0,단 한 번의 삶,김영하,복복서가,2025년 04월,"15,120",8.9,9
1,듀얼 브레인,이선 몰릭,상상스퀘어,2025년 03월,"18,900",8.7,38
2,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,2025년 03월,"18,000",9.9,56
3,소년이 온다,한강,창비,2014년 05월,"13,500",9.7,"3,845"
4,성적 초격차를 만드는 독서력 수업,김수미,빅피시,2025년 03월,"17,820",9.9,67
...,...,...,...,...,...,...,...
115,한권으로 정리한 김종우 도끼 올인원 우편일반,김종우,가치산책컴퍼니,2025년 04월,"24,300",0.0,0
116,청춘 돼지는 디어 프렌드의 꿈을 꾸지 않는다,카모시다 하지메,디앤씨미디어(D&C미디어),2025년 04월,"7,650",0.0,0
117,청춘 돼지는 걸 프렌드의 꿈을 꾸지 않는다,카모시다 하지메,디앤씨미디어(D&C미디어),2025년 04월,"7,650",0.0,0
118,혼잡(JOB) IBK기업은행 기출복원 실전모의고사 (NCS직업기초·경제·경영·시사),혼Job취업연구소,커리어빅,2025년 03월,"23,400",0.0,0
119,미술관에 가고 싶어지는 미술책,김영숙,휴머니스트,2021년 08월,"12,600",9.5,26

In [108]:
x = 3
print("짝수") if x % 2 == 0 else print("홀수")

홀수

In [133]:
print("가격: ", len(list(soup.select("ul#yesBestList .info_row.info_price em.yes_b"))))
print("평점: ", len(list(soup.select("ul#yesBestList .rating_grade em.yes_b"))))
print("리뷰수: ", len(list(soup.select("ul#yesBestList .info_row.info_rating em.txC_blue"))))

가격:  120
평점:  108
리뷰수:  108

In [128]:
result['author'][28]

'정관 스님'

In [134]:
book_list[28].select_one(".info_row.info_pubGrp").text

'\n\n정관 스님, 후남 셀만 저/베로니크 회거 사진/양혜영 역\r\n                            \n윌북(willbook)\n2025년 04월\n'

In [150]:
book_list[28].select_one(".authPub.info_auth").text.split("/")[0]

'\n정관 스님, 후남 셀만 저'

In [151]:
book_list[28].select_one(".authPub.info_auth").text.split("/")[1]

'베로니크 회거 사진'

In [152]:
book_list[28].select_one(".authPub.info_auth").text.split("/")[2]

'양혜영 역\r\n                            '

In [161]:
book_list[20].select_one(".authPub.info_auth").text.split("/")[1].replace("\n", " ").strip("감추기 ")

'백온유 강보라 서장원 성해나 성혜령 이희주 현호정'

In [ ]:
https://www.yes24.com/product/goods/101402

In [170]:
link = "https://www.yes24.com" + book_list[20].select_one(".gd_name")['href']

'https://www.yes24.com/product/goods/144248311'

# 전체 페이지 수집하기

In [165]:
import pandas as pd
import requests
import time
from bs4 import BeautifulSoup as bs

In [175]:
result_list = []
page = 1
while True:
    url = "https://www.yes24.com/product/category/bestseller"
    payload = dict(categoryNumber="001", pageNumber=page, pageSize=120)
    r = requests.get(url, params=payload)
    print(r.url)
    print(r.status_code)
    soup = bs(r.content, "lxml")
    time.sleep(5)
    # yes24 전체 페이지에서 책 정보가 들어있는 부분만 잘라서 book_list에 저장
    book_list = soup.select("ul#yesBestList > li")
    result = {}
    for idx, book in enumerate(book_list):
        print(f"{idx}/{len(book_list)} 추출중", end="\r")
        # 책 제목
        book_title = book.select_one(".gd_name").text
        # 저자
        author = book.select_one(".info_row.info_pubGrp a").text
        # 출판사
        publisher = book.select_one(".authPub.info_pub a").text
        # 출간일
        date_pub = book.select_one(".authPub.info_date").text
        # 가격
        price = book.select_one(".info_row.info_price em.yes_b").text
        # 평점
        rating = book.select_one(".rating_grade em.yes_b").text if book.select_one(".rating_grade em.yes_b") != None else 0.0
        # 리뷰수
        n_reviews = book.select_one(".info_row.info_rating em.txC_blue").text if book.select_one(".info_row.info_rating em.txC_blue") != None else 0

        keys = ['book_title', 'author', 'publisher', 'date_pub', 'price', 'rating', 'n_reviews']
        values = [book_title, author, publisher, date_pub, price, rating, n_reviews]
        for key, value in zip(keys, values):
            result.setdefault(key, []).append(value)

    for key, value in result.items():
        print(key, len(value))

    result_list.append(pd.DataFrame(result))
    
    if page < 12:
        page += 1
    else:
        break
    
result_list = pd.concat(result_list)
result_list = result_list.reset_index(drop=True)
result_list

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=2&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=3&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=4&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=5&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=6&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=7&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=8&pageSize=120
200
book_title 120
author 120
publisher 120
date_pub 120
price 120
rating 120
n_reviews 120
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=9&pageSize=120
200
book_title 39
author 39
publisher 39
date_pub 39
price 39
rating 39
n_reviews 39
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=10&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=11&pageSize=120
200
https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=12&pageSize=120
200

,book_title,author,publisher,date_pub,price,rating,n_reviews
0,단 한 번의 삶,김영하,복복서가,2025년 04월,"15,120",8.9,9
1,듀얼 브레인,이선 몰릭,상상스퀘어,2025년 03월,"18,900",8.7,38
2,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,2025년 03월,"18,000",9.9,56
3,소년이 온다,한강,창비,2014년 05월,"13,500",9.7,"3,845"
4,성적 초격차를 만드는 독서력 수업,김수미,빅피시,2025년 03월,"17,820",9.9,67
...,...,...,...,...,...,...,...
994,오십의 기술,이호선,카시오페아,2023년 04월,"16,200",9.2,48
995,햇빛초 대나무 숲에 새 글이 올라왔습니다,황지영,우리학교,2020년 08월,"13,050",9.9,68
996,처음 읽는 그리스 로마 신화 2,최설희,미래엔아이세움,2020년 08월,"10,800",9.9,84
997,"칵테일, 러브, 좀비",조예은,안전가옥,2020년 04월,"11,700",9.2,"1,132"
998,와일드 로봇,피터 브라운,거북이북스,2019년 07월,"15,120",9.9,86

# 저자, 역자, 글그림, 편저, 공동저자등 구분하기

In [176]:
url = "https://www.yes24.com/product/category/bestseller"
payload = dict(categoryNumber="001", pageNumber=1, pageSize=120)
r = requests.get(url, params=payload)
print(r.url)
print(r.status_code)
soup = bs(r.content, "lxml")
time.sleep(5)
book_list = soup.select("ul#yesBestList > li")

https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=120
200

In [185]:
def text_clean(text):
    return text.replace("\n", " ").replace("\r", " ").strip()

In [205]:

for book in book_list:
    author = ""
    photo = ""
    trans = ""
    paint = ""
    for item in text_clean(book.select_one(".authPub.info_auth").text).split("/"):
        if "저" == item[-1]:
            author = item
        elif "정보 더 보기" == item[-7:]:
            author = item.replace("정보 더 보기", "").strip()
        elif "사진" == item[-2:]:
            photo = item
        elif "역" == item[-1]:
            trans = item
        elif "글그림" == item[-3:]:
            paint = item
    print(f"author{author}, photo{photo}, trans{trans}, paint{paint}")

author김영하 저, photo, trans, paint
author이선 몰릭 저, photo, trans신동숙 역, paint
author김종원 저, photo, trans, paint
author한강 저, photo, trans, paint
author김수미 저, photo, trans, paint
author태수 저, photo, trans, paint
author김주환 저, photo, trans, paint
author양귀자 저, photo, trans, paint
author, photo, trans권남희 역, paint요시타케 신스케 글그림
author코이케 류노스케 저, photo, trans박재현 역, paint
author, photo, trans현승희 역, paint와야마 야마 글그림
author유발 하라리 저, photo, trans김명주 역, paint
author유선경 저, photo, trans, paint
author최태성 저, photo, trans, paint
author김주환 저, photo, trans, paint
author, photo, trans, paint안녕달 글그림
author최태성 저, photo, trans, paint
author브라이언 트레이시 저, photo, trans정지현 역, paint
author정대건 저, photo, trans, paint
author존 윌리엄스 저, photo, trans김승욱 역, paint
author백온유, 강보라, 서장원, 성해나, 성혜령 저 외 2명, photo, trans, paint
author한현근 저, photo, trans, paint
author한강 저, photo, trans, paint
authorETS 저, photo, trans, paint
authorETS 저, photo, trans, paint
author성해나 저, photo, trans, paint
author오건영 저, photo, trans, paint
author한강 저, photo, trans, paint
author정관 스님, 후남 셀만 저, photo베로니크 회거 사진, trans양혜영 역, paint
author, photo, trans, paint스즈키 유우토 글그림
author김직선 저, photo, trans, paint
author, photo, trans, paint니이 사토루 글그림
author김지훈(포메뽀꼬) 저, photo, trans, paint
author안-엘렌 클레르, 뱅상 트리부 저, photo, trans구영옥 역, paint
author한동훈 저, photo, trans, paint
authorDavid Cho 저, photo, trans, paint
author한강 저, photo, trans, paint
author김종원 저, photo, trans, paint
author김종원 저, photo, trans, paint
author프리드리히 니체 저, photo, trans, paint
author최태성 저, photo, trans, paint
author김종원 저, photo, trans, paint
author, photo, trans, paint루리 글그림
author벤저민 하디 저, photo, trans최은아 역, paint
author, photo, trans, paint
author, photo, trans, paint타츠 유키노부 글그림
author김종원 저, photo, trans, paint
author정수봉, 이준영, 원효리, 이성열, 임다연 편저, photo, trans, paint
author흔한남매 원저, photo, trans, paint
author유은하 저, photo, trans, paint
author천근아 저, photo, trans, paint
author이철희 저, photo, trans, paint
author신재은 저, photo, trans, paint
author태 킴 저, photo, trans김정민 역, paint
author, photo, trans유유리 역, paint타치바나 오레코 글그림
author, photo, trans, paint유설화 글그림
author, photo, trans장혜영 역, paint아이다이로 글그림
author위혜정 저, photo, trans, paint
author김민철 편저, photo, trans, paint
author, photo, trans, paint
author이어령 저, photo, trans, paint
author백수린 저, photo, trans, paint
author네빌 고다드 저, photo, trans홍주연 역, paint
author세이노(SayNo) 저, photo, trans, paint
author클레어 키건 저, photo, trans홍한별 역, paint
author최승필 저, photo, trans, paint
author손원평 저, photo, trans, paint
author칼 에드워드 세이건 저, photo, trans홍승수 역, paint
author유현준 저, photo, trans, paint
author, photo, trans반기모 역, paint센바 쿠로노 글그림
author해커스 일본어연구소 저, photo, trans, paint
author강용수 저, photo, trans, paint
author문상훈 저, photo, trans, paint
author데일 카네기 저, photo, trans임상훈 역, paint
author, photo, trans, paint
author강보라, 성해나, 윤단 저, photo, trans, paint
author한강 저, photo, trans, paint
author, photo, trans, paint
author리처드 도킨스 저, photo, trans홍영남, 이상임 역, paint
author김지원, 김혜원, 도헌정, 허완, 조성도 저 외 5명, photo, trans, paint
author유발 하라리 저, photo, trans조현욱 역, paint
author최승호 외 저, photo, trans, paint
author조수용 저, photo, trans, paint
author박준 저, photo, trans, paint
author박태웅 저, photo, trans, paint
author, photo, trans, paint하마지 아키, 쿠미쵸 글그림
author이꽃님 저, photo, trans, paint
author정주희 저, photo, trans, paint
author, photo, trans, paint하마지 아키 글그림
author고시넷 NCS 연구소 편저, photo, trans, paint
author, photo, trans, paint
author빨간내복야코 원저, photo, trans, paint
author오창석 저, photo, trans, paint
author인이이 저, photo, trans장려진 역, paint
author도야마 시게히코 저, photo, trans전경아 역, paint
author, photo, trans, paint
author제시카 윤 저, photo, trans, paint
author헤르만 헤세 저, photo, trans전영애 역, paint
author, photo, trans, paint백유연 글그림
author예소연, 김기태, 문지혁, 서장원, 정기현 저 외 1명, photo, trans, paint
author엄예정 저, photo, trans, paint
author박진여 저, photo, trans, paint
author김주환 저, photo, trans, paint
authorDavid Cho 저, photo, trans, paint
author한강 저, photo, trans, paint
author모건 하우절 저, photo, trans이지연 역, paint
author모건 하우절 저, photo, trans이수경 역, paint
author한현근 저, photo, trans, paint
author유창호 편저, photo, trans, paint
author, photo, trans, paint
author슈뻘맨 원저, photo, trans, paint
author로이스 라우리 저, photo, trans장은수 역, paint
author최진영 저, photo, trans, paint
author김대환 저, photo, trans, paint
author박재한 저, photo, trans, paint
author김종우 편저, photo, trans, paint
author카모시다 하지메 저, photo, trans이승원 역, paint
author카모시다 하지메 저, photo, trans이승원 역, paint
author혼Job취업연구소 편저, photo, trans, paint
author김영숙 저, photo, trans, paint

In [203]:
for item in text_clean(book_list[20].select_one(".authPub.info_auth").text).split("/"):
#     print(item)
    if "감추기" in item[:4]:
        author = item.replace("감추기", "").strip()
        print(author)

백온유 강보라 서장원 성해나 성혜령 이희주 현호정