# 하나은행에서 환율조회 부분 찾아서 selenium으로 열기
* 날짜 입력부분 찾아 날짜 넣기
* 조회 버튼 찾아 버튼 클릭하기
* 조회된 데이터를 pd.read_html을 이용해 dataframe으로 만들기
* 데이터 프레임에 조회 날짜 컬럼 만들어서 날짜 추가하기

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import pandas as pd

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/135.0.0.0")
options.add_argument("lang=ko_KR")


driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )

url = "https://www.kebhana.com/cms/rate/index.do?contentUrl=/cms/rate/wpfxd651_01i.do"
driver.get(url)

In [3]:
input_box = driver.find_element(By.CSS_SELECTOR, "#tmpInqStrDt")
input_box.clear()
input_box.send_keys("20250408")
search_button = driver.find_element(By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")
search_button.click()

In [4]:
# 날짜 입력
date_input = driver.find_element(By.CSS_SELECTOR, "#tmpInqStrDt")
date_input.clear()
date_input.send_keys("20250408")
date_input.send_keys(Keys.ENTER)

# 조회버튼 클릭
search_button = driver.find_element(By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")
search_button.click()

In [5]:
from io import StringIO

In [6]:
df = pd.read_html(StringIO(driver.find_element(By.CSS_SELECTOR, ".tblBasic.leftNone").get_attribute('outerHTML')))[0]
df

                 통화       현찰                              송금           \
                 통화     사실 때            파실 때            보낼 때     받을 때
                 통화       환율 Spread       환율 Spread     보낼 때     받을 때
0            미국 USD  1512.51   1.75  1460.49   1.75  1501.00  1472.00
1      일본 JPY (100)  1036.35   1.75  1000.71   1.75  1028.51  1008.55
2            유로 EUR  1663.21   1.99  1598.31   1.99  1647.06  1614.46
3            중국 CNY   210.70   5.00   190.64   5.00   202.67   198.67
4            홍콩 HKD   195.05   1.97   187.53   1.97   193.20   189.38
5            태국 THB    44.71   5.00    40.04   6.00    43.01    42.17
6            대만 TWD    50.73  13.10    40.38  10.00     0.00     0.00
7           필리핀 PHP    28.41  10.00    23.72   8.20    26.08    25.58
8          싱가포르 SGD  1120.61   1.99  1076.89   1.99  1109.73  1087.77
9            호주 AUD   902.57   1.97   867.71   1.97   893.99   876.29
10    베트남 VND (100)     6.40  11.80     5.06  11.80     5.78     5.68
11           영국 GBP  1937.55   1.97  1862.69   1.97  1919.12  1881.12
12          캐나다 CAD  1063.19   1.97  1022.11   1.97  1053.07  1032.23
13        말레이시아 MYR   355.49   7.40   306.51   7.40     0.00   327.69
14          러시아 RUB    18.96   9.50    14.29  17.50    17.92    16.72
15        남아공화국 ZAR    81.31   8.00    69.27   8.00    76.19    74.39
16         노르웨이 NOK   140.30   3.30   128.08   5.70   137.17   134.47
17         뉴질랜드 NZD   837.62   1.97   805.26   1.97   829.65   813.23
18          덴마크 DKK   225.62   3.30   205.98   5.70   220.60   216.24
19          멕시코 MXN    78.78  10.50    63.82  10.50    72.01    70.59
20           몽골 MNT     0.00   0.00     0.00   0.00     0.00     0.00
21          바레인 BHD  4195.87   6.40  3628.02   8.00  3982.92  3904.06
22        방글라데시 BDT     0.00   0.00     0.00   0.00     0.00     0.00
23          브라질 BRL   272.32  10.20   222.41  10.00     0.00   244.16
24         브루나이 BND  1142.70   4.00  1032.83   6.00     0.00     0.00
25      사우디아라비아 SAR   420.93   6.30   368.67   6.90   399.94   392.04
26         스리랑카 LKR     0.00   0.00     0.00   0.00     0.00     0.00
27          스웨덴 SEK   153.51   3.30   140.14   5.70   150.09   147.13
28          스위스 CHF  1791.60   1.97  1722.38   1.97  1774.55  1739.43
29    아랍에미리트공화국 AED   426.95   5.50   376.78   6.90   408.74   400.66
30          알제리 DZD     0.00   0.00     0.00   0.00     0.00     0.00
31           오만 OMR  4131.41   7.00  3590.87   7.00     0.00     0.00
32          요르단 JOD  2283.20   8.90  1928.89   8.00     0.00     0.00
33         이스라엘 ILS   432.63  10.00   361.84   8.00     0.00     0.00
34          이집트 EGP     0.00   0.00     0.00   0.00     0.00     0.00
35           인도 INR     0.00   0.00     0.00   0.00    17.42    17.04
36  인도네시아 IDR (100)     9.71  10.00     7.95  10.00     8.91     8.75
37           체코 CZK    70.18   8.50    58.87   9.00    65.40    63.98
38           칠레 CLP     1.63  10.00     1.35  10.00     0.00     0.00
39        카자흐스탄 KZT     0.00   0.00     0.00   0.00     0.00     0.00
40          카타르 QAR     0.00   0.00     0.00   0.00     0.00     0.00
41           케냐 KES     0.00   0.00     0.00   0.00     0.00     0.00
42         콜롬비아 COP     0.00   0.00     0.00   0.00     0.00     0.00
43         쿠웨이트 KWD  5138.00   6.50  4438.47   8.00  4872.66  4776.18
44         탄자니아 TZS     0.00   0.00     0.00   0.00     0.00     0.00
45         튀르키예 TRY     0.00   0.00     0.00   0.00    39.63    38.77
46         파키스탄 PKR     0.00   0.00     0.00   0.00     0.00     0.00
47          폴란드 PLN   412.32   8.00   351.24   8.00   385.97   377.59
48          헝가리 HUF     4.37   9.30     3.68   8.00     4.04     3.96
49           네팔 NPR     0.00   0.00     0.00   0.00     0.00     0.00
50          마카오 MOP     0.00   0.00     0.00   0.00     0.00     0.00
51         캄보디아 KHR     0.00   0.00     0.00   0.00     0.00     0.00
52           피지 FJD     0.00   0.00     0.00   0.00     0.00     0.00
53          리비아 LYD     0.00   0.00     0.00   0.00   269.96   264.62
54         루마니아 RON     0.00   0.00     0.00   0.00   331.26   324.06
55          미얀마 MMK     0.00   0.00     0.00   0.00     0.00     0.00
56        에티오피아 ETB     0.00   0.00     0.00   0.00     0.00     0.00
57       우즈베키스탄 UZS     0.00   0.00     0.00   0.00     0.00     0.00

   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
0    1469.47  1486.50   6.15079  1.0000
1    1007.90  1018.53   2.60318  0.6852
2    1612.51  1630.76   4.31600  1.0970
3       0.00   200.67   4.43712  0.1350
4     189.11   191.29   5.74800  0.1287
5      42.13    42.59   4.03366  0.0287
6       0.00    44.86   3.58766  0.0302
7       0.00    25.83   7.52400  0.0174
8    1086.49  1098.75   4.76033  0.7392
9     874.79   885.14   6.22766  0.5955
10      0.00     5.73   6.61166  0.0039
11   1877.72  1900.12   6.53300  1.2783
12   1030.85  1042.65   4.76900  0.7014
13      0.00   331.00   5.26066  0.2227
14      0.00    17.32   2.97500  0.0117
15      0.00    75.29   9.61100  0.0506
16    134.23   135.82   6.44133  0.0914
17    811.95   821.44   5.71166  0.5526
18    215.97   218.42   4.60800  0.1469
19      0.00    71.30  11.68300  0.0480
20      0.00     0.42  13.47500  0.0003
21   3895.56  3943.49   7.76900  2.6529
22      0.00    12.23  12.17370  0.0082
23      0.00   247.12  14.67000  0.1662
24      0.00  1098.75   4.67500  0.7392
25    391.22   395.99   7.47533  0.2664
26      0.00     4.96  11.50000  0.0033
27    146.95   148.61   4.40666  0.1000
28   1738.30  1756.99   2.32000  1.1820
29    400.10   404.70   5.07500  0.2723
30      0.00    11.13   5.97500  0.0075
31      0.00  3861.14   4.45500  2.5975
32      0.00  2096.61   8.73900  1.4104
33      0.00   393.30   6.56500  0.2646
34      0.00    28.99   5.97500  0.0195
35      0.00    17.23   9.06800  0.0116
36      8.74     8.83   8.42166  0.0059
37      0.00    64.69   5.73366  0.0435
38      0.00     1.49   6.12200  0.0010
39      0.00     2.87  16.97500  0.0019
40      0.00   407.82   3.35500  0.2743
41      0.00    11.48   9.78333  0.0077
42      0.00     0.34   0.00000  0.0002
43   4769.94  4824.42   4.65766  3.2455
44      0.00     0.55  10.27500  0.0004
45      0.00    39.20  49.80833  0.0264
46      0.00     5.30  18.24833  0.0036
47      0.00   381.78   8.13933  0.2568
48      0.00     4.00   8.44966  0.0027
49      0.00    10.77   0.00000  0.0072
50      0.00   185.58   0.00000  0.1248
51      0.00     0.37   0.00000  0.0002
52      0.00   633.84   0.00000  0.4264
53      0.00   267.29   0.00000  0.1798
54      0.00   327.66   7.75800  0.2204
55      0.00     0.71   0.00000  0.0005
56      0.00    11.24   0.00000  0.0076
57      0.00     0.11   0.00000  0.0001

In [7]:
df['date'] = "2025-04-08"
df

                 통화       현찰                              송금           \
                 통화     사실 때            파실 때            보낼 때     받을 때
                 통화       환율 Spread       환율 Spread     보낼 때     받을 때
0            미국 USD  1512.51   1.75  1460.49   1.75  1501.00  1472.00
1      일본 JPY (100)  1036.35   1.75  1000.71   1.75  1028.51  1008.55
2            유로 EUR  1663.21   1.99  1598.31   1.99  1647.06  1614.46
3            중국 CNY   210.70   5.00   190.64   5.00   202.67   198.67
4            홍콩 HKD   195.05   1.97   187.53   1.97   193.20   189.38
5            태국 THB    44.71   5.00    40.04   6.00    43.01    42.17
6            대만 TWD    50.73  13.10    40.38  10.00     0.00     0.00
7           필리핀 PHP    28.41  10.00    23.72   8.20    26.08    25.58
8          싱가포르 SGD  1120.61   1.99  1076.89   1.99  1109.73  1087.77
9            호주 AUD   902.57   1.97   867.71   1.97   893.99   876.29
10    베트남 VND (100)     6.40  11.80     5.06  11.80     5.78     5.68
11           영국 GBP  1937.55   1.97  1862.69   1.97  1919.12  1881.12
12          캐나다 CAD  1063.19   1.97  1022.11   1.97  1053.07  1032.23
13        말레이시아 MYR   355.49   7.40   306.51   7.40     0.00   327.69
14          러시아 RUB    18.96   9.50    14.29  17.50    17.92    16.72
15        남아공화국 ZAR    81.31   8.00    69.27   8.00    76.19    74.39
16         노르웨이 NOK   140.30   3.30   128.08   5.70   137.17   134.47
17         뉴질랜드 NZD   837.62   1.97   805.26   1.97   829.65   813.23
18          덴마크 DKK   225.62   3.30   205.98   5.70   220.60   216.24
19          멕시코 MXN    78.78  10.50    63.82  10.50    72.01    70.59
20           몽골 MNT     0.00   0.00     0.00   0.00     0.00     0.00
21          바레인 BHD  4195.87   6.40  3628.02   8.00  3982.92  3904.06
22        방글라데시 BDT     0.00   0.00     0.00   0.00     0.00     0.00
23          브라질 BRL   272.32  10.20   222.41  10.00     0.00   244.16
24         브루나이 BND  1142.70   4.00  1032.83   6.00     0.00     0.00
25      사우디아라비아 SAR   420.93   6.30   368.67   6.90   399.94   392.04
26         스리랑카 LKR     0.00   0.00     0.00   0.00     0.00     0.00
27          스웨덴 SEK   153.51   3.30   140.14   5.70   150.09   147.13
28          스위스 CHF  1791.60   1.97  1722.38   1.97  1774.55  1739.43
29    아랍에미리트공화국 AED   426.95   5.50   376.78   6.90   408.74   400.66
30          알제리 DZD     0.00   0.00     0.00   0.00     0.00     0.00
31           오만 OMR  4131.41   7.00  3590.87   7.00     0.00     0.00
32          요르단 JOD  2283.20   8.90  1928.89   8.00     0.00     0.00
33         이스라엘 ILS   432.63  10.00   361.84   8.00     0.00     0.00
34          이집트 EGP     0.00   0.00     0.00   0.00     0.00     0.00
35           인도 INR     0.00   0.00     0.00   0.00    17.42    17.04
36  인도네시아 IDR (100)     9.71  10.00     7.95  10.00     8.91     8.75
37           체코 CZK    70.18   8.50    58.87   9.00    65.40    63.98
38           칠레 CLP     1.63  10.00     1.35  10.00     0.00     0.00
39        카자흐스탄 KZT     0.00   0.00     0.00   0.00     0.00     0.00
40          카타르 QAR     0.00   0.00     0.00   0.00     0.00     0.00
41           케냐 KES     0.00   0.00     0.00   0.00     0.00     0.00
42         콜롬비아 COP     0.00   0.00     0.00   0.00     0.00     0.00
43         쿠웨이트 KWD  5138.00   6.50  4438.47   8.00  4872.66  4776.18
44         탄자니아 TZS     0.00   0.00     0.00   0.00     0.00     0.00
45         튀르키예 TRY     0.00   0.00     0.00   0.00    39.63    38.77
46         파키스탄 PKR     0.00   0.00     0.00   0.00     0.00     0.00
47          폴란드 PLN   412.32   8.00   351.24   8.00   385.97   377.59
48          헝가리 HUF     4.37   9.30     3.68   8.00     4.04     3.96
49           네팔 NPR     0.00   0.00     0.00   0.00     0.00     0.00
50          마카오 MOP     0.00   0.00     0.00   0.00     0.00     0.00
51         캄보디아 KHR     0.00   0.00     0.00   0.00     0.00     0.00
52           피지 FJD     0.00   0.00     0.00   0.00     0.00     0.00
53          리비아 LYD     0.00   0.00     0.00   0.00   269.96   264.62
54         루마니아 RON     0.00   0.00     0.00   0.00   331.26   324.06
55          미얀마 MMK     0.00   0.00     0.00   0.00     0.00     0.00
56        에티오피아 ETB     0.00   0.00     0.00   0.00     0.00     0.00
57       우즈베키스탄 UZS     0.00   0.00     0.00   0.00     0.00     0.00

   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율        date
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
0    1469.47  1486.50   6.15079  1.0000  2025-04-08
1    1007.90  1018.53   2.60318  0.6852  2025-04-08
2    1612.51  1630.76   4.31600  1.0970  2025-04-08
3       0.00   200.67   4.43712  0.1350  2025-04-08
4     189.11   191.29   5.74800  0.1287  2025-04-08
5      42.13    42.59   4.03366  0.0287  2025-04-08
6       0.00    44.86   3.58766  0.0302  2025-04-08
7       0.00    25.83   7.52400  0.0174  2025-04-08
8    1086.49  1098.75   4.76033  0.7392  2025-04-08
9     874.79   885.14   6.22766  0.5955  2025-04-08
10      0.00     5.73   6.61166  0.0039  2025-04-08
11   1877.72  1900.12   6.53300  1.2783  2025-04-08
12   1030.85  1042.65   4.76900  0.7014  2025-04-08
13      0.00   331.00   5.26066  0.2227  2025-04-08
14      0.00    17.32   2.97500  0.0117  2025-04-08
15      0.00    75.29   9.61100  0.0506  2025-04-08
16    134.23   135.82   6.44133  0.0914  2025-04-08
17    811.95   821.44   5.71166  0.5526  2025-04-08
18    215.97   218.42   4.60800  0.1469  2025-04-08
19      0.00    71.30  11.68300  0.0480  2025-04-08
20      0.00     0.42  13.47500  0.0003  2025-04-08
21   3895.56  3943.49   7.76900  2.6529  2025-04-08
22      0.00    12.23  12.17370  0.0082  2025-04-08
23      0.00   247.12  14.67000  0.1662  2025-04-08
24      0.00  1098.75   4.67500  0.7392  2025-04-08
25    391.22   395.99   7.47533  0.2664  2025-04-08
26      0.00     4.96  11.50000  0.0033  2025-04-08
27    146.95   148.61   4.40666  0.1000  2025-04-08
28   1738.30  1756.99   2.32000  1.1820  2025-04-08
29    400.10   404.70   5.07500  0.2723  2025-04-08
30      0.00    11.13   5.97500  0.0075  2025-04-08
31      0.00  3861.14   4.45500  2.5975  2025-04-08
32      0.00  2096.61   8.73900  1.4104  2025-04-08
33      0.00   393.30   6.56500  0.2646  2025-04-08
34      0.00    28.99   5.97500  0.0195  2025-04-08
35      0.00    17.23   9.06800  0.0116  2025-04-08
36      8.74     8.83   8.42166  0.0059  2025-04-08
37      0.00    64.69   5.73366  0.0435  2025-04-08
38      0.00     1.49   6.12200  0.0010  2025-04-08
39      0.00     2.87  16.97500  0.0019  2025-04-08
40      0.00   407.82   3.35500  0.2743  2025-04-08
41      0.00    11.48   9.78333  0.0077  2025-04-08
42      0.00     0.34   0.00000  0.0002  2025-04-08
43   4769.94  4824.42   4.65766  3.2455  2025-04-08
44      0.00     0.55  10.27500  0.0004  2025-04-08
45      0.00    39.20  49.80833  0.0264  2025-04-08
46      0.00     5.30  18.24833  0.0036  2025-04-08
47      0.00   381.78   8.13933  0.2568  2025-04-08
48      0.00     4.00   8.44966  0.0027  2025-04-08
49      0.00    10.77   0.00000  0.0072  2025-04-08
50      0.00   185.58   0.00000  0.1248  2025-04-08
51      0.00     0.37   0.00000  0.0002  2025-04-08
52      0.00   633.84   0.00000  0.4264  2025-04-08
53      0.00   267.29   0.00000  0.1798  2025-04-08
54      0.00   327.66   7.75800  0.2204  2025-04-08
55      0.00     0.71   0.00000  0.0005  2025-04-08
56      0.00    11.24   0.00000  0.0076  2025-04-08
57      0.00     0.11   0.00000  0.0001  2025-04-08

In [8]:
df.columns

MultiIndex([(       '통화',        '통화',        '통화'),
            (       '현찰',      '사실 때',        '환율'),
            (       '현찰',      '사실 때',    'Spread'),
            (       '현찰',      '파실 때',        '환율'),
            (       '현찰',      '파실 때',    'Spread'),
            (       '송금',      '보낼 때',      '보낼 때'),
            (       '송금',      '받을 때',      '받을 때'),
            ('외화 수표 파실때', '외화 수표 파실때', '외화 수표 파실때'),
            (   '매매 기준율',    '매매 기준율',    '매매 기준율'),
            (    '환가 료율',     '환가 료율',     '환가 료율'),
            (   '미화 환산율',    '미화 환산율',    '미화 환산율'),
            (     'date',          '',          '')],
           )

# 날짜 생성하기
* 1995-01-03 - 어제까지(2025-04-08) 날짜 생성하기
* 평일만 날짜 생성
* 날짜 리스트에 모든 날짜 저장

In [ ]:
import datetime

In [ ]:
# weekday() : 요일 표시
datetime.now().weekday()

In [ ]:
print(datetime.datetime.now(), type(datetime.datetime.now()))

In [ ]:
start_day = datetime.date(2025, 4, 1)
end_day = datetime.date(2025, 4, 11)

In [ ]:
# 날짜 데이터 타입은 논리 연산(비교 가능)
start_day != end_day

In [ ]:
# datetime.timedelta() 로 날짜 증감 가능

In [ ]:
day_increased = start_day + datetime.timedelta(days=9)
print(f"start_day: {start_day}\n, day_increased: {day_increased}\n, end_day: {end_day}\n", day_increased==end_day)

In [ ]:
# weekday() 는 월 0, 화 1, 수 2, 목 3, 금 4, 토 5 일 6
for days in range(1,10):
#     print(current_date + datetime.timedelta(days=days))
    day = start_day + datetime.timedelta(days=days)
    if day.weekday() < 5:
        print(day, day.weekday())

# 시작일과 끝일을 입력해서 평일만 생성하기

In [ ]:
start_date = datetime.date(2025, 4, 1)
end_date = datetime.date(2025, 4, 8)

In [ ]:
date_list = []
while start_date <= end_date:
    # 평일인지 필터링
    if start_date.weekday() < 5:
        date_list.append(start_date)
    start_date += datetime.timedelta(days = 1)
date_list

In [ ]:
print(str(date_list[0]).replace("-", ""))

In [ ]:
# list -> 1개의 문자열로 합치는 함수: join()
# 문자열을 -> list : split()

In [ ]:
# 중복된 자료 제거 1 set 집합자료형
# set 자료형은 순서가 없음
print(set(df.columns[0]))
print(set(df.columns[1]))
print(set(df.columns[1]))

In [9]:
df.columns

MultiIndex([(       '통화',        '통화',        '통화'),
            (       '현찰',      '사실 때',        '환율'),
            (       '현찰',      '사실 때',    'Spread'),
            (       '현찰',      '파실 때',        '환율'),
            (       '현찰',      '파실 때',    'Spread'),
            (       '송금',      '보낼 때',      '보낼 때'),
            (       '송금',      '받을 때',      '받을 때'),
            ('외화 수표 파실때', '외화 수표 파실때', '외화 수표 파실때'),
            (   '매매 기준율',    '매매 기준율',    '매매 기준율'),
            (    '환가 료율',     '환가 료율',     '환가 료율'),
            (   '미화 환산율',    '미화 환산율',    '미화 환산율'),
            (     'date',          '',          '')],
           )

In [11]:
new_cols = []
for col in df.columns:
    print(col)
    if col[0] == col[1] == col[2]:
        new_cols.append(col[0].strip().replace(" ", "_"))
#         print(col[0].strip().replace(" ", "_"), end="\n\n")
    else:
        new_cols.append(" ".join(col).strip().replace(" ", "_"))

('통화', '통화', '통화')
('현찰', '사실 때', '환율')
('현찰', '사실 때', 'Spread')
('현찰', '파실 때', '환율')
('현찰', '파실 때', 'Spread')
('송금', '보낼 때', '보낼 때')
('송금', '받을 때', '받을 때')
('외화 수표 파실때', '외화 수표 파실때', '외화 수표 파실때')
('매매 기준율', '매매 기준율', '매매 기준율')
('환가 료율', '환가 료율', '환가 료율')
('미화 환산율', '미화 환산율', '미화 환산율')
('date', '', '')

In [12]:
new_cols

['통화',
 '현찰_사실_때_환율',
 '현찰_사실_때_Spread',
 '현찰_파실_때_환율',
 '현찰_파실_때_Spread',
 '송금_보낼_때_보낼_때',
 '송금_받을_때_받을_때',
 '외화_수표_파실때',
 '매매_기준율',
 '환가_료율',
 '미화_환산율',
 'date']

In [13]:
df.columns = new_cols
df

,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화_수표_파실때,매매_기준율,환가_료율,미화_환산율,date
0,미국 USD,1512.51,1.75,1460.49,1.75,1501.00,1472.00,1469.47,1486.50,6.15079,1.0000,2025-04-08
1,일본 JPY (100),1036.35,1.75,1000.71,1.75,1028.51,1008.55,1007.90,1018.53,2.60318,0.6852,2025-04-08
2,유로 EUR,1663.21,1.99,1598.31,1.99,1647.06,1614.46,1612.51,1630.76,4.31600,1.0970,2025-04-08
3,중국 CNY,210.70,5.00,190.64,5.00,202.67,198.67,0.00,200.67,4.43712,0.1350,2025-04-08
4,홍콩 HKD,195.05,1.97,187.53,1.97,193.20,189.38,189.11,191.29,5.74800,0.1287,2025-04-08
5,태국 THB,44.71,5.00,40.04,6.00,43.01,42.17,42.13,42.59,4.03366,0.0287,2025-04-08
6,대만 TWD,50.73,13.10,40.38,10.00,0.00,0.00,0.00,44.86,3.58766,0.0302,2025-04-08
7,필리핀 PHP,28.41,10.00,23.72,8.20,26.08,25.58,0.00,25.83,7.52400,0.0174,2025-04-08
8,싱가포르 SGD,1120.61,1.99,1076.89,1.99,1109.73,1087.77,1086.49,1098.75,4.76033,0.7392,2025-04-08
9,호주 AUD,902.57,1.97,867.71,1.97,893.99,876.29,874.79,885.14,6.22766,0.5955,2025-04-08
10,베트남 VND (100),6.40,11.80,5.06,11.80,5.78,5.68,0.00,5.73,6.61166,0.0039,2025-04-08
11,영국 GBP,1937.55,1.97,1862.69,1.97,1919.12,1881.12,1877.72,1900.12,6.53300,1.2783,2025-04-08
12,캐나다 CAD,1063.19,1.97,1022.11,1.97,1053.07,1032.23,1030.85,1042.65,4.76900,0.7014,2025-04-08
13,말레이시아 MYR,355.49,7.40,306.51,7.40,0.00,327.69,0.00,331.00,5.26066,0.2227,2025-04-08
14,러시아 RUB,18.96,9.50,14.29,17.50,17.92,16.72,0.00,17.32,2.97500,0.0117,2025-04-08
15,남아공화국 ZAR,81.31,8.00,69.27,8.00,76.19,74.39,0.00,75.29,9.61100,0.0506,2025-04-08
16,노르웨이 NOK,140.30,3.30,128.08,5.70,137.17,134.47,134.23,135.82,6.44133,0.0914,2025-04-08
17,뉴질랜드 NZD,837.62,1.97,805.26,1.97,829.65,813.23,811.95,821.44,5.71166,0.5526,2025-04-08
18,덴마크 DKK,225.62,3.30,205.98,5.70,220.60,216.24,215.97,218.42,4.60800,0.1469,2025-04-08
19,멕시코 MXN,78.78,10.50,63.82,10.50,72.01,70.59,0.00,71.30,11.68300,0.0480,2025-04-08
20,몽골 MNT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.42,13.47500,0.0003,2025-04-08
21,바레인 BHD,4195.87,6.40,3628.02,8.00,3982.92,3904.06,3895.56,3943.49,7.76900,2.6529,2025-04-08
22,방글라데시 BDT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.23,12.17370,0.0082,2025-04-08
23,브라질 BRL,272.32,10.20,222.41,10.00,0.00,244.16,0.00,247.12,14.67000,0.1662,2025-04-08
24,브루나이 BND,1142.70,4.00,1032.83,6.00,0.00,0.00,0.00,1098.75,4.67500,0.7392,2025-04-08
25,사우디아라비아 SAR,420.93,6.30,368.67,6.90,399.94,392.04,391.22,395.99,7.47533,0.2664,2025-04-08
26,스리랑카 LKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.96,11.50000,0.0033,2025-04-08
27,스웨덴 SEK,153.51,3.30,140.14,5.70,150.09,147.13,146.95,148.61,4.40666,0.1000,2025-04-08
28,스위스 CHF,1791.60,1.97,1722.38,1.97,1774.55,1739.43,1738.30,1756.99,2.32000,1.1820,2025-04-08
29,아랍에미리트공화국 AED,426.95,5.50,376.78,6.90,408.74,400.66,400.10,404.70,5.07500,0.2723,2025-04-08
30,알제리 DZD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.13,5.97500,0.0075,2025-04-08
31,오만 OMR,4131.41,7.00,3590.87,7.00,0.00,0.00,0.00,3861.14,4.45500,2.5975,2025-04-08
32,요르단 JOD,2283.20,8.90,1928.89,8.00,0.00,0.00,0.00,2096.61,8.73900,1.4104,2025-04-08
33,이스라엘 ILS,432.63,10.00,361.84,8.00,0.00,0.00,0.00,393.30,6.56500,0.2646,2025-04-08
34,이집트 EGP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,28.99,5.97500,0.0195,2025-04-08
35,인도 INR,0.00,0.00,0.00,0.00,17.42,17.04,0.00,17.23,9.06800,0.0116,2025-04-08
36,인도네시아 IDR (100),9.71,10.00,7.95,10.00,8.91,8.75,8.74,8.83,8.42166,0.0059,2025-04-08
37,체코 CZK,70.18,8.50,58.87,9.00,65.40,63.98,0.00,64.69,5.73366,0.0435,2025-04-08
38,칠레 CLP,1.63,10.00,1.35,10.00,0.00,0.00,0.00,1.49,6.12200,0.0010,2025-04-08
39,카자흐스탄 KZT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.87,16.97500,0.0019,2025-04-08
40,카타르 QAR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,407.82,3.35500,0.2743,2025-04-08
41,케냐 KES,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.48,9.78333,0.0077,2025-04-08
42,콜롬비아 COP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.34,0.00000,0.0002,2025-04-08
43,쿠웨이트 KWD,5138.00,6.50,4438.47,8.00,4872.66,4776.18,4769.94,4824.42,4.65766,3.2455,2025-04-08
44,탄자니아 TZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.55,10.27500,0.0004,2025-04-08
45,튀르키예 TRY,0.00,0.00,0.00,0.00,39.63,38.77,0.00,39.20,49.80833,0.0264,2025-04-08
46,파키스탄 PKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.30,18.24833,0.0036,2025-04-08
47,폴란드 PLN,412.32,8.00,351.24,8.00,385.97,377.59,0.00,381.78,8.13933,0.2568,2025-04-08
48,헝가리 HUF,4.37,9.30,3.68,8.00,4.04,3.96,0.00,4.00,8.44966,0.0027,2025-04-08
49,네팔 NPR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.77,0.00000,0.0072,2025-04-08
50,마카오 MOP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,185.58,0.00000,0.1248,2025-04-08
51,캄보디아 KHR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.37,0.00000,0.0002,2025-04-08
52,피지 FJD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,633.84,0.00000,0.4264,2025-04-08
53,리비아 LYD,0.00,0.00,0.00,0.00,269.96,264.62,0.00,267.29,0.00000,0.1798,2025-04-08
54,루마니아 RON,0.00,0.00,0.00,0.00,331.26,324.06,0.00,327.66,7.75800,0.2204,2025-04-08
55,미얀마 MMK,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.71,0.00000,0.0005,2025-04-08
56,에티오피아 ETB,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.24,0.00000,0.0076,2025-04-08
57,우즈베키스탄 UZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.11,0.00000,0.0001,2025-04-08

In [14]:
df.columns

Index(['통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
       '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화_수표_파실때', '매매_기준율', '환가_료율',
       '미화_환산율', 'date'],
      dtype='object')

In [15]:
df = df[['date', '통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
       '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화_수표_파실때', '매매_기준율', '환가_료율',
       '미화_환산율']]
df

,date,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화_수표_파실때,매매_기준율,환가_료율,미화_환산율
0,2025-04-08,미국 USD,1512.51,1.75,1460.49,1.75,1501.00,1472.00,1469.47,1486.50,6.15079,1.0000
1,2025-04-08,일본 JPY (100),1036.35,1.75,1000.71,1.75,1028.51,1008.55,1007.90,1018.53,2.60318,0.6852
2,2025-04-08,유로 EUR,1663.21,1.99,1598.31,1.99,1647.06,1614.46,1612.51,1630.76,4.31600,1.0970
3,2025-04-08,중국 CNY,210.70,5.00,190.64,5.00,202.67,198.67,0.00,200.67,4.43712,0.1350
4,2025-04-08,홍콩 HKD,195.05,1.97,187.53,1.97,193.20,189.38,189.11,191.29,5.74800,0.1287
5,2025-04-08,태국 THB,44.71,5.00,40.04,6.00,43.01,42.17,42.13,42.59,4.03366,0.0287
6,2025-04-08,대만 TWD,50.73,13.10,40.38,10.00,0.00,0.00,0.00,44.86,3.58766,0.0302
7,2025-04-08,필리핀 PHP,28.41,10.00,23.72,8.20,26.08,25.58,0.00,25.83,7.52400,0.0174
8,2025-04-08,싱가포르 SGD,1120.61,1.99,1076.89,1.99,1109.73,1087.77,1086.49,1098.75,4.76033,0.7392
9,2025-04-08,호주 AUD,902.57,1.97,867.71,1.97,893.99,876.29,874.79,885.14,6.22766,0.5955
10,2025-04-08,베트남 VND (100),6.40,11.80,5.06,11.80,5.78,5.68,0.00,5.73,6.61166,0.0039
11,2025-04-08,영국 GBP,1937.55,1.97,1862.69,1.97,1919.12,1881.12,1877.72,1900.12,6.53300,1.2783
12,2025-04-08,캐나다 CAD,1063.19,1.97,1022.11,1.97,1053.07,1032.23,1030.85,1042.65,4.76900,0.7014
13,2025-04-08,말레이시아 MYR,355.49,7.40,306.51,7.40,0.00,327.69,0.00,331.00,5.26066,0.2227
14,2025-04-08,러시아 RUB,18.96,9.50,14.29,17.50,17.92,16.72,0.00,17.32,2.97500,0.0117
15,2025-04-08,남아공화국 ZAR,81.31,8.00,69.27,8.00,76.19,74.39,0.00,75.29,9.61100,0.0506
16,2025-04-08,노르웨이 NOK,140.30,3.30,128.08,5.70,137.17,134.47,134.23,135.82,6.44133,0.0914
17,2025-04-08,뉴질랜드 NZD,837.62,1.97,805.26,1.97,829.65,813.23,811.95,821.44,5.71166,0.5526
18,2025-04-08,덴마크 DKK,225.62,3.30,205.98,5.70,220.60,216.24,215.97,218.42,4.60800,0.1469
19,2025-04-08,멕시코 MXN,78.78,10.50,63.82,10.50,72.01,70.59,0.00,71.30,11.68300,0.0480
20,2025-04-08,몽골 MNT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.42,13.47500,0.0003
21,2025-04-08,바레인 BHD,4195.87,6.40,3628.02,8.00,3982.92,3904.06,3895.56,3943.49,7.76900,2.6529
22,2025-04-08,방글라데시 BDT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.23,12.17370,0.0082
23,2025-04-08,브라질 BRL,272.32,10.20,222.41,10.00,0.00,244.16,0.00,247.12,14.67000,0.1662
24,2025-04-08,브루나이 BND,1142.70,4.00,1032.83,6.00,0.00,0.00,0.00,1098.75,4.67500,0.7392
25,2025-04-08,사우디아라비아 SAR,420.93,6.30,368.67,6.90,399.94,392.04,391.22,395.99,7.47533,0.2664
26,2025-04-08,스리랑카 LKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.96,11.50000,0.0033
27,2025-04-08,스웨덴 SEK,153.51,3.30,140.14,5.70,150.09,147.13,146.95,148.61,4.40666,0.1000
28,2025-04-08,스위스 CHF,1791.60,1.97,1722.38,1.97,1774.55,1739.43,1738.30,1756.99,2.32000,1.1820
29,2025-04-08,아랍에미리트공화국 AED,426.95,5.50,376.78,6.90,408.74,400.66,400.10,404.70,5.07500,0.2723
30,2025-04-08,알제리 DZD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.13,5.97500,0.0075
31,2025-04-08,오만 OMR,4131.41,7.00,3590.87,7.00,0.00,0.00,0.00,3861.14,4.45500,2.5975
32,2025-04-08,요르단 JOD,2283.20,8.90,1928.89,8.00,0.00,0.00,0.00,2096.61,8.73900,1.4104
33,2025-04-08,이스라엘 ILS,432.63,10.00,361.84,8.00,0.00,0.00,0.00,393.30,6.56500,0.2646
34,2025-04-08,이집트 EGP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,28.99,5.97500,0.0195
35,2025-04-08,인도 INR,0.00,0.00,0.00,0.00,17.42,17.04,0.00,17.23,9.06800,0.0116
36,2025-04-08,인도네시아 IDR (100),9.71,10.00,7.95,10.00,8.91,8.75,8.74,8.83,8.42166,0.0059
37,2025-04-08,체코 CZK,70.18,8.50,58.87,9.00,65.40,63.98,0.00,64.69,5.73366,0.0435
38,2025-04-08,칠레 CLP,1.63,10.00,1.35,10.00,0.00,0.00,0.00,1.49,6.12200,0.0010
39,2025-04-08,카자흐스탄 KZT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.87,16.97500,0.0019
40,2025-04-08,카타르 QAR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,407.82,3.35500,0.2743
41,2025-04-08,케냐 KES,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.48,9.78333,0.0077
42,2025-04-08,콜롬비아 COP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.34,0.00000,0.0002
43,2025-04-08,쿠웨이트 KWD,5138.00,6.50,4438.47,8.00,4872.66,4776.18,4769.94,4824.42,4.65766,3.2455
44,2025-04-08,탄자니아 TZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.55,10.27500,0.0004
45,2025-04-08,튀르키예 TRY,0.00,0.00,0.00,0.00,39.63,38.77,0.00,39.20,49.80833,0.0264
46,2025-04-08,파키스탄 PKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.30,18.24833,0.0036
47,2025-04-08,폴란드 PLN,412.32,8.00,351.24,8.00,385.97,377.59,0.00,381.78,8.13933,0.2568
48,2025-04-08,헝가리 HUF,4.37,9.30,3.68,8.00,4.04,3.96,0.00,4.00,8.44966,0.0027
49,2025-04-08,네팔 NPR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.77,0.00000,0.0072
50,2025-04-08,마카오 MOP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,185.58,0.00000,0.1248
51,2025-04-08,캄보디아 KHR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.37,0.00000,0.0002
52,2025-04-08,피지 FJD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,633.84,0.00000,0.4264
53,2025-04-08,리비아 LYD,0.00,0.00,0.00,0.00,269.96,264.62,0.00,267.29,0.00000,0.1798
54,2025-04-08,루마니아 RON,0.00,0.00,0.00,0.00,331.26,324.06,0.00,327.66,7.75800,0.2204
55,2025-04-08,미얀마 MMK,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.71,0.00000,0.0005
56,2025-04-08,에티오피아 ETB,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.24,0.00000,0.0076
57,2025-04-08,우즈베키스탄 UZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.11,0.00000,0.0001

In [ ]:
import datetime
today = datetime.datetime.now()
print(today.year)
print(today.month)
print(today.day)

# 코드 합쳐서 전체 날짜 데이터 추출하기

In [ ]:
def new_col(df):
    new_cols = []
    for col in df.columns:
        if col[0] == col[1] == col[2]:
            new_cols.append(col[0].strip().replace(" ", "_"))
        else:
            new_cols.append(" ".join(col).strip().replace(" ", "_"))
    return new_cols

In [ ]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
from io import StringIO
import time
from ex_dbio import to_ex_db

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/135.0.0.0")
options.add_argument("lang=ko_KR")
# 웹브라우저가 백그라운드에서 작동하도록 설정
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )

url = "https://www.kebhana.com/cms/rate/index.do?contentUrl=/cms/rate/wpfxd651_01i.do"
driver.get(url)

wait = WebDriverWait(driver, 10)

# 시작일과 끝일 입력해서 날짜 리스트 생성
start_date = datetime.date(1995, 1, 3)
end_date = datetime.date(2025, 4, 10)

date_list = []
while start_date <= end_date:
    # 평일인지 필터링
    if start_date.weekday() < 5:
        date_list.append(start_date)
    start_date += datetime.timedelta(days = 1)

for date in date_list:
    # 날짜 입력
    date_input = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#tmpInqStrDt")))
    date_input.clear()
    date_input.send_keys(str(date).replace("-", ""))
    date_input.send_keys(Keys.ENTER)

    # 조회버튼 클릭
    search_button = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")))
    search_button.click()
    time.sleep(2)
    df = pd.read_html(StringIO(driver.find_element(By.CSS_SELECTOR, ".tblBasic.leftNone").get_attribute('outerHTML')))[0]
    df['date'] = date
    new_columns = new_col(df)
    df.columns = new_columns
    df = df[['date', '통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
       '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화_수표_파실때', '매매_기준율', '환가_료율',
       '미화_환산율']]
    to_ex_db(df)
    print(f"{date} 환율정보 DB 저장 완료", end="\r")

# 오늘의 환율 데이터 저장하기

In [1]:
def new_col(df):
    new_cols = []
    for col in df.columns:
        if col[0] == col[1] == col[2]:
            new_cols.append(col[0].strip().replace(" ", "_"))
        else:
            new_cols.append(" ".join(col).strip().replace(" ", "_"))
    return new_cols

In [2]:
# import datetime
# today = datetime.datetime.now()
# date = f"{today.year}-{today.month:02d}-{today.day:02d}"
# print(date)

In [3]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
from io import StringIO
import time
from ex_dbio import to_ex_db_test

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/135.0.0.0")
options.add_argument("lang=ko_KR")
# 웹브라우저가 백그라운드에서 작동하도록 설정
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )

url = "https://www.kebhana.com/cms/rate/index.do?contentUrl=/cms/rate/wpfxd651_01i.do"
driver.get(url)

wait = WebDriverWait(driver, 20)

# 오늘날짜 20250411 형식으로 가져오기
today = datetime.datetime.now()
date = f"{today.year}-{today.month:02d}-{today.day:02d}"

date_input = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#tmpInqStrDt")))
date_input.clear()
date_input.send_keys(date.replace("-", ""))
date_input.send_keys(Keys.ENTER)

# 조회버튼 클릭
search_button = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")))
search_button.click()
time.sleep(2)
df = pd.read_html(StringIO(driver.find_element(By.CSS_SELECTOR, ".tblBasic.leftNone").get_attribute('outerHTML')))[0]
df['date'] = date
new_columns = new_col(df)
df.columns = new_columns
df = df[['date', '통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
   '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화_수표_파실때', '매매_기준율', '환가_료율',
   '미화_환산율']]
to_ex_db_test(df)
print(f"{date} 환율정보 DB 저장 완료", end="\r")